## PRB1.5. Capacity {#prb1.5.-capacity .Heading-2-ER}

- Portugal registered 0.28 minutes of average en route ATFM delay per flight during 2025, which remained 0.28 after the post-ops adjustment process, thus achieving the local target value of 0.30. Delays in Portugal decreased by -0.11 minutes per flight year-on-year.

- Delays were highest in January to April, mostly driven by ATC capacity, and in November and December due to non-ATC causes.

- The share of delayed flights with delays longer than 15 minutes in Portugal decreased by -5 percentage points compared to 2024.

- The number of ATCOs in OPS was 174 being below the 2025 plan in Lisbon ACC by -6 FTE.

- The yearly total of sector opening hours in Lisbon ACC was 70,152, showing a 2% increase compared to 2024.

- Lisbon ACC registered 10.06 IFR movements per sector opening hour in 2025 4% above the 2024 level.

- Portugal registered an average airport arrival ATFM delay of 1.88 minutes per flight in 2025, thus achieving the local target of 2.19 minutes. Compared to 2024, average arrival ATFM delays in Portugal were -0.82 minutes per flight lower higher in 2025.

- The main drivers of delays were weather, accounting for 1.33 of the total delays, and other non-ATC causes, responsible for 0.47.

