## SAF1.3. Rate of runway incursions (RIs) (PI#1)

Portugal has reported 18 runway incursions (RI) during 2025 for all airports listed in the performance plans (10). In terms of ATS/CNS contribution, Portugal reported 6 runway incursions.

When comparing the rate of RIs at airport level to Union-wide level, Portugal was higher than Union-wide average (3.31 vs 2.53). The rate has increased compared to 2024 (3.31 vs 0.38).

When comparing the rate of RIs at airport level with ATS/CNS contribution, Portugal was higher than Union-wide average (1.10 vs 0.96). The rate has increased compared to 2024 (1.10 vs 0.38).

In terms of the initiatives implemented or planned to improve this performance indicator, the report defines the following elements: Increased number of Observational Safety Surveys directed to the application of runway incursion preventive measures, namely the adherence to GAPPRI recommendations. Implementation of RWY Occupancy warning in the VAISALA system. Tighter coordination with aerodrome stakeholders through Local Runway Safety Team. Improvements in ground surveillance in LPPT, LPPR and LPFR (on-going developments). RI automatic warnings in Azores aerodromes (LPPD, LPHR, LPFL, LPAZ) through SATL-TWR system (on-going developments).

