## **TZ1.1. SECTION 1 -- UNIT COST**

### **TZ1.1.1. AUC VS. DUC**

In 2025, the terminal AUC was -7.4% (or -10.58 €2022) lower than the planned DUC. This results from the combination of significantly lower than planned terminal costs in real terms (-8.1%, or -4.0 M€2022) and slightly lower than planned TNSUs (-0.8%).

### **TZ1.1.2. TERMINAL SERVICE UNITS**

The difference between actual and planned TNSUs (-0.8%) falls inside the ±2% dead-band. Hence, the loss of terminal revenues is borne by the ANSPs.

### **TZ1.1.3. TERMINAL COSTS BY ENTITY**

Actual real terminal costs are -8.1% (-4.0 M€2022) lower than planned. This is the result of lower costs for the main ANSP, NAV Portugal (-8.4%, or -4.0 M€2022) and the NSA (-14.1%, or -0.1 M€2022) and higher costs for the MET service provider (+3.3%, or +0.1 M€2022).

### **TZ1.1.4. TERMINAL COSTS FOR THE MAIN ANSP (NAV PORTUGAL) AT CHARGING ZONE LEVEL**

Based on the additional information to the terminal reporting tables, the significantly lower than planned terminal costs in real terms for NAV Portugal in 2025 (-8.4%, or -4.0 M€2022) result from:

- Significantly lower than planned staff costs (-8.1%), mainly due to significantly lower-than-expected defined benefit pension costs, driven by favourable financial market conditions, while remuneration and other social charges remained in line with plan.

- Significantly lower than planned other operating costs (-7.6%), mainly due to lower electricity prices and reduced expenditure on rent and leasing, maintenance and repairs, and travel, partially offset by increased investment in IT and security.

- Slightly higher than planned depreciation (+1.7%), driven by the commissioning of investments implemented in recent years.

- Significantly lower than planned cost of capital (-51.0%) resulting from a much smaller-than expected asset base.

### **TZ1.1.5. ASSESSMENT OF THE ACTUAL PERFORMANCE IN THE CHARGING ZONE REPORTED BY THE NSA**

The NSA of Portugal provides the following overall assessment of the actual performance in 2025 at charging zone level:

*"Total terminal costs, in real terms, were 8.1% lower than planned, which, combined with a negative deviation of 0.8% in service units, resulted in an actual unit cost 7.4% lower than projected.*

*This result was based on NAV Portugal, whose actual costs were 8.4% lower than the estimated costs, mainly due to the behavior of costs associated with defined benefit pension funds, where savings resulting from market factors -- approximately 1.9 million euros -- will be returned to airspace users in the next reference period."*

### **TZ1.1.6. EXPLANATION OF THE DIFFERENCES BETWEEN ACTUAL AND DETERMINED COSTS AT CHARGING ZONE LEVEL REPORTED BY THE NSA**

The NSA provides the following explanation for the differences between actual and determined costs in the charging zone:

*"As justified above."*

### **TZ1.1.7. RECOMMENDATIONS FORMULATED BY THE NSA TO THE ANSP (NAV PORTUGAL) TO RECTIFY THE SITUATION AND ACTIONS TAKEN BY THE ANSP**

The NSA 2025 monitoring report indicates the following recommendations formulated by the NSA:

*"There is no deviation to rectify."*

NAV Portugal reports the implementation of the following actions:

*"The cost-efficiency targets for terminal have been met by the ANSP."*

### **TZ1.1.8. NOTES**

#### **TZ1.1.8.1. NOTE 1**

#### **TZ1.1.8.2. NOTE 2**

