## **2.3.3 ATCO Planning 1**

### **Additional comments**

NAV Portugal\'s efforts in recruiting and training new air traffic controllers have yielded positive results this year, as the initial gap between the actual and planned number of FTEs has been narrowed. It should be noted that the difference in the number of ATCOs in OPS, results mainly from the performance in 2024, when NAV ended the year 5 ATCOs short of expected. In 2025, NAV was only 1 ATCO short of initial estimates.

### **Additional comments**

Very similar numbers of air traffic controller movements throughout the year.

### **Description of the training process, including details on the effective failure rate and the process used to allocate newly qualified ATCOs between ACC, APP and TWR positions**

In this section, the total values ​​for NAV Portugal were considered.

While the first two lines refer to ab-initio training, the third line -- Number of air traffic controller trainees at the end of the year -- reports the on-job-trainees, of which 5 come from the ATC-FI 029 training course and 11 from the ATC-FI 030 training course.

