## **TZ1.3. SECTION 3 -- REGULATORY RESULT**

### **TZ1.3.1. FINTRAFFIC ANS NET GAIN/LOSS ON ACTIVITY IN THE FINLAND TERMINAL CHARGING ZONE IN 2025**

Fintraffic ANS reported a net gain of +0.8 M€, as a combination of a gain of +1.1 M€ arising from the cost sharing mechanism, with a loss of -0.4 M€ arising from the traffic risk sharing mechanism.

### **TZ1.3.2. FINTRAFFIC ANS OVERALL REGULATORY RESULT (RR) ON ACTIVITY IN THE TERMINAL CHARING ZONE** 

Ex-post, the overall RR, taking into account the net gain from the terminal activity mentioned above (+0.8 M€) and the actual RoE (+0.2 M€), amounts to +1.0 M€ (5.6% of the terminal revenues). The resulting ex-post rate of return on equity is 22.7%, which is higher than the 4.8% planned in the PP (see also Note 1 below).

### **TZ1.3.3. NOTES**

#### **TZ1.3.3.1. NOTE 1**

The ex-post RR does not take into account the application of a lower unit rate in 2025 as per Art. 29.6 (the loss in revenues corresponds to -0.5 M€ for 2025).

#### **TZ1.3.3.2. NOTE 2**
