## **TZ1.1. SECTION 1 -- UNIT COST**

### **TZ1.1.1. AUC VS. DUC**

In 2025, the terminal AUC was -6.0% (or -10.75 €2022) lower than the planned DUC. This results from the combination of significantly lower than planned terminal costs in real terms (-8.3%, or -1.5 M€2022) and lower than planned TNSUs (-2.4%).

### **TZ1.1.2. TERMINAL SERVICE UNITS**

The difference between actual and planned TNSUs (-2.4%) falls outside the ±2% dead-band, but does not exceed the ±10% threshold foreseen in the traffic risk sharing mechanism. The resulting loss of terminal revenues is therefore shared between the ANSP and the airspace users (see the main ANSP regulatory result).

### **TZ1.1.3. TERMINAL COSTS BY ENTITY**

Actual real terminal costs are -8.3% (-1.5 M€2022) lower than planned. This is the result of lower costs for the main ANSP, Fintraffic ANS (-9.3%, or -1.6 M€2022) and higher costs for the MET service provider (+1.7%), while the NSA costs were consistent with those planned.

### **TZ1.1.4. TERMINAL COSTS FOR THE MAIN ANSP (FINTRAFFIC ANS) AT CHARGING ZONE LEVEL**

Based on the additional information to the terminal reporting tables, the significantly lower than planned terminal costs in real terms for Fintraffic ANS in 2025 (-9.3%, or -1.6 M€2022) result from:

- Significantly lower than planned staff costs (-8.2%), due to multiple factors, including: lower than planned personnel fund contributions; reduced performance bonuses; the postponement of the FINEST project (an ANS cooperation initiative with EANS) meaning that the planned expansion of the Airspace management service (AMC) was not implemented; lower than planned external recruitment into the development function. Overall, FTEs and salary increases were below plan.

- Significantly lower than planned other operating costs (-10.1%), mainly due to lower than planned leasing costs paid to the airport operator Finavia. The airport operator Finavia owns some ANS assets and Fintraffic ANS pays for their use via leasing costs (included in Fintraffic ANS other operating costs). These leasing costs are considered as investment costs with the difference between planned and actual lease returned to the airspace users through the cost risk sharing mechanism.

- Significantly lower than planned depreciation (-34.1%), due to delays in several investments because of limited internal resources and constraints related to system suppliers. However, terminal asset depreciation costs are small (1.3% of Fintraffic ANS' actual real terminal costs) because most of the investments are made by airport operator Finavia, as highlighted above.

- Lower than planned cost of capital (-3.5%), due to smaller than planned net current assets.

### **TZ1.1.5. ASSESSMENT OF THE ACTUAL PERFORMANCE IN THE CHARGING ZONE REPORTED BY THE NSA**

The NSA of Finland provides the following overall assessment of the actual performance in 2025 at charging zone level:

"*Terminal cost-efficiency was met. The actual traffic actualised a bit smaller than planned but the actual costs were proportionally lower than the traffic.*"

### **TZ1.1.6. EXPLANATION OF THE DIFFERENCES BETWEEN ACTUAL AND DETERMINED COSTS AT CHARGING ZONE LEVEL REPORTED BY THE NSA**

The NSA provides the following explanation for the differences between actual and determined costs in the charging zone:

"*A major reason for lower actual terminal ANSP cost were leasing costs. Main part of the terminal assets are leased from the airport operator Finavia and their have delayed their investment plan. The second major reason is lower staff costs as in enroute actual cost base.*"

### **TZ1.1.7. RECOMMENDATIONS FORMULATED BY THE NSA TO THE ANSP (FINTRAFFIC ANS) TO RECTIFY THE SITUATION AND ACTIONS TAKEN BY THE ANSP**

The NSA 2025 monitoring report indicates the following recommendations formulated by the NSA:

"*The unspent investment costs are reimbursed to airspace users and the ANSP is bearing a significant part of the traffic risk.*"

Fintraffic ANS reports the implementation of the following actions:

"*The lower actual costs haven\'t impacted issues with capacity.*"

### **TZ1.1.8. NOTES**

#### **TZ1.1.8.1. NOTE 1**

#### **TZ1.1.8.2. NOTE 2**

