## **2.2.1.A. KPI #1**

### **Assessment of the achieved level of actual performance in the environment KPA**

Finland has implemented Free Route Airspace together with neighboring countries (NEFAB + DK-SE FAB) and the overflying traffic can select their preferred routing in the Finnish airspace.

The performance in 2025 was slightly above the target set in the NOP, resulting to actual value of 3,71 %. This has been caused mainly because of the airspace closures due to the Russia\'s war against Ukraine.

The airspace closures have shifted the traffic flows from Russia to Kaliningrad, and these flights have to use the narrow international airspace corridor between Finland and Estonia, and can not use the direct routing that has been used before the war.

### **Has the ANSP implemented any major operational or structural changes (incl. any new fixed assets put into operation) during the calendar year impacting performance in this key performance area? Please outline the relevant changes and their estimated impact**

### **Progress on the implementation of the measures committed to in the ERNIP**

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

The airspace closures have shifted the traffic flows from Russia to Kaliningrad, and these flights have to use the narrow international airspace corridor between Finland and Estonia, and can not use the direct routing that has been used before the war.

### **Recommendations to the ANSP to rectify the situation**

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

