## **ER1.3.  SECTION 3 -- REGULATORY RESULT**

### **ER1.3.1. FINTRAFFIC ANS NET GAIN/LOSS ON ACTIVITY IN THE FINLAND EN ROUTE CHARGING ZONE IN 2025**

Fintraffic ANS reported a net loss of -0.2 M€, as a combination of a gain of +1.7 M€ arising from the cost sharing mechanism, with a loss of -1.9 M€ arising from the traffic risk sharing mechanism.

### **ER1.3.2. FINTRAFFIC ANS OVERALL REGULATORY RESULT (RR) FOR THE EN ROUTE ACTIVITY**

Ex-post, the overall RR, taking into account the net loss from the en route activity mentioned above (-0.2 M€) and the actual RoE (+1.4 M€), amounts to +1.2 M€ (3.0% of the en route revenues). The resulting ex-post rate of return on equity is 4.1%, which is lower than the 4.8% planned in the PP (see also Note 1 below).

### **ER1.3.3. NOTES** 

#### **ER1.3.3.1. NOTE 1**

The ex-post RR does not take into account the application of a lower unit rate in 2025 as per Art. 29.6 (the loss in revenues corresponds to -1.9 M€ for 2025).

#### **ER1.3.3.2. NOTE 2**

# **TZ1. TERMINAL CHARGING ZONE - FINLAND**

