## **ER1.1. SECTION 1 -- UNIT COST**

### **ER1.1.1. AUC VS. DUC**

In 2025, the en route AUC was +14.9% (or +8.97 €2022) higher than the planned DUC. This results from the combination of significantly lower than planned TSUs (-16.9%) and lower than planned en route costs in real terms (-4.5%, or -2.2 M€2022).

### **ER1.1.2. EN ROUTE SERVICE UNITS**

The difference between actual and planned TSUs (-16.9%) falls outside the ±10% threshold foreseen in the traffic risk sharing mechanism. The resulting loss of en route revenues is therefore shared between the ANSP and the airspace users (see the main ANSP regulatory result).

### **ER1.1.3. EN ROUTE COSTS BY ENTITY**

Actual real en route costs are -4.5% (-2.2 M€2022) lower than planned. This is the result of lower costs for the main ANSP, Fintraffic ANS (-5.4%, or -2.2 M€2022) and the NSA/EUROCONTROL (-0.9%) and higher costs for the MET service provider (+1.6%, or +0.1 M€2022).

### **ER1.1.4. EN ROUTE COSTS FOR THE MAIN ANSP (FINTRAFFIC ANS) AT CHARGING ZONE LEVEL**

Based on the additional information to the en route reporting tables, the significantly lower than planned en route costs in real terms for Fintraffic ANS in 2025 (-5.4%, or -2.2 M€2022) result from:

- Significantly lower than planned staff costs (-6.4%), due to multiple factors, including: lower than planned personnel fund contributions; reduced performance bonuses; the postponement of the FINEST project (an ANS cooperation initiative with EANS) meaning that the planned expansion of the Airspace management service (AMC) was not implemented; lower than planned external recruitment into the development function. Overall, FTEs and salary increases were below plan.

- Lower than planned other operating costs (-3.4%), mainly due to lower than planned leasing costs paid to the airport operator Finavia. The airport operator Finavia owns some ANS assets and Fintraffic ANS pays for their use via leasing costs (included in Fintraffic ANS other operating costs). These leasing costs are considered as investment costs with the difference between planned and actual leasing costs returned to the airspace users through the cost risk sharing mechanism.

- Significantly lower than planned depreciation (-9.3%), due to delays in several investments because of limited internal resources and constraints related to system suppliers.

- Higher than planned cost of capital (+4.4%), mainly due to higher fixed assets under construction driven by ATM systems renewal.

- Slightly higher than planned deduction for VFR exempted flights (+0.3%).

### **ER1.1.5. ASSESSMENT OF THE ACTUAL PERFORMANCE IN THE CHARGING ZONE REPORTED BY THE NSA**

The NSA of Finland provides the following overall assessment of the actual performance in 2025 at charging zone level:

"*IFR movements did not decrease in the same proportion as SUs (-16,9 % vs. -6,8 %), meaning that the ANSP\'s cost reduction is more closely aligned with the level of traffic. The traffic situation was very challenging, as major Asian airlines that previously flew through Finnish airspace rerouted their flights south of Finland. At the same time, traffic from Russia to Kaliningrad, using the narrow international corridor between Finland and Estonia, remained relatively busy.*"

### **ER1.1.6. EXPLANATION OF THE DIFFERENCES BETWEEN ACTUAL AND DETERMINED COSTS AT CHARGING ZONE LEVEL REPORTED BY THE NSA**

The NSA provides the following explanation for the differences between actual and determined costs in the charging zone:

"*Two major reasons for lower actual ANSP costs were lower investment costs (delayed investments, smaller leasing costs) and lower costs for technical department. In addition, staff costs were generally lower than planned.*"

### **ER1.1.7. RECOMMENDATIONS FORMULATED BY THE NSA TO THE ANSP (FINTRAFFIC ANS) TO RECTIFY THE SITUATION AND ACTIONS TAKEN BY THE ANSP**

The NSA 2025 monitoring report indicates the following recommendations formulated by the NSA:

The "*NSA is monitoring the cost evolution and its impact on service level.*"

Fintraffic ANS reports the implementation of the following actions:

"*The lower actual costs haven\'t impacted issues with capacity.*"

### **ER1.1.8. NOTES**

#### **ER1.1.8.1. NOTE 1**

#### **ER1.1.8.2. NOTE 2**

