## **ER1.3.  SECTION 3 -- REGULATORY RESULT**

### **ER1.3.1. LGS NET GAIN/LOSS ON ACTIVITY IN THE LATVIA EN ROUTE CHARGING ZONE IN 2025**

LGS reported a net gain of +1.3 M€, as a combination of a gain of +1.5 M€ arising from the cost sharing mechanism, with a loss of -0.5 M€ arising from the traffic risk sharing mechanism and a gain of +0.3 M€ relating to financial incentives.

### **ER1.3.2. LGS OVERALL REGULATORY RESULT (RR) FOR THE EN ROUTE ACTIVITY**

Ex-post, the overall RR, taking into account the net gain from the en route activity mentioned above (+1.3 M€) and the actual RoE (+1.1 M€), amounts to +2.4 M€ (9.7% of the en route revenues). The resulting ex-post rate of return on equity is 17.7%, which is higher than the 8.3% planned in the PP (see also Note 1 below).

### **ER1.3.3. NOTES** 

#### **ER1.3.3.1. NOTE 1**

The ex-post RR does not take into account the application of a lower unit rate in 2025 as per Art. 29.6 (the loss in revenues corresponds to -5.8 M€ for 2025).

#### **ER1.3.3.2. NOTE 2**
