## **2.2.1.A. KPI #1**

### **Assessment of the achieved level of actual performance in the environment KPA**

The level of actual performance in the environment KPA is met.

### **Has the ANSP implemented any major operational or structural changes (incl. any new fixed assets put into operation) during the calendar year impacting performance in this key performance area? Please outline the relevant changes and their estimated impact**

Continuos monitoring, revision and updates of PBN procedures in line with airspace users requirements.

### **Progress on the implementation of the measures committed to in the ERNIP**

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

N/A

### **Recommendations to the ANSP to rectify the situation**

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

