## SAF1.4. Rate of separation minima infringements (SMIs) (PI#2)

At State level, Latvia reported 2 separation minima infringements (SMI) in their airspace\
during 2025. The rate of separation minima infringements was lower than the Union-wide average (3.15 vs 7.10). At ANSP level, Latvia reported 1 SMI with ATS/CNS contribution. The rate of separation minima infringements at ANSP level was lower than the Union-wide average (1.57 vs 6.0).

When comparing to 2024, the rate of separation minima infringements has increased at State level (3.15 vs 3.03) and decreased at ANSP level (1.57 vs 3.03).

According to the monitoring report, all cases have been thoroughly investigated, and corrective actions have been implemented to address identified issues and prevent their recurrence, thereby ensuring continuous improvement in safety and operational efficiency. During the investigation process, recommendations were developed, and the status of their implementation is continuously monitored. Furthermore, investigation reports are distributed to the relevant organizational units to ensure that all personnel are informed. Regarding corrective actions, in one case the staff member involved was assigned to additional simulator training sessions in order to practice handling similar situations. In addition, the relevant safety occurrences have been incorporated as case studies into future air traffic controller training programmes. The case study included a detailed analysis of contributing factors, relevant procedures, and best practices aimed at preventing the recurrence of similar events. During the session, a discussion was held together with a supervisor to strengthen situational awareness, decision-making skills, and compliance with standard operating procedures. In the second case, the occurrence took place in High Seas and involved military aircraft.

The NSA notes in the monitoring report that the Civil Aviation Agency receives, and reviews safety occurrence reports upon receipt and follows-up by monitoring the implementation of improvements and corrective measures. Latvia has also established reactive and proactive initiatives when occurrences take place, analysing the incidents, implementing corrective actions and targeted follow-up training. The proactive approach includes conducting case studies, additional briefings and training sessions. The goal of these initiatives is to increase situational awareness and identify potential risks before they occur.

