## **2.3.1.A. KPI #1**

### **Identification and analysis of the reasons and circumstances resulting in the achieved level of actual performance of the en-route ATFM delay per flight KPI**

BULATSA deals with the increasing complexity and the high traffic levels using flexible sectorization and sector saturation avoidance procedures, optimized and flexible human resources management in terms of existing ATCOs and recruitment of the new ones, and strict ATFM adverse weather procedures.

### **Description of the adjustments to the capacity plan included in adopted performance plan**

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

### **Recommendations to the ANSP to rectify the situation**

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

