## **2.3.3 ATCO Planning 1**

### **Additional comments**

### **Additional comments**

Please note that part of the additional ATCOs in OPS that started working in the OPS room in 2025 are related to the return of ATCOs being on maternity leave the previous year. They practically increased the number of FTEs actively involved in service provision in OPS room.

### **Description of the training process, including details on the effective failure rate and the process used to allocate newly qualified ATCOs between ACC, APP and TWR positions**

The overall success rate for the initial trainings and unit trainings is above 80%. More than 97% of the newly recruited applicants for student ATCOs are allocated to initial training for ACS rating (basic and ACS rating training), based on the targets set for RP4, while the rest applicants are directly allocated to initial training for ADC rating (basic and ADC rating training).

Remark : BULATSA manages one of the most complex area control airspace in Europe and integrates significant part of the traffic to the 3 Istanbul airports.

