## PRB1.6. Cost-efficiency {#prb1.6.-cost-efficiency .Heading-2-ER}

- The en route 2025 actual unit cost of Bulgaria was 26.46€2022, -2.9% lower than the determined unit cost (27.25€2022). Bulgaria does not have a terminal charging zone.

- The en route 2025 actual service units (5.5M) were +3.8% higher than the determined service units (5.3M).

- The en route 2025 actual total costs were +1.1M€2022 (+0.8%) higher than determined. This is mainly due to higher other operating costs (+2.2M€2022, or +19.1%) of BULATSA, partially compensated by lower staff costs than planned (-1.0M€2022, or -1.1%). The NSA explained that the increase in other operating costs is attributable to the increase of the costs of external services, health and life insurance, and software maintenance and development.

- BULATSA costs of investments were 23.8M€2022 in 2025, +1.8% more than determined (23.4M€2022). According to the NSA, this increase is due to the development of the investment cycle.

- The en route actual unit cost incurred by users in 2025 was 29.87€ (-1.6% below the 2025 DUC). The difference between the AUCU and the DUC is mainly driven by the traffic risk sharing adjustment.

- The en route regulatory result for BULATSA amounted to +16.2M€, or 10.4% of the 2025 revenue. This may indicate that the airspace users are charged for costs which have not materialised in 2025.

