## **ER1.1. SECTION 1 -- UNIT COST**

### **ER1.1.1. AUC VS. DUC**

In 2025, the en route AUC was -12.6% (or -3.84 €2022) lower than the planned DUC. This results from the combination of significantly higher than planned TSUs (+12.2%) and lower than planned en route costs in real terms (-1.9%, or -1.1 M€2022).

### **ER1.1.2. EN ROUTE SERVICE UNITS**

The difference between actual and planned TSUs (+12.2%) falls outside the ±10% threshold foreseen in the traffic risk sharing mechanism. The resulting gain of additional en route revenues is therefore shared between the ANSP and the airspace users (see the main ANSP regulatory result).

### **ER1.1.3. EN ROUTE COSTS BY ENTITY**

Actual real en route costs are -1.9% (-1.1 M€2022) lower than planned. This is the result of lower costs for the MET service provider (-11.4%, or -0.5 M€2022), the main ANSP, DCAC Cyprus (-0.9%, or -0.4 M€2022) and the NSA/EUROCONTROL (-2.5%, or -0.3 M€2022).

### **ER1.1.4. EN ROUTE COSTS FOR THE MAIN ANSP (DCAC CYPRUS) AT CHARGING ZONE LEVEL**

Based on the additional information to the en route reporting tables, the slightly lower than planned en route costs in real terms for DCAC Cyprus in 2025 (-0.9%, or -0.4 M€2022) result from:

- Higher than planned staff costs (+1.6%), mainly reflecting the impact of lower than planned inflation index (-1.3 p.p.) since costs in nominal terms were in line with the plan (+0.3%).

- Lower than planned other operating costs (-2.5%), mainly due to the postponement of some planned expenditures related to CNS and security of the new ACC.

- Significantly lower than planned depreciation (-8.4%), mainly due to delays to the implementation of planned projects (namely: *secondary Radar in Horteri; AEROMED WEB Upgrade; DME-DME infrastructure*).

- Higher than planned cost of capital (+2.6%), mainly due to prepayments for investments under construction (namely: *new ATM system -- phase 4; new radar in Horteri; new primary and secondary Kionia radar and new Larnaca radar*.)

### **ER1.1.5. ASSESSMENT OF THE ACTUAL PERFORMANCE IN THE CHARGING ZONE REPORTED BY THE NSA**

The NSA of Cyprus provides the following overall assessment of the actual performance in 2025 at charging zone level:

"*The actual costs are lower than the determined ones by 2.7% whilst the en route service units are higher than the forecast by 12.2%. The combination of the two parameters results to an actual unit cost (in real terms) which is lower than the determined unit cost (by 12.8%).*"

*\[It should be noted that Cyprus submitted revised Monitoring Report 2025 with the updated en route costs, but not all corresponding figures were updated in the analysis. As a result, some of the amounts indicated by the NSA cited above differ slightly from the amounts reported in the respective data tables in the same NSA Monitoring Report and in the submission of en route reporting tables (both of which are aligned).\]*

### **ER1.1.6. EXPLANATION OF THE DIFFERENCES BETWEEN ACTUAL AND DETERMINED COSTS AT CHARGING ZONE LEVEL REPORTED BY THE NSA**

The NSA provides the following explanation for the differences between actual and determined costs in the charging zone:

"*Actual overall ANS costs are lower (by 2.9%) than the determined costs foreseen in the RP4 PP. This is broken down as follows: Main ANSP -1.9%; MET -12%; State/NSA -3.3%.*

*The main reasons for these deviations are:*

*- Delays to or partial implementation of the recruitment plans of the ANSPs.*

*- Delays to or partial implementation of ANSPs' organisational plans (leading to lower operating costs than those foreseen).*

*- Delays to or partial implementation of certain investments (leading to lower depreciation costs and cost of capital).*"

*\[It should be noted that Cyprus submitted revised Monitoring Report 2025 with the updated en route costs, but not all corresponding figures were updated in the analysis. As a result, some of the amounts indicated by the NSA cited above differ slightly from the amounts reported in the respective data tables in the same NSA Monitoring Report and in the submission of en route reporting tables (both of which are aligned).\]*

### **ER1.1.7. RECOMMENDATIONS FORMULATED BY THE NSA TO THE ANSP (DCAC CYPRUS) TO RECTIFY THE SITUATION AND ACTIONS TAKEN BY THE ANSP**

The NSA 2025 monitoring report indicates the following recommendations formulated by the NSA:

"*Strong recommendations were made to the ANSPs to implement more consistently their plans regarding the investments.*"

DCAC Cyprus reports the implementation of the following actions:

"*The ANSPs\' Annual Plans will be modified so as to catch-up with the delayed investments.*"

### **ER1.1.8. NOTES**

#### **ER1.1.8.1. NOTE 1**

#### **ER1.1.8.2. NOTE 2**

