## **2.2.1.A. KPI #1**

### **Assessment of the achieved level of actual performance in the environment KPA**

The actual performance was almost in line with the PP targets.

### **Has the ANSP implemented any major operational or structural changes (incl. any new fixed assets put into operation) during the calendar year impacting performance in this key performance area? Please outline the relevant changes and their estimated impact**

The ANSP continues to work closely with the Network Manager so as to implement airspace re-structuring projects and to improve further its performance with respect to the enviromental.

FRA implementation in Nicosia FIR continues as planned.

### **Progress on the implementation of the measures committed to in the ERNIP**

The published flight efficiency plans (ERNIP) continue to be implemented in cooperation with the Network Manager. FRA implementation in Nicosia FIR continues as planned.

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

The slight deviation from the optimum routing options is not attributed to the ANSP but to the inability of Cyprus to optimise traffic flows in the entire of Nicosia FIR (e.g. Turkey is not cooperating for additional airspace improvements).

It should be noted that most neigbouring ANSPs do not need to comply with EU law and EU instruments such as the ERNIP.

### **Recommendations to the ANSP to rectify the situation**

The ANSP should continue to work closely with the Network Manager to implement airspace re-structuring projects and to improve, to the maximums extent possible, its enviromental efficiency.

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

The ANSP is not able, on its own, to optimise furhter the airspace structures in the entire Nicosia FIR, and particularly the northern part. It remains dependent on geopolitical develpoments and the NM\'s initiatives for performing further optimisations.

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

