## SAF1.1. Effectiveness of Safety Management (EoSM) (KPI#1)

In 2025, CYATS achieved the planned maturity levels set out in its performance plan for four out of five components. CYATS missed the planned level in the Safety Risk Management component of the EoSM.

As described in the monitoring report, the actual performance achieved in most areas was equal to the target set. Further improvements are needed in risk management aspects. The ANSP's actions aimed at improving its safety performance include:

-   Nicosia ACC Safety Bulletins to personnel January -December 2025.

-   Central SMS Alerts to the Nicosia ACC, data dissemination and facilitation to the dedicated safety committee meetings.

-   NicACC safety committee meetings and corrective measures planning on personnel awareness.

-   NicACC dedicated meeting with the NACC Supervisors.

-   NicACC communication to all personnel on concertation and discipline.

-   2025 NicACC Theoretical and Practical Refresher Training. In the theoretical part all lessons learned from SMI analysis were presented and disseminated to NACC personnel. Furthermore, actions included the incorporation of human factor stressors and enhanced human error analysis within investigation reports.

In terms of underlying causes or circumstances leading to levels not being achieved, the monitoring report states that the staffing levels in the safety management unit have been degraded after the unforeseen departure of three officers which were hired a few years ago. A recruitment process to replace them has already been initiated by the ANSP.

According to the monitoring report, the ANSP has mitigated this issue by assigning part-time SMS duties to operational staff.

In terms of measures that the NSA intends to undertake to remedy the situation, the monitoring report states that the NSA has highlighted its concerns regarding the staffing of the ANSP\'s SMS Unit in the context of an ad hoc audit conducted in April 2025 and has asked the ANSP to expedite its corrective actions. Nevertheless, it should be noted that the ANSP remains a public sector entity and, in this respect, it does not directly manage the recruitment process (this is delegated, by the Constitution of the Republic to an independent government body). In general, the NSA is closely monitoring the effectiveness of the recommendations/actions decided via ad-hoc inspections and follow-up audits. For instance, a follow-up audit was conducted on February 2026 to verify the implementation of the ANSP's corrective actions.

