## SAF1.4. Rate of separation minima infringements (SMIs) (PI#2)

At State level, Cyprus reported 10 separation minima infringements (SMI) in their airspace during 2025. The rate of separation minima infringements was below Union-wide average (5.52 vs 7.10). At ANSP level, Cyprus reported 9 SMIs with ATS/CNS contribution. The rate of separation minima infringements at ANSP level was below the Union-wide average (4.97 vs 6.0).

When comparing to 2024, the rate of separation minima infringements has increased at both State level (5.52 vs 4.4) and at ANSP level (4.97 vs 4.41).

In terms of initiatives implemented or planned, the monitoring report states that the ANSP has actions aimed at managing SMI events and reversing the previously identified negative trend. These actions included the following:

-   Nicosia ACC Safety Bulletins to personnel January -December 2025.

-   Central SMS Alerts to the Nicosia ACC, data dissemination and facilitation to the dedicated NACC safety committee meetings.

-   NicACC safety committee meetings and corrective measures planning on personnel awareness

-   NicACC dedicated meeting with the NACC Supervisors.

-   NicACC communication to all personnel on concertation and discipline.

-   2025 NACC Theoretical and Practical Refresher Training. In the theoretical part all lessons learned from SMI analysis were presented and disseminated to NACC personnel.

Furthermore, actions included the incorporation of human factor stressors and enhanced human error analysis within investigation reports.

The NSA notes in the monitoring report that it intends to monitor the effectiveness of the recommendations/actions decided via ad-hoc inspections and follow-up audits. For instance, a follow-up audit was conducted in February 2026 to verify the implementation of the ANSP's corrective actions.

