## **TZ1.1. SECTION 1 -- UNIT COST**

### **TZ1.1.1. AUC VS. DUC**

In 2025, the terminal AUC was -2.4% (or -30.98 DKK2022, -4.17 €2022) lower than the planned DUC. This results from the combination of lower than planned terminal costs in real terms (-4.4%, or -10.0 MDKK2022, -1.3 M€2022) and lower than planned TNSUs (-2.1%).

### **TZ1.1.2. TERMINAL SERVICE UNITS**

The difference between actual and planned TNSUs (-2.1%) falls outside the ±2% dead-band, but does not exceed the ±10% threshold foreseen in the traffic risk sharing mechanism. The resulting loss of terminal revenues is therefore shared between the ANSP and the airspace users (see the main ANSP regulatory result).

### **TZ1.1.3. TERMINAL COSTS BY ENTITY**

Actual real terminal costs are -4.4% (-1.3 M€2022) lower than planned. This is the result of lower costs for the main ANSP, NAVIAIR (-4.5%, or -1.4 M€2022) and higher costs for the MET service provider (+6.7%).

### **TZ1.1.4. TERMINAL COSTS FOR THE MAIN ANSP (NAVIAIR) AT CHARGING ZONE LEVEL**

Based on the additional information to the terminal reporting tables, the lower than planned terminal costs in real terms for NAVIAIR in 2025 (-4.5%, or -1.4 M€2022) result from:

- Slightly lower than planned staff costs (-1.1%).

- Significantly lower than planned other operating costs (-20.2%), mainly due to lower or postponed expenditures in various cost items, with the exception of training costs which were on plan.

- Significantly higher than planned depreciation (+11.2%), mainly due to a high activity level compared to plan.

- Slightly lower than planned cost of capital (-1.1%), mainly due to a lower bank loan interest rate than expected.

### **TZ1.1.5. ASSESSMENT OF THE ACTUAL PERFORMANCE IN THE CHARGING ZONE REPORTED BY THE NSA**

The NSA of Denmark provides the following overall assessment of the actual performance in 2025 at charging zone level:

"*Lower OPEX (not training) means that real unit costs are 2.4% below DUC despite traffic also being lower than planned.*"

### **TZ1.1.6. EXPLANATION OF THE DIFFERENCES BETWEEN ACTUAL AND DETERMINED COSTS AT CHARGING ZONE LEVEL REPORTED BY THE NSA**

The NSA provides the following explanation for the differences between actual and determined costs in the charging zone:

"*The difference is due to lower OPEX except for training and lower interest. However, the difference is relatively small and does not need to be rectified.*"

### **TZ1.1.7. RECOMMENDATIONS FORMULATED BY THE NSA TO THE ANSP (NAVIAIR) TO RECTIFY THE SITUATION AND ACTIONS TAKEN BY THE ANSP**

No information was provided in the NSA 2025 Monitoring Report.

### **TZ1.1.8. NOTES**

#### **TZ1.1.8.1. NOTE 1**

#### **TZ1.1.8.2. NOTE 2**

