## **2.3.1.A. KPI #1**

### **Identification and analysis of the reasons and circumstances resulting in the achieved level of actual performance of the en-route ATFM delay per flight KPI**

The average delay was 0.11 minutes per flight in 2025, below the reference value set in the RP4-planning (0.17).

52% of the delays were due to the reason ATC Staffing, 29% due to ATC Capacity, 13% due to the reason Weather and 6% due to the reason Airspace Management.

Post summer 57% of the total yearly delay can be attributed to September 2025 were there were ATFM-regulations mainly due to ATC Staffing and ATC Capacity. This is the main contributing factor relating to not reaching the target.

### **Description of the adjustments to the capacity plan included in adopted performance plan**

None

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

The underperformance were minimal. The NSA agrees with Naviair on the reasons behind.

### **Recommendations to the ANSP to rectify the situation**

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

