## **2.2.1.A. KPI #1**

### **Assessment of the achieved level of actual performance in the environment KPA**

Naviair has consistently recorded a low value and is in 2025 among the lowest-scoring ANSPs.

The failure to meet the target in the reporting year should be assessed within a broader operational context.

Flight inefficiency increased accross the European ATM network, as documented in the Perfomance Review Report 2025.

### **Has the ANSP implemented any major operational or structural changes (incl. any new fixed assets put into operation) during the calendar year impacting performance in this key performance area? Please outline the relevant changes and their estimated impact**

F35 military training areas were implemented on 18th of May

### **Progress on the implementation of the measures committed to in the ERNIP**

EKDK FIR sector split

VOR stations closure Denmark - Phase 2

Areas over the High Seas

New TRAs

are all implemented

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

### **Recommendations to the ANSP to rectify the situation**

The underperformance was minimal. Underperformance is seen as linked to the fact that new military training areas were implemented and the unstable situation across the European network.

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

The PRB in their report "Performance Review Body Advice on the Union-wide targets for RP4 Annex II -- Impact of Russia\'s war of aggression on horizontal flight efficiency" together with Eurocontrol has established that there is an impact of Russia's war og agression on the KEA value of 0,12 pp.

The overall increase in value can be attributed to the structural change in flows with impact also from staffing and increased military airspace closures due to training

