## SAF1.1. Effectiveness of Safety Management (EoSM) (KPI#1)

In 2025, Naviair did not achieve the planned levels set out in its performance plan for three out of five components of the EoSM. The components where Naviair missed the planned levels were Safety Risk Management, Safety Promotion and Safety Culture.

Denmark assesses the achieved level of actual performance in the monitoring report as follows: Naviair has assessed the maturity level between Level A and Level B across the five Safety Components. The assessment is primarily influenced by the fact that the difference between the requirements at level A and level B is quite large and that Naviair does not currently have all the formalised processes in place.

As described in the monitoring report, Naviair has initiated a project at corporate level to ensure a unified approach across all departments to achieve the safety performance targets by 2029. Furthermore, Naviair has established a plan to address current performance gaps in Safety Culture, Safety Risk Management, and Safety Promotion. The plan includes responsibilities for developing and executing detailed plans, to meet annual sub-goals and the final targets for 2029.

In terms of underlying causes or circumstances leading to levels not being achieved, the monitoring report states that the result is primarily due to the fact that the difference between the requirements at level A and level B is quite large and that Naviair does not currently have all the formalised processes in place.

Furthermore, the monitoring report states that the NSA will monitor and follow up on Naviair's plan for improving the SAF performance during RP4.

