## **ER1.1. SECTION 1 -- UNIT COST**

### **ER1.1.1. AUC VS. DUC**

In 2025, the en route AUC was +7.4% (or +38.69 DKK2022, +5.20 €2022) higher than the planned DUC. This results from the combination of significantly lower than planned TSUs (-5.0%) and higher than planned en route costs in real terms (+2.0%, or +17.1 MDKK2022, +2.3 M€2022).

### **ER1.1.2. EN ROUTE SERVICE UNITS**

The difference between actual and planned TSUs (-5.0%) falls outside the ±2% dead-band, but does not exceed the ±10% threshold foreseen in the traffic risk sharing mechanism. The resulting loss of en route revenues is therefore shared between the ANSP and the airspace users (see the main ANSP regulatory result).

### **ER1.1.3. EN ROUTE COSTS BY ENTITY**

Actual real en route costs are +2.0% (+2.3 M€2022) higher than planned. This is the result of higher costs for the main ANSP, NAVIAIR (+1.8%, or +1.8 M€2022) and the NSA/EUROCONTROL (+4.8%, or +0.5 M€2022) and lower costs for the MET service provider (-0.2%).

### **ER1.1.4. EN ROUTE COSTS FOR THE MAIN ANSP (NAVIAIR) AT CHARGING ZONE LEVEL**

Based on the additional information to the en route reporting tables, the higher than planned en route costs in real terms for NAVIAIR in 2025 (+1.8%, or +1.8 M€2022) result from:

- Higher than planned staff costs (+4.1%), mainly due to the increased use of extra shifts attributed to the *"resource situation*".

- Significantly lower than planned other operating costs (-5.8%), mainly due to lower or postponed expenditures in various cost items while the budget for training is considered on track.

- Significantly higher than planned depreciation (+7.3%), mainly due to a high activity level compared to plan.

- Significantly lower than planned cost of capital (-5.1%), mainly due to a lower bank loan interest rate than expected.

- Slightly higher than planned deduction for VFR exempted flights (+0.1%).

### **ER1.1.5. ASSESSMENT OF THE ACTUAL PERFORMANCE IN THE CHARGING ZONE REPORTED BY THE NSA**

The NSA of Denmark provides the following overall assessment of the actual performance in 2025 at charging zone level:

"*Actual real en route costs are almost in line with determined costs (+2%). However real unit costs are 7,4% above DUC. This is due to actual service units being 5% below forecast.*"

### **ER1.1.6. EXPLANATION OF THE DIFFERENCES BETWEEN ACTUAL AND DETERMINED COSTS AT CHARGING ZONE LEVEL REPORTED BY THE NSA**

The NSA provides the following explanation for the differences between actual and determined costs in the charging zone:

"*Actual costs are not significantly above determined costs.*"

### **ER1.1.7. RECOMMENDATIONS FORMULATED BY THE NSA TO THE ANSP (NAVIAIR) TO RECTIFY THE SITUATION AND ACTIONS TAKEN BY THE ANSP**

The NSA 2025 monitoring report indicates that no recommendations were proposed by the NSA.

### **ER1.1.8. NOTES**

#### **ER1.1.8.1. NOTE 1**

#### **ER1.1.8.2. NOTE 2**

