## PRB1.6. Cost-efficiency {#prb1.6.-cost-efficiency .Heading-2-ER}

- The en route 2025 actual unit cost of Denmark was 75.69€2022, +7.4% higher than the determined unit cost (70.49€2022). The terminal 2025 actual unit cost was 170.86€2022, -2.4% lower than the determined unit cost (175.03€2022).

- The en route 2025 actual service units (1.56M) were -5.0% lower than the determined service units (1.64M).

- The en route 2025 actual total costs were +2.3M€2022 (+2.0%) higher than determined. This is mainly due to higher staff costs (+2.5M€2022, or +4.1%) for NAVIAIR, partially compensated by lower other operating costs than planned (-1.2M€2022, or -5.8%). The NSA explained that the increase in staff costs is due to the higher use of extra shifts due to the staffing situation.

- NAVIAIR spent 19.3M€2022 in 2025 related to costs of investments for both en route and terminal charging zones, +3.6% more than determined (18.6M€2022). According to the NSA, this increase is due to the higher activity level than planned.

- The en route actual unit cost incurred by users in 2025 was 75.67€ (+2.6% above the 2025 DUC), while the terminal actual unit cost incurred by users was 182.85€ (-1.0% below the 2025 DUC). The difference between the AUCU and the DUC for the en route charging zone is mainly driven by the traffic risk sharing adjustment, while for the terminal charging zone it is mainly driven by financial incentives.

