## PRB1.5. Capacity {#prb1.5.-capacity .Heading-2-ER}

- Denmark registered 0.11 minutes of average en route ATFM delay per flight during 2025, which remained 0.11 after the post-ops adjustment process, thus not achieving the local target value of 0.10. Delays in Denmark increased by 0.06 minutes per flight year-on-year.

- Delays were highest in September, mostly driven by ATC staffing.

- The share of delayed flights with delays longer than 15 minutes in Denmark decreased by -14 percentage points compared to 2024.

- The number of ATCOs in OPS was 83 being below the 2025 plan in Copenhagen ACC by -4 FTE.

- The yearly total of sector opening hours in Copenhagen ACC was 49,777, showing a 10% increase compared to 2024.

- Copenhagen ACC registered 10.35 IFR movements per sector opening hour in 2025, -9% below the level recorded in 2024.

- Denmark registered an average airport arrival ATFM delay of 0.55 minutes per flight in 2025, thus not achieving the local target of 0.2 minutes. Compared to 2024, average arrival ATFM delays in Denmark were 0.05 minutes per flight higher in 2025.

- The main drivers of delays were ATC staffing, accounting for 0.23 of the total delays, and other non-ATC causes, responsible for 0.16.

