## **2.3.1.B. KPI #2**

### **Identification and analysis of the reasons and circumstances resulting in the achieved level of actual performance of the arrival ATFM delay per flight KPI**

The average delay was 0.55 minutes per flight in 2025, which on the same level as 2024-value of 0,50.

42% of the delays were due to the reason ATC Staffing, 26% due to the reason Aerodrome capacity, 25% due to the reason Weather and 4% due to ATC Capacity.

Naviairs notes that there are currently an intensive focus on increasing staff-levels for Copenhagen Airports and the rest of Naviairs operational units. ATC staffing isolated (0.23) is on target level (0.20 in 2025), while more than 50% of delays can be attributed to factors related to Aerodrome or Weather. This trend with increasing other contributing factors is being monitored going forward.

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

Most of the delay is attributed to factors outside the ANSPs sphere of influence. Besides that ATC staffing delay must be reduced.

### **Recommendations to the ANSP to rectify the situation**

Continued intense focus on increasing staffing levels in Naviair.

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

The NSA is aware that recruitment and training are ongoing, with associated risks related to staffing levels and service delivery.

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

