```{r some-params}
# to avoid errors
cz=c("1", "enroute")
  
# define cz
ez <- as.numeric(cz[[1]])
cztype <- cz[[2]]
```

[Cost-efficiency - {{< var doc.country >}}]{class="fakeh1"}

## PRB monitoring

```{r concl-cef-duc}
cef_conc <- read_mytable("PRB_findings.xlsx", "cost-efficiency", "Table_Findings_CEFF") %>%
  filter(Year_Report == params$year_report, State == params$country) %>%
  select(Conclusion) %>% toString() %>% paste0(., "@")

cef_conc1 <- cef_conc %>% str_replace_all(c('", ' = '\n\n', '\"' = '', '\n\n\n' = '\n\n')) %>% str_replace(fixed('c('), '') %>%  str_replace(fixed(')@'), '\n')
```

`r cef_conc1`


::: {#cef-cost-muac}
## Total costs

:::: {layout="[ 50, 50 ]"}
::::: {#chart-cef-cost-muac}
```{r chart-cef-cost-muac, options = (cz=c("1", "enroute"))}
#| file: R/chart_level2_cef_cost.R
#| out.width: "100%"
```
:::::

::::: {#table-costs-muac}
```{r table-cef-cost-muac, options = (cz=c("1", "enroute"))}
#| file: R/table_level2_cef_cost.R
#| out.width: "100%"
```
:::::
::::

:::
