## **2.3.1.B. KPI #2**

### **Identification and analysis of the reasons and circumstances resulting in the achieved level of actual performance of the arrival ATFM delay per flight KPI**

Better understanding of the ATFM arrival delay calculation principle (regulations vs capacity). Capacity reduction instead of regulation of default capacity. Default capacity is regularly reduced from 20 to 18 arrivals per hour, due to staffing issues (third position of the arrival manager temporarily not manned). No more needs for regulations as long as traffic remains below 18 arrivals. Main delay cause was weather (0,13 mins). Two incidents, closure of the runway due to a hole in June and an aircraft blocking the runway with retracted train in November, explain the remaining 0,02 mins of delay.

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

N/A

### **Recommendations to the ANSP to rectify the situation**

N/A

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

N/A

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

Technical issues leading to imposed regulations in 2023 and 2024 have been mitigated.

