## SAF1.1. Effectiveness of Safety Management (EoSM) (KPI#1)

In 2025, ANA LUX achieved the planned maturity levels set out in its performance plan for three out of five components of the EoSM. The components where ANA LUX missed the planned levels were Safety Policy and Objectives and Safety Risk Management. ANA LUX scored A for the Safety Policy and Objectives and Safety Risk Management and needs significant improvement for the EoSM in order to reach the targets by the end of RP4.

In terms of main measures put in place to achieve the safety performance targets, the report defines that there is a CAP plan in place for those areas where the performance was not in line with the target. For the others there is an RP4 development plan to reach the target.

As the planned levels were not achieved, Luxembourg explains in the monitoring report the reasons leading to this situation; Structurally over the last years, the safety department has put their efforts into solving (EU) 376/2014 related issues and findings, which were successful. This, however, meant that only minimal efforts were undertaken to get the SMS ready for RP4, which explains the poor start into RP4. Additionally, it was recognized that more staff is needed on this area. The recruitment had been anticipated, and this will be mitigated by Q3 2026.

In terms of remedial actions, the report states that the main issues that affected the results above were identified during an SMS audit performed by the NSA/NCA, where a corrective action plan to solve the identified non-conformities with (EU) 2017/373 will be required.

Further measures by NSA, according to the monitoring report, include oversight to ensure effective development of a corrective action plan with effective measures to achieve the overall targets.

