## **2.3.1.A. KPI #1**

### **Identification and analysis of the reasons and circumstances resulting in the achieved level of actual performance of the en-route ATFM delay per flight KPI**

The delay targets for RP4 have been deemed unrealistic and unachievable from the onset. The target was missed mainly due to the substantial increase in traffic, that is higher than the forecast on which the PP was based. It has to be noted that the KPI was reduced by approx. 15% compared to the preceding year.

### **Description of the adjustments to the capacity plan included in adopted performance plan**

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

The capacity planning of Austro Control was based on the forecasts that had been used for the performance planning in the preceding year. These forecasts have proven too low and the target was missed mainly due to an increased traffic demand that exceeded the forecasts substantially.

### **Recommendations to the ANSP to rectify the situation**

It is recommended to continue the ATCO recruitment initiative as well as the development of the new ATM system, which are both ongoign and are expected to contribute to capacity increases on the long term.

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

No measures beyond the above-mentioned initiatives are feasible on the short term.

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

n/a

