## **TZ1.3. SECTION 3 -- REGULATORY RESULT**

### **TZ1.3.1. AUSTRO CONTROL NET GAIN/LOSS ON ACTIVITY IN THE AUSTRIA TERMINAL CHARGING ZONE IN 2025**

Austro Control reported a net gain of +2.5 M€, as a combination of a gain of +3.0 M€ arising from the cost sharing mechanism, with a loss of -0.5 M€ arising from the traffic risk sharing mechanism. See also Note 1 below.

### **TZ1.3.2. AUSTRO CONTROL OVERALL REGULATORY RESULT (RR) ON ACTIVITY IN THE TERMINAL CHARGING ZONE** 

Ex-post, the overall RR, taking into account the net gain from the terminal activity mentioned above (+2.5 M€) and the actual RoE (+1.4 M€), amounts to +3.9 M€ (6.9% of the terminal revenues). The resulting ex-post rate of return on equity is 11.4%, which is higher than the 4.0% planned in the PP. See also Note 1 below.

### **TZ1.3.3. NOTES**

#### **TZ1.3.3.1. NOTE 1**

The analysis presented above excludes the costs of meteorological services provided by Austro Control since MET figures are disclosed separately in terminal reporting tables.

#### **TZ1.3.3.2. NOTE 2**
