## ERT1.1. En route ATFM delay per flight (KPI#1) {#ert1.1.-en-route-atfm-delay-per-flight-kpi1 .Heading-2-ER}

- Austria had 1 681k flights in 2025, up from 1 507k flights in 2024.

- Austro Control applied en route ATFM regulations resulting in 549k minutes of delay, a reduction from the 641k minutes in 2024.

- As part of the strategic traffic re-orientation programme (S25/NTDM) operated by the Network Manager, there were 27k minutes of en route ATFM delay reattributed **to Austro Control**; 12k minutes of delay originating in Vienna ACC were re-attributed **to other ANSPs.**

- Under the auspices of the Route Network (RN) Scenarios during Capacity & Weather Based Operations between June and September 2025, an additional 13k minutes of en route ATFM delay were re-attributed **to Austro Control** -- with \<1k minutes of delay, originating in Vienna ACC, being re-attributed **to other ANSPs**.

- A further 3k of en route ATFM delay was reclassified, through the NM post-operations process, as airport ATFM delay and re-attributed to Vienna airport instead of Vienna ACC/APP.

- When the above post-operations re-attributions are factored in, the total en route delay for Austro Control in 2025 was 573k minutes in 2025, down from 595k minutes in 2024.

