## **2.2.1.A. KPI #1**

### **Assessment of the achieved level of actual performance in the environment KPA**

The KEA value has been achieved despite a challenging target and the substantially increased traffic.

### **Has the ANSP implemented any major operational or structural changes (incl. any new fixed assets put into operation) during the calendar year impacting performance in this key performance area? Please outline the relevant changes and their estimated impact**

Full FRA is active since 2016, offering throughout possibilities to fly shortest routes.

### **Progress on the implementation of the measures committed to in the ERNIP**

Since March 2024, FRAIT and SECSIFRA are operating in terms of cross border FRA.

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

n/a

### **Recommendations to the ANSP to rectify the situation**

n/a

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

n/a

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

Weather forecasting is undergoing continuous improvement

