## **TZ1.1. SECTION 1 -- UNIT COST**

### **TZ1.1.1. AUC VS. DUC**

In 2025, the terminal AUC was +3.7% (or +8.95 €2022) higher than the planned DUC. This results from the combination of higher than planned terminal costs in real terms (+2.8%, or +1.4 M€2022) and slightly lower than planned TNSUs (-0.9%).

### **TZ1.1.2. TERMINAL SERVICE UNITS**

The difference between actual and planned TNSUs (-0.9%) falls inside the ±2% dead-band. Hence, the loss of terminal revenues is borne by the ANSPs.

### **TZ1.1.3. TERMINAL COSTS BY ENTITY**

Actual real terminal costs are +2.8% (+1.4 M€2022) higher than planned. This is the result of higher costs for the main ANSP, Austro Control (+3.4%, or +1.6 M€2022) and the NSA (+19.1%, or +0.03 M€2022) and lower costs for the MET service provider (-7.8%, or -0.3 M€2022).

### **TZ1.1.4. TERMINAL COSTS FOR THE MAIN ANSP (AUSTRO CONTROL) AT CHARGING ZONE LEVEL**

Based on the additional information to the terminal reporting tables, the higher than planned terminal costs in real terms for Austro Control in 2025 (+3.4%, or +1.6 M€2022) result from:

- Significantly higher than planned staff costs (+5.7%), mainly due to higher than foreseen inflation and its effects on pension costs.

- Lower than planned other operating costs (-5.0%).

- Slightly lower than planned depreciation (-0.9%).

- Slightly higher than planned cost of capital (+1.8%).

- Slightly lower than planned exceptional costs (-0.9%), due to the effect of higher than planned inflation index (+1.1 p.p.) since in nominal terms the actual costs were equal to those planned.

### **TZ1.1.5. ASSESSMENT OF THE ACTUAL PERFORMANCE IN THE CHARGING ZONE REPORTED BY THE NSA**

The NSA of Austria provides the following overall assessment of the actual performance in 2025 at charging zone level:

*"Higher costs together with a higher inflation and less traffic than determined led to higher real en route unit costs."*

\[It should be noted that the extract from the NSA 2025 monitoring report cited above refers to "en-route" whereas it is reported under "terminal ANS" section of the report.\]

### **TZ1.1.6. EXPLANATION OF THE DIFFERENCES BETWEEN ACTUAL AND DETERMINED COSTS AT CHARGING ZONE LEVEL REPORTED BY THE NSA**

The NSA provides the following explanation for the differences between actual and determined costs in the charging zone:

*"Actual staff costs have been influenced by the higher than determined pension costs which are not within the ANSPs direct influence."*

### **TZ1.1.7. RECOMMENDATIONS FORMULATED BY THE NSA TO THE ANSP (AUSTRO CONTROL) TO RECTIFY THE SITUATION AND ACTIONS TAKEN BY THE ANSP**

No information was provided in the NSA 2025 Monitoring Report.

### **TZ1.1.8. NOTES**

#### **TZ1.1.8.1. NOTE 1**

#### **TZ1.1.8.2. NOTE 2**

