## SAF1.1. Effectiveness of Safety Management (EoSM) (KPI#1)

Austro Control achieved the planned maturity levels for 2025 for all components of the effectiveness of safety management (EoSM) and exceeded their planned levels for Safety Policy and Objectives. Austro Control needs to improve in the other 4 components to reach the targets by the end of RP4.

As described in the monitoring report, the verification of the proposed ANSP answers has been conducted by the NCA/NSA in the course of an EoSM audit held on the January 22, 2026. All EoSM targets from the national performance plan have been fully met by Austro Control GmbH. In terms of main measures put in place to achieve the safety performance targets, the report states that since improvements are needed by the end of the RP4, the ANSP has recognized the need to establish a project. Therefore, the specific work packages will be defined over the next few months. The project is scheduled to launch in 2026 and run through the end of 2029. A project update will be provided to the steering committee at least twice a year, and progress will also be closely monitored and overseen by the NCA/NSA.

