## **2.3.1.B. KPI #2**

### **Identification and analysis of the reasons and circumstances resulting in the achieved level of actual performance of the arrival ATFM delay per flight KPI**

Extreme WXC (CB and TS) situations were encountered at LOWW between May and September. 97% of the delays are attributable to adverse weather.

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

Despite a 10% improvement of the delay performance (at national level and for LOWW) it has proven impossible to achieve the targets, which are much lower than in the preceding year. The adverse weather conditions - in particular in LOWW - were the main contributing factor.

### **Recommendations to the ANSP to rectify the situation**

None

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

No measures, since weather impacts are inherently unpredictable and unavoidable.

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

n/a

