## **ER1.3.  SECTION 3 -- REGULATORY RESULT**

### **ER1.3.1. AUSTRO CONTROL NET GAIN/LOSS ON ACTIVITY IN THE AUSTRIA EN ROUTE CHARGING ZONE IN 2025**

Austro Control reported a net gain of +28.4 M€, as a combination of a gain of +20.2 M€ arising from the cost sharing mechanism, with a gain of +9.4 M€ arising from the traffic risk sharing mechanism and a loss of -1.1 M€ relating to financial incentives. See also Note 1 below.

### **ER1.3.2. AUSTRO CONTROL OVERALL REGULATORY RESULT (RR) FOR THE EN ROUTE ACTIVITY**

Ex-post, the overall RR, taking into account the net gain from the en route activity mentioned above (+28.4 M€) and the actual RoE (+4.7 M€), amounts to +33.1 M€ (13.3% of the en route revenues). The resulting ex-post rate of return on equity is 28.3%, which is higher than the 4.0% planned in the PP. See also Note 1 below.

### **ER1.3.3. NOTES** 

#### **ER1.3.3.1. NOTE 1**

The analysis presented above excludes the costs of meteorological services provided by Austro Control since MET figures are disclosed separately in en route reporting tables.

#### **ER1.3.3.2. NOTE 2**

# **TZ1. TERMINAL CHARGING ZONE - AUSTRIA**

