::: {.grid .align-items-center}
:::: {.g-col-9}
[Annual Monitoring Report `r toupper(params$year_folder)` - {{< var doc.country >}}]{.fakeh1}
::::

:::: {.g-col-3}
<span class="no-external-icon">[<i class="fa fa-download"></i> Download Report](`r params$home_address`/download/{{< var doc.year_report >}}/PRB-Annual-Monitoring-Report_{{< var doc.country >}}_{{< var doc.year_report >}}.pdf){.btn .btn-light .text-dark .border .bg-secondary-subtle .rounded}</span>
::::
:::


```{r context-data, eval=TRUE}

# to be added
```

## Contextual information
[to be added]


::: {#container-env style="clear: both"}

## Environment (FABEC)

:::: {#chart-env class="mychart"}
```{r chart-env-kea, options = (doclevel=c("level1"))}
#| file: R/chart_level1_kea.R
#| out.width: "99%"
```
::::


:::: {#concl-env}

```{r env_prb}
#| echo: false
#| output: asis

path <- sprintf("./qmd_parts/%s/%s/_%s_%s_prb_env.qmd", as.character(year_report),country,country, as.character(year_report))

replace_headings(path, character(0))

``` 

:::

::: {#container-cap style="clear: both"}

## Capacity (FABEC)
:::: {#chart-cap class="mychart"}
```{r chart-cap-er, options = (cztype=c("enroute"))}
#| file: R/chart_level1_cap.R
#| out.width: "99%"
```
::::

:::: {#concl-cap}

```{r cap_prb}
#| echo: false
#| output: asis

path <- sprintf("./qmd_parts/%s/%s/_%s_%s_prb_cap.qmd", as.character(year_report),country,country, as.character(year_report))

replace_headings(path, character(0))

``` 

::::
:::
