```{r mvt_prb}
#| echo: false
source("R/params_project.R")
```

## Document download - `r rp_short`

### PRB Annual Monitoring Report `r rp_years[[1]]`

::: {.grid}
:::: {.g-col-1}
::::

:::: {.g-col-10}

|  |  |  |
|-----------------------|-----------------------|------------------------|
| [SES RP4](download/2025/PRB-Annual-Monitoring-Report_SES%20RP4_2025.pdf) | [France](download/2025/PRB-Annual-Monitoring-Report_France_2025.pdf) | [Netherlands](download/2025/PRB-Annual-Monitoring-Report_Netherlands_2025.pdf) |
|  | [Germany](download/2025/PRB-Annual-Monitoring-Report_Germany_2025.pdf) | [Network Manager](download/2025/PRB-Annual-Monitoring-Report_Network%20Manager_2025.pdf) |
| [Austria](download/2025/PRB-Annual-Monitoring-Report_Austria_2025.pdf) | [Greece](download/2025/PRB-Annual-Monitoring-Report_Greece_2025.pdf) | [Norway](download/2025/PRB-Annual-Monitoring-Report_Norway_2025.pdf) |
| [Belgium](download/2025/PRB-Annual-Monitoring-Report_Belgium_2025.pdf) | [Hungary](download/2025/PRB-Annual-Monitoring-Report_Hungary_2025.pdf) | [Poland](download/2025/PRB-Annual-Monitoring-Report_Poland_2025.pdf) |
| [Bulgaria](download/2025/PRB-Annual-Monitoring-Report_Bulgaria_2025.pdf) | [Ireland](download/2025/PRB-Annual-Monitoring-Report_Ireland_2025.pdf) | [Portugal](download/2025/PRB-Annual-Monitoring-Report_Portugal_2025.pdf) |
| [Croatia](download/2025/PRB-Annual-Monitoring-Report_Croatia_2025.pdf) | [Italy](download/2025/PRB-Annual-Monitoring-Report_Italy_2025.pdf) | [Romania](download/2025/PRB-Annual-Monitoring-Report_Romania_2025.pdf) |
| [Cyprus](download/2025/PRB-Annual-Monitoring-Report_Cyprus_2025.pdf) | [Latvia](download/2025/PRB-Annual-Monitoring-Report_Latvia_2025.pdf) | [Slovakia](download/2025/PRB-Annual-Monitoring-Report_Slovakia_2025.pdf) |
| [Czech Republic](download/2025/PRB-Annual-Monitoring-Report_Czech%20Republic_2025.pdf) | [Lithuania](download/2025/PRB-Annual-Monitoring-Report_Lithuania_2025.pdf) | [Slovenia](download/2025/PRB-Annual-Monitoring-Report_Slovenia_2025.pdf) |
| [Denmark](download/2025/PRB-Annual-Monitoring-Report_Denmark_2025.pdf) | [Luxembourg](download/2025/PRB-Annual-Monitoring-Report_Luxembourg_2025.pdf) | [Spain](download/2025/PRB-Annual-Monitoring-Report_Spain_2025.pdf) |
| [Estonia](download/2025/PRB-Annual-Monitoring-Report_Estonia_2025.pdf) | [Malta](download/2025/PRB-Annual-Monitoring-Report_Denmark_2025.pdf) | [Sweden](download/2025/PRB-Annual-Monitoring-Report_Sweden_2025.pdf) |
| [Finland](download/2025/PRB-Annual-Monitoring-Report_Finland_2025.pdf) | [MUAC](download/2025/PRB-Annual-Monitoring-Report_MUAC_2025.pdf) | [Switzerland](download/2025/PRB-Annual-Monitoring-Report_Switzerland_2025.pdf) |

:::: 

:::: {.g-col-1}
::::
:::

## Document download - RP3

### PRB Annual Monitoring Report 2024

::: {.grid}
:::: {.g-col-1}
::::

:::: {.g-col-10}

|  |  |  |
|-----------------------|-----------------------|------------------------|
| [SES RP4](rp3/download/2024/PRB-Annual-Monitoring-Report_SES%20RP3_2024.pdf) | [France](rp3/download/2024/PRB-Annual-Monitoring-Report_France_2024.pdf) | [Netherlands](rp3/download/2024/PRB-Annual-Monitoring-Report_Netherlands_2024.pdf) |
|  | [Germany](rp3/download/2024/PRB-Annual-Monitoring-Report_Germany_2024.pdf) | [Network Manager](rp3/download/2024/PRB-Annual-Monitoring-Report_Network%20Manager_2024.pdf) |
| [Austria](rp3/download/2024/PRB-Annual-Monitoring-Report_Austria_2024.pdf) | [Greece](rp3/download/2024/PRB-Annual-Monitoring-Report_Greece_2024.pdf) | [Norway](rp3/download/2024/PRB-Annual-Monitoring-Report_Norway_2024.pdf) |
| [Belgium](rp3/download/2024/PRB-Annual-Monitoring-Report_Belgium_2024.pdf) | [Hungary](rp3/download/2024/PRB-Annual-Monitoring-Report_Hungary_2024.pdf) | [Poland](rp3/download/2024/PRB-Annual-Monitoring-Report_Poland_2024.pdf) |
| [Bulgaria](rp3/download/2024/PRB-Annual-Monitoring-Report_Bulgaria_2024.pdf) | [Ireland](rp3/download/2024/PRB-Annual-Monitoring-Report_Ireland_2024.pdf) | [Portugal](rp3/download/2024/PRB-Annual-Monitoring-Report_Portugal_2024.pdf) |
| [Croatia](rp3/download/2024/PRB-Annual-Monitoring-Report_Croatia_2024.pdf) | [Italy](rp3/download/2024/PRB-Annual-Monitoring-Report_Italy_2024.pdf) | [Romania](rp3/download/2024/PRB-Annual-Monitoring-Report_Romania_2024.pdf) |
| [Cyprus](rp3/download/2024/PRB-Annual-Monitoring-Report_Cyprus_2024.pdf) | [Latvia](rp3/download/2024/PRB-Annual-Monitoring-Report_Latvia_2024.pdf) | [Slovakia](rp3/download/2024/PRB-Annual-Monitoring-Report_Slovakia_2024.pdf) |
| [Czech Republic](rp3/download/2024/PRB-Annual-Monitoring-Report_Czech%20Republic_2024.pdf) | [Lithuania](rp3/download/2024/PRB-Annual-Monitoring-Report_Lithuania_2024.pdf) | [Slovenia](rp3/download/2024/PRB-Annual-Monitoring-Report_Slovenia_2024.pdf) |
| [Denmark](rp3/download/2024/PRB-Annual-Monitoring-Report_Denmark_2024.pdf) | [Luxembourg](rp3/download/2024/PRB-Annual-Monitoring-Report_Luxembourg_2024.pdf) | [Spain](rp3/download/2024/PRB-Annual-Monitoring-Report_Spain_2024.pdf) |
| [Estonia](rp3/download/2024/PRB-Annual-Monitoring-Report_Estonia_2024.pdf) | [Malta](rp3/download/2024/PRB-Annual-Monitoring-Report_Denmark_2024.pdf) | [Sweden](rp3/download/2024/PRB-Annual-Monitoring-Report_Sweden_2024.pdf) |
| [Finland](rp3/download/2024/PRB-Annual-Monitoring-Report_Finland_2024.pdf) | [MUAC](rp3/download/2024/PRB-Annual-Monitoring-Report_MUAC_2024.pdf) | [Switzerland](rp3/download/2024/PRB-Annual-Monitoring-Report_Switzerland_2024.pdf) |

:::: 

:::: {.g-col-1}
::::
:::

### PRB Annual Monitoring Report 2023

::: {.grid}
:::: {.g-col-1}
::::

:::: {.g-col-10}

|  |  |  |
|-----------------------|-----------------------|------------------------|
| [SES RP4](rp3/download/2023/PRB-Annual-Monitoring-Report_SES%20RP3_2023.pdf) | [France](rp3/download/2023/PRB-Annual-Monitoring-Report_France_2023.pdf) | [Netherlands](rp3/download/2023/PRB-Annual-Monitoring-Report_Netherlands_2023.pdf) |
|  | [Germany](rp3/download/2023/PRB-Annual-Monitoring-Report_Germany_2023.pdf) | [Network Manager](rp3/download/2023/PRB-Annual-Monitoring-Report_Network%20Manager_2023.pdf) |
| [Austria](rp3/download/2023/PRB-Annual-Monitoring-Report_Austria_2023.pdf) | [Greece](rp3/download/2023/PRB-Annual-Monitoring-Report_Greece_2023.pdf) | [Norway](rp3/download/2023/PRB-Annual-Monitoring-Report_Norway_2023.pdf) |
| [Belgium](rp3/download/2023/PRB-Annual-Monitoring-Report_Belgium_2023.pdf) | [Hungary](rp3/download/2023/PRB-Annual-Monitoring-Report_Hungary_2023.pdf) | [Poland](rp3/download/2023/PRB-Annual-Monitoring-Report_Poland_2023.pdf) |
| [Bulgaria](rp3/download/2023/PRB-Annual-Monitoring-Report_Bulgaria_2023.pdf) | [Ireland](rp3/download/2023/PRB-Annual-Monitoring-Report_Ireland_2023.pdf) | [Portugal](rp3/download/2023/PRB-Annual-Monitoring-Report_Portugal_2023.pdf) |
| [Croatia](rp3/download/2023/PRB-Annual-Monitoring-Report_Croatia_2023.pdf) | [Italy](rp3/download/2023/PRB-Annual-Monitoring-Report_Italy_2023.pdf) | [Romania](rp3/download/2023/PRB-Annual-Monitoring-Report_Romania_2023.pdf) |
| [Cyprus](rp3/download/2023/PRB-Annual-Monitoring-Report_Cyprus_2023.pdf) | [Latvia](rp3/download/2023/PRB-Annual-Monitoring-Report_Latvia_2023.pdf) | [Slovakia](rp3/download/2023/PRB-Annual-Monitoring-Report_Slovakia_2023.pdf) |
| [Czech Republic](rp3/download/2023/PRB-Annual-Monitoring-Report_Czech%20Republic_2023.pdf) | [Lithuania](rp3/download/2023/PRB-Annual-Monitoring-Report_Lithuania_2023.pdf) | [Slovenia](rp3/download/2023/PRB-Annual-Monitoring-Report_Slovenia_2023.pdf) |
| [Denmark](rp3/download/2023/PRB-Annual-Monitoring-Report_Denmark_2023.pdf) | [Luxembourg](rp3/download/2023/PRB-Annual-Monitoring-Report_Luxembourg_2023.pdf) | [Spain](rp3/download/2023/PRB-Annual-Monitoring-Report_Spain_2023.pdf) |
| [Estonia](rp3/download/2023/PRB-Annual-Monitoring-Report_Estonia_2023.pdf) | [Malta](rp3/download/2023/PRB-Annual-Monitoring-Report_Denmark_2023.pdf) | [Sweden](rp3/download/2023/PRB-Annual-Monitoring-Report_Sweden_2023.pdf) |
| [Finland](rp3/download/2023/PRB-Annual-Monitoring-Report_Finland_2023.pdf) | [MUAC](rp3/download/2023/PRB-Annual-Monitoring-Report_MUAC_2023.pdf) | [Switzerland](rp3/download/2023/PRB-Annual-Monitoring-Report_Switzerland_2023.pdf) |

:::: 

:::: {.g-col-1}
::::
:::

### PRB Annual Monitoring Report 2022

::: {.grid}
:::: {.g-col-1}
::::

:::: {.g-col-10}

|  |  |  |
|-----------------------|-----------------------|------------------------|
| [SES RP4](rp3/download/2022/PRB-Annual-Monitoring-Report_SES%20RP3_2022.pdf) | [France](rp3/download/2022/PRB-Annual-Monitoring-Report_France_2022.pdf) | [Netherlands](rp3/download/2022/PRB-Annual-Monitoring-Report_Netherlands_2022.pdf) |
|  | [Germany](rp3/download/2022/PRB-Annual-Monitoring-Report_Germany_2022.pdf) | [Network Manager](rp3/download/2022/PRB-Annual-Monitoring-Report_Network%20Manager_2022.pdf) |
| [Austria](rp3/download/2022/PRB-Annual-Monitoring-Report_Austria_2022.pdf) | [Greece](rp3/download/2022/PRB-Annual-Monitoring-Report_Greece_2022.pdf) | [Norway](rp3/download/2022/PRB-Annual-Monitoring-Report_Norway_2022.pdf) |
| [Belgium](rp3/download/2022/PRB-Annual-Monitoring-Report_Belgium_2022.pdf) | [Hungary](rp3/download/2022/PRB-Annual-Monitoring-Report_Hungary_2022.pdf) | [Poland](rp3/download/2022/PRB-Annual-Monitoring-Report_Poland_2022.pdf) |
| [Bulgaria](rp3/download/2022/PRB-Annual-Monitoring-Report_Bulgaria_2022.pdf) | [Ireland](rp3/download/2022/PRB-Annual-Monitoring-Report_Ireland_2022.pdf) | [Portugal](rp3/download/2022/PRB-Annual-Monitoring-Report_Portugal_2022.pdf) |
| [Croatia](rp3/download/2022/PRB-Annual-Monitoring-Report_Croatia_2022.pdf) | [Italy](rp3/download/2022/PRB-Annual-Monitoring-Report_Italy_2022.pdf) | [Romania](rp3/download/2022/PRB-Annual-Monitoring-Report_Romania_2022.pdf) |
| [Cyprus](rp3/download/2022/PRB-Annual-Monitoring-Report_Cyprus_2022.pdf) | [Latvia](rp3/download/2022/PRB-Annual-Monitoring-Report_Latvia_2022.pdf) | [Slovakia](rp3/download/2022/PRB-Annual-Monitoring-Report_Slovakia_2022.pdf) |
| [Czech Republic](rp3/download/2022/PRB-Annual-Monitoring-Report_Czech%20Republic_2022.pdf) | [Lithuania](rp3/download/2022/PRB-Annual-Monitoring-Report_Lithuania_2022.pdf) | [Slovenia](rp3/download/2022/PRB-Annual-Monitoring-Report_Slovenia_2022.pdf) |
| [Denmark](rp3/download/2022/PRB-Annual-Monitoring-Report_Denmark_2022.pdf) | [Luxembourg](rp3/download/2022/PRB-Annual-Monitoring-Report_Luxembourg_2022.pdf) | [Spain](rp3/download/2022/PRB-Annual-Monitoring-Report_Spain_2022.pdf) |
| [Estonia](rp3/download/2022/PRB-Annual-Monitoring-Report_Estonia_2022.pdf) | [Malta](rp3/download/2022/PRB-Annual-Monitoring-Report_Denmark_2022.pdf) | [Sweden](rp3/download/2022/PRB-Annual-Monitoring-Report_Sweden_2022.pdf) |
| [Finland](rp3/download/2022/PRB-Annual-Monitoring-Report_Finland_2022.pdf) | [MUAC](rp3/download/2022/PRB-Annual-Monitoring-Report_MUAC_2022.pdf) | [Switzerland](rp3/download/2022/PRB-Annual-Monitoring-Report_Switzerland_2022.pdf) |

:::: 

:::: {.g-col-1}
::::
:::

### PRB Annual Monitoring Report 2021

::: {.grid}
:::: {.g-col-1}
::::

:::: {.g-col-10}

|  |  |  |
|-----------------------|-----------------------|------------------------|
| [SES RP4](rp3/download/2021/PRB-Annual-Monitoring-Report_SES%20RP3_2021.pdf) | [France](rp3/download/2021/PRB-Annual-Monitoring-Report_France_2021.pdf) | [Netherlands](rp3/download/2021/PRB-Annual-Monitoring-Report_Netherlands_2021.pdf) |
|  | [Germany](rp3/download/2021/PRB-Annual-Monitoring-Report_Germany_2021.pdf) | [Network Manager](rp3/download/2021/PRB-Annual-Monitoring-Report_Network%20Manager_2021.pdf) |
| [Austria](rp3/download/2021/PRB-Annual-Monitoring-Report_Austria_2021.pdf) | [Greece](rp3/download/2021/PRB-Annual-Monitoring-Report_Greece_2021.pdf) | [Norway](rp3/download/2021/PRB-Annual-Monitoring-Report_Norway_2021.pdf) |
| [Belgium](rp3/download/2021/PRB-Annual-Monitoring-Report_Belgium_2021.pdf) | [Hungary](rp3/download/2021/PRB-Annual-Monitoring-Report_Hungary_2021.pdf) | [Poland](rp3/download/2021/PRB-Annual-Monitoring-Report_Poland_2021.pdf) |
| [Bulgaria](rp3/download/2021/PRB-Annual-Monitoring-Report_Bulgaria_2021.pdf) | [Ireland](rp3/download/2021/PRB-Annual-Monitoring-Report_Ireland_2021.pdf) | [Portugal](rp3/download/2021/PRB-Annual-Monitoring-Report_Portugal_2021.pdf) |
| [Croatia](rp3/download/2021/PRB-Annual-Monitoring-Report_Croatia_2021.pdf) | [Italy](rp3/download/2021/PRB-Annual-Monitoring-Report_Italy_2021.pdf) | [Romania](rp3/download/2021/PRB-Annual-Monitoring-Report_Romania_2021.pdf) |
| [Cyprus](rp3/download/2021/PRB-Annual-Monitoring-Report_Cyprus_2021.pdf) | [Latvia](rp3/download/2021/PRB-Annual-Monitoring-Report_Latvia_2021.pdf) | [Slovakia](rp3/download/2021/PRB-Annual-Monitoring-Report_Slovakia_2021.pdf) |
| [Czech Republic](rp3/download/2021/PRB-Annual-Monitoring-Report_Czech%20Republic_2021.pdf) | [Lithuania](rp3/download/2021/PRB-Annual-Monitoring-Report_Lithuania_2021.pdf) | [Slovenia](rp3/download/2021/PRB-Annual-Monitoring-Report_Slovenia_2021.pdf) |
| [Denmark](rp3/download/2021/PRB-Annual-Monitoring-Report_Denmark_2021.pdf) | [Luxembourg](rp3/download/2021/PRB-Annual-Monitoring-Report_Luxembourg_2021.pdf) | [Spain](rp3/download/2021/PRB-Annual-Monitoring-Report_Spain_2021.pdf) |
| [Estonia](rp3/download/2021/PRB-Annual-Monitoring-Report_Estonia_2021.pdf) | [Malta](rp3/download/2021/PRB-Annual-Monitoring-Report_Denmark_2021.pdf) | [Sweden](rp3/download/2021/PRB-Annual-Monitoring-Report_Sweden_2021.pdf) |
| [Finland](rp3/download/2021/PRB-Annual-Monitoring-Report_Finland_2021.pdf) | [MUAC](rp3/download/2021/PRB-Annual-Monitoring-Report_MUAC_2021.pdf) | [Switzerland](rp3/download/2021/PRB-Annual-Monitoring-Report_Switzerland_2021.pdf) |

:::: 

:::: {.g-col-1}
::::
:::

### PRB Annual Monitoring Report 2020

::: {.grid}
:::: {.g-col-1}
::::

:::: {.g-col-10}

|  |  |  |
|-----------------------|-----------------------|------------------------|
| [SES RP4](rp3/download/2020/PRB-Annual-Monitoring-Report_SES%20RP3_2020.pdf) | [France](rp3/download/2020/PRB-Annual-Monitoring-Report_France_2020.pdf) | [Netherlands](rp3/download/2020/PRB-Annual-Monitoring-Report_Netherlands_2020.pdf) |
|  | [Germany](rp3/download/2020/PRB-Annual-Monitoring-Report_Germany_2020.pdf) | [Network Manager](rp3/download/2020/PRB-Annual-Monitoring-Report_Network%20Manager_2020.pdf) |
| [Austria](rp3/download/2020/PRB-Annual-Monitoring-Report_Austria_2020.pdf) | [Greece](rp3/download/2020/PRB-Annual-Monitoring-Report_Greece_2020.pdf) | [Norway](rp3/download/2020/PRB-Annual-Monitoring-Report_Norway_2020.pdf) |
| [Belgium](rp3/download/2020/PRB-Annual-Monitoring-Report_Belgium_2020.pdf) | [Hungary](rp3/download/2020/PRB-Annual-Monitoring-Report_Hungary_2020.pdf) | [Poland](rp3/download/2020/PRB-Annual-Monitoring-Report_Poland_2020.pdf) |
| [Bulgaria](rp3/download/2020/PRB-Annual-Monitoring-Report_Bulgaria_2020.pdf) | [Ireland](rp3/download/2020/PRB-Annual-Monitoring-Report_Ireland_2020.pdf) | [Portugal](rp3/download/2020/PRB-Annual-Monitoring-Report_Portugal_2020.pdf) |
| [Croatia](rp3/download/2020/PRB-Annual-Monitoring-Report_Croatia_2020.pdf) | [Italy](rp3/download/2020/PRB-Annual-Monitoring-Report_Italy_2020.pdf) | [Romania](rp3/download/2020/PRB-Annual-Monitoring-Report_Romania_2020.pdf) |
| [Cyprus](rp3/download/2020/PRB-Annual-Monitoring-Report_Cyprus_2020.pdf) | [Latvia](rp3/download/2020/PRB-Annual-Monitoring-Report_Latvia_2020.pdf) | [Slovakia](rp3/download/2020/PRB-Annual-Monitoring-Report_Slovakia_2020.pdf) |
| [Czech Republic](rp3/download/2020/PRB-Annual-Monitoring-Report_Czech%20Republic_2020.pdf) | [Lithuania](rp3/download/2020/PRB-Annual-Monitoring-Report_Lithuania_2020.pdf) | [Slovenia](rp3/download/2020/PRB-Annual-Monitoring-Report_Slovenia_2020.pdf) |
| [Denmark](rp3/download/2020/PRB-Annual-Monitoring-Report_Denmark_2020.pdf) | [Luxembourg](rp3/download/2020/PRB-Annual-Monitoring-Report_Luxembourg_2020.pdf) | [Spain](rp3/download/2020/PRB-Annual-Monitoring-Report_Spain_2020.pdf) |
| [Estonia](rp3/download/2020/PRB-Annual-Monitoring-Report_Estonia_2020.pdf) | [Malta](rp3/download/2020/PRB-Annual-Monitoring-Report_Denmark_2020.pdf) | [Sweden](rp3/download/2020/PRB-Annual-Monitoring-Report_Sweden_2020.pdf) |
| [Finland](rp3/download/2020/PRB-Annual-Monitoring-Report_Finland_2020.pdf) | [MUAC](rp3/download/2020/PRB-Annual-Monitoring-Report_MUAC_2020.pdf) | [Switzerland](rp3/download/2020/PRB-Annual-Monitoring-Report_Switzerland_2020.pdf) |

:::: 

:::: {.g-col-1}
::::
:::
