## SAF1.3. Rate of runway incursions (RIs) (PI#1)

Ireland reported 1 runway incursion (RI) at Shannon airport during 2025. When comparing the RIs at airport level to Union-wide level, Ireland was below the Union-wide average (0.29 vs 2.53).

Ireland reported 1 RI with ATS/CNS contribution in 2025. When comparing airport level with ATS/CNS contribution to the Union-wide level, Ireland was below the Union-wide average (0.29 vs 0.96).

The rate of runway incursions has decreased significantly compared to 2024 at both airport level (0.29 vs 5.16) and at ATS/CNS contribution-level (0.29 vs 2.35).

As described in the monitoring report, AirNav Ireland acknowledges that preventing runway incursions requires vigilance, technological advancements, and industry-wide collaboration to ensure runway safety. The organisation focuses on enhancing cooperation among airports, air traffic management, and airlines to reduce the risk of incursions. This approach includes continuous engagement and representation at both Local Runway Safety Teams and the IAA National Runway Safety Team, supporting the Global Action Plan for the Prevention of Runway Incursions, and addressing any gaps in current safety measures. Additionally, AirNav Ireland has received Board approval for the installation of advanced surface movement and guidance systems at Cork and Shannon Airports. AirNav Ireland has developed and implemented leading and lagging indicators to monitor the effectiveness of safety measures to prevent runway incursions. These indicators are reviewed at the Safety Review Board and through Safety Action Group. Runway incursions are documented on the enterprise risk register and monitored for safety assurance.

The NSA notes in the monitoring report that the NSA/NCA have for several years, including 2025, used the Event Risk Classification (ERC) of the ARMS Methodology for conducting its risk classification of mandatory occurrences reported by organisations. The ARMS (ERC) methodology is a similar assessment to ERCS, albeit a more simplified version. Of most significance, the ARMS risk scores are directly translatable to the common European risk classification scheme (ERCS) and therefore the data is verifiable. The State provides its data for safety performance indicators during 2024 based on ARMS (ERC) classifications. The NSA/NCA monitors a selection of appropriate Safety Performance Indicators (SPIs), including RI & SMI. For the defined SPIs, there are associated safety targets and alert thresholds in order to provide quantifiable measures for the maintenance and/or improvement of the level of safety for the air navigation services domain in Ireland. This methodology is developed to identify an Acceptable level of safety performance (AloSP) and is aligned with ICAO Doc 9859.

Furthermore, based on the NSA/NCA monitoring of RIs in 2025, via the above-described methodology, the rate of RIs was below the target set for 2025.

