## **2.3.1.A. KPI #1**

### **Identification and analysis of the reasons and circumstances resulting in the achieved level of actual performance of the en-route ATFM delay per flight KPI**

Average en route ATFM delay per overflight was 0.01 minutes per flight, consistent with the target and broadly in line with previous years. A Eurocontrol CAPAN study is taking place during 2026 to examine operations at Dublin ACC and Shannon ACC. The IAA and AirNav Ireland meet regularly to discuss the peformance indicators, including ATFM delay.

### **Description of the adjustments to the capacity plan included in adopted performance plan**

The NSA has introduced an additional capacity incentive scheme which aims to incentivise the ANSP to meet its ATCO and ATSEP hiring targets.

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

N/A.

### **Recommendations to the ANSP to rectify the situation**

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

