## **2.2.2.G. PI #7**

### **What initiatives were implemented or are planned that will improve this PI and how does the NSA intend on monitoring their effectiveness on performance?**

AirNav Ireland is engaging key airlines about Continuous Descent Operations (CDO) performance at Irish airports where it provides ATM services. The data highlights a significant difference in CDO achievd by airlines and as a result there is significant potential to improve overall CDO performance.

AirNav Ireland has established an environmental taskforce to support improved environmental performance, with increased monitoring, trials and a review of airspace changes that may be required to further facilitate airlines improve CDO.

Trials conducted at Shannon and Cork airports in 2024 provided useful information to the ANSP in the context of development of timebound procedures. Airlines serving Cork during the first 30 days of the trial advised of fuel savings of approx. 21,000 Kgs. The output from the trials is under discussion as part of the low-level airspace review and associated changes to the Shannon and Cork CTRs.

