## **2.2.2.F. PI #6**

### **What initiatives were implemented or are planned that will improve this PI and how does the NSA intend on monitoring their effectiveness on performance?**

AirNav Ireland is working with the airlines at Dublin airport to reduce the frequency of early arrivals at the airport, which will reduce the number of early arriving aircraft placed in the hold prior to 07:00 local time to facilitate a focus on the 1st wave of departures, in keeping with the Network Manager's operational priorities which is in turn supported by airlines. The Dublin Airport Planning Group established a subgroup suggested by the ANSP to progress improvements in this area.

A review of the Dublin airspace is ongoing and includes:

- Review of and update to IFP\'s as required to ensure regulatory compliance

- Interface meetings have taken place between Shannon and Dublin to review current procedures with a view to improving day to day operations as well as lay the ground work for future changes and developments. Work will continue in this area in 2026.

### **If the data at airport level are not available, please explain the reasons why data is missing and describe the measures planned to resolve the situation**

