## **TZ1.1. SECTION 1 -- UNIT COST**

### **TZ1.1.1. AUC VS. DUC**

In 2025, the terminal AUC was -1.9% (or -2.97 €2022) lower than the planned DUC. This results from the combination of significantly lower than planned terminal costs in real terms (-5.6%, or -1.9 M€2022) and lower than planned TNSUs (-3.7%).

### **TZ1.1.2. TERMINAL SERVICE UNITS**

The difference between actual and planned TNSUs (-3.7%) falls outside the ±2% dead-band, but does not exceed the ±10% threshold foreseen in the traffic risk sharing mechanism. The resulting loss of terminal revenues is therefore shared between the ANSP and the airspace users (see the main ANSP regulatory result).

### **TZ1.1.3. TERMINAL COSTS BY ENTITY**

Actual real terminal costs are -5.6% (-1.9 M€2022) lower than planned. This is the result of lower costs for the main ANSP, AirNav Ireland (-6.4%, or -1.9 M€2022) and higher costs for the NSA (+0.2%, or +0.003 M€2022), the MET service provider (+1.4%, or +0.03 M€2022).

### **TZ1.1.4. TERMINAL COSTS FOR THE MAIN ANSP (AIRNAV IRELAND) AT CHARGING ZONE LEVEL**

Based on the additional information to the terminal reporting tables, the significantly lower than planned terminal costs in real terms for AirNav Ireland in 2025 (-6.4%, or -1.9 M€2022) result from:

- Slightly higher than planned staff costs (+0.8%).

- Significantly lower than planned other operating costs (-9.7%), where "*other operating costs comprise training, systems and equipment maintenance, telecommunications, spares, power and administration costs including rent and rates, insurance, security, building repairs and maintenance."*

- Significantly lower than planned depreciation (-14.4%), mainly reflecting *"a shortfall in technical and operational resources necessary to deliver capital projects."*

- Significantly lower than planned cost of capital (-12.9%), mainly *"due to delays in project completions as outlined above."*

### **TZ1.1.5. ASSESSMENT OF THE ACTUAL PERFORMANCE IN THE CHARGING ZONE REPORTED BY THE NSA**

*"The actual unit cost was 1.9% below forecast. Total nominal terminal costs for 2025 were 5.3% below the forecast level, and the real total terminal cost was 5.6% below the level forecast in the Performance Plan. The lower total real costs were mitigated by a 3.7% reduction in TNSUs but still resulted in a DUC outperformance of 1.9%."*

### **TZ1.1.6. EXPLANATION OF THE DIFFERENCES BETWEEN ACTUAL AND DETERMINED COSTS AT CHARGING ZONE LEVEL REPORTED BY THE NSA**

*"The ANSP\'s total operating costs were 9.5% lower than forecast. This comprises training, systems and equipment maintenance, telecommunications, spares, power and administration costs including rent and rates, insurance, security, building repairs and maintenance. Depreciation costs for ANI and the NSA were below determined. For the NSA this relates to a later than expected capitalisation of the largest investment. For AirNav Ireland, actual capital costs of both depreciation and cost of capital were lower than determined due to delays in project completions."*

### **TZ1.1.7. RECOMMENDATIONS FORMULATED BY THE NSA TO THE ANSP (AIRNAV IRELAND) TO RECTIFY THE SITUATION AND ACTIONS TAKEN BY THE ANSP**

*"Continue efforts to hire engineers and ATCOs. This will allow ANI to allocate resources to its capex programme."*

AirNav Ireland reports the implementation of the following actions:

*"The ANSP will return any costs associated with unspent capex to users in RP5."*

### **TZ1.1.8. NOTES**

#### **TZ1.1.8.1. NOTE 1**

#### **TZ1.1.8.2. NOTE 2**

