## **2.2.2.B. PI #2**

### **What initiatives were implemented or are planned that will improve this PI and how does the NSA intend on monitoring their effectiveness on performance?**

The flight plan trajectory within the EISN FIR is determined by the airspace users' preferences as a free route airspace (FRA) concept of operations applies within Irish airspace. Differences from the shortest constrained trajectory are therefore a result of the trajectory planned by the airspace user. Accordingly, inefficiencies in KES result from factors outside of Irish airspace and therefore, outside of the ANSP's control.

The Low Level airspace review continued with the following completed and ongoing:

1\. The removal of the last remaining routes (which were available for flight planning but not mandatory)

2\. Additional controlled airspace introduced at Ireland West airport to protect instrument flight procedures and faciliate CCO/CDO

Work continued on the development of new IFP\'s and associated changes for the Shannon and Cork CTRs. This area continues to be a work in progress.

