## **2.3.3 ATCO Planning 1**

### **Additional comments**

The number of ATCOs split by ACC, APP and TWR is the combined total across four service units (Dublin, SNN ENR, CTBU & STBU). The number of ATCOs in ops allocated to the en route cost base relates to Dublin (EIDW) and Shannon (EISN) only. The figures are the Average FTE ATCOs over 2025.

### **Additional comments**

### **Description of the training process, including details on the effective failure rate and the process used to allocate newly qualified ATCOs between ACC, APP and TWR positions**

The calculations are based on a 70% pass rate. Operational decisions as regards the allocation of ATCOs to the various control centres is a matter for AirNav Ireland, based on need. ATCOs are typically multi-rated and assigned to locations, rather than being limited to being assigned to ACC, APP, or TWR positions. In some cases, for example, ATCOs at the Dublin control centre are licensed for all three of ACC, APP, and TWR positions, which is intended to allow for the provision of flexible, scalable, and cost effective capacity.

The training process for ATCOs is partially outsourced to Entry Point North. In relation to licenced training such as unit endorsement training or continuation training, AirNav Ireland is contracted by EPN to provide this training service (unit endorsement training has to be completed by an ATCO rated in that unit). On the job training is provided by AirNav Ireland. Other aspects of the training process (e.g., initial assessments) are carried out by AirNav Ireland without any involvement of EPN.

