## **ER1.2. SECTION 2 - ACTUAL UNIT COSTS INCURRED BY THE USERS**

### **ER1.2.1. FOCUS ON EN ROUTE AUCU MONITORING AT CHARGING ZONE LEVEL**

The actual en route unit cost incurred by airspace users (AUCU) in respect of activities performed in 2025 (58.65 €) is -3.5% lower than the nominal DUC (60.78 €). The difference between these two figures (-2.13 €/SU) is due to:

- the negative inflation adjustment resulting from lower than planned inflation (-0.12 €/SU);

- the impact of adjustments resulting from the costs exempted from cost sharing mechanism (+0.31 €/SU);

- the deduction of the traffic risk sharing adjustments (-2.11 €/SU);

- the deduction of the traffic adjustment (-0.49 €/SU) for the costs not subject to traffic risk sharing; and,

- the impact of financial incentives (+0.28 €/SU).

The share of the regulatory result (see next sub-section) in the AUCU (before the deduction of other revenues) is 5.1%.

### **ER1.2.2. INITIATIVES IMPLEMENTED OR PLANNED THAT WILL IMPROVE THIS PI REPORTED BY THE NSA**

No information on such initiatives was provided in the NSA 2025 Monitoring Report.

### **ER1.2.3. NOTES** 

#### **ER1.2.3.1. NOTE 1**

#### **ER1.2.3.1. NOTE 2**

