## **2.2.1.A. KPI #1**

### **Assessment of the achieved level of actual performance in the environment KPA**

Cross border FRA fully implemented.

### **Has the ANSP implemented any major operational or structural changes (incl. any new fixed assets put into operation) during the calendar year impacting performance in this key performance area? Please outline the relevant changes and their estimated impact**

No

### **Progress on the implementation of the measures committed to in the ERNIP**

All done.

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

Shortest flight planning options already close to optimum, with some RAD restrictions in place.

### **Recommendations to the ANSP to rectify the situation**

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

Cross border free route implemented with all the neighbours.

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

