## **2.3.1.A. KPI #1**

### **Identification and analysis of the reasons and circumstances resulting in the achieved level of actual performance of the en-route ATFM delay per flight KPI**

Traffic much higher than planned in the Performance plan, but flexible shifts and rostering system used accomodate demand. Majority of delays is caused due to weather.

### **Description of the adjustments to the capacity plan included in adopted performance plan**

LARA implementation planned to be completed in 2025;

Enhanced ATFCM techniques, including STAM;

Full FRA implementation;

Additional ATCOs;

ATM system upgrades;

Flexible sector configurations, adapting regularly based on demand.

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

N/A

### **Recommendations to the ANSP to rectify the situation**

N/A

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

N/A

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

Additional shifts implemented, ATCOs intake and training increased.

