## SAF1.1. Effectiveness of Safety Management (EoSM) (KPI#1)

In 2025, ROMATSA did not achieve the planned maturity levels set out in its performance plan for three out of five components of the EoSM. The components where ROMATSA missed the planned levels were Safety Policy and Objectives, Safety Promotion and Safety Culture.

## According to the NSA assessment of the actual performance, as described in the monitoring report, Romania/ANSP ROMATSA achieved the Safety targets in 2025 (Level C) for Safety Risk Management and Safety Assurance, the rest of the safety management objectives (Safety Policy and Objectives, Safety Promotion and Safety Culture) were assessed by the NSA at Level B, as per the final reporting exercise of EoSM (1st of June 2026). The main areas of improvement are related to: the Just Culture Policy, to incorporate the types of operational behaviours which are unacceptable by the Organization; Human Factors (HF) Expert/ Specialist with a relevant academic degree and / or professional experience recognized by a professional body; the periodic monitoring of the key suppliers (quarterly as per the EoSM guidance) and HF factors in the related agreements; hazard identification; competency of the staff and contractors who directly support air navigation service provision. {#according-to-the-nsa-assessment-of-the-actual-performance-as-described-in-the-monitoring-report-romaniaansp-romatsa-achieved-the-safety-targets-in-2025-level-c-for-safety-risk-management-and-safety-assurance-the-rest-of-the-safety-management-objectives-safety-policy-and-objectives-safety-promotion-and-safety-culture-were-assessed-by-the-nsa-at-level-b-as-per-the-final-reporting-exercise-of-eosm-1st-of-june-2026.-the-main-areas-of-improvement-are-related-to-the-just-culture-policy-to-incorporate-the-types-of-operational-behaviours-which-are-unacceptable-by-the-organization-human-factors-hf-expert-specialist-with-a-relevant-academic-degree-and-or-professional-experience-recognized-by-a-professional-body-the-periodic-monitoring-of-the-key-suppliers-quarterly-as-per-the-eosm-guidance-and-hf-factors-in-the-related-agreements-hazard-identification-competency-of-the-staff-and-contractors-who-directly-support-air-navigation-service-provision. .Heading-2-ER}

In terms of main measures put in place to achieve the targets, the report defines the following: ROMATSA\'s safety objective is \"the improvement of its safety level so that the number of accidents, serious or risk-bearing incidents induced by air navigation services provided by ROMATSA do not increase and, whenever possible, decreases.\" ROMATSA considers the safety KPA as having priority over all other KPAs, with this approach formalised in the DANUBE FAB Safety Policy: \"Safety has priority over commercial, operational, environmental and social pressures.\" In this respect, safety is paramount and all other KPAs must be managed in a manner that does not reduce the level of safety. Compliance with the requirements set out in Regulation (EU) 2017/373 was confirmed by the Romanian Civil Aviation Authority at the time of certification, based on a compliance matrix. ROMATSA\'s recertifications as an ATM/ANS Service Provider are equally based on a compliance matrix with applicable regulations.

Furthermore, safety being the first priority, all ROMATSA employees are aware of their individual safety roles. The Safety Policy states that each employee is individually responsible for safety. Safety training modules are delivered to front-line operators, and the value of safety is promoted throughout the organisation as a core operational requirement. Management commitment is documented in the Safety Policy and is focused on continuous improvement. Employees are encouraged to share experience with peers and with management. Lessons learned are captured through investigation and safety surveillance processes and disseminated across the organisation. All employees are trained in the essentials of the Safety Management Manual, with dedicated training delivered to those with specific safety responsibilities, including managers and front-line operators. Safety risk assessment processes and procedures take into account the need to prepare staff for changes that may affect safety, with consultation, involvement and training considered accordingly. All ROMATSA organisational units have one or more Local Safety Coordinators, typically appointed from frontline staff (ATC and technical personnel). ROMATSA\'s Safety Department verifies on a permanent basis that all necessary corrective actions have been duly established and applied. ROMATSA ensures the allocation of necessary funds for the fulfilment of safety activities and safety improvement actions, establishes and allocates strategic lines of action in the safety domain, and reviews the manner in which nonconformities detected during ATM safety surveys, audits and oversight activities are addressed, adopting measures and proposals accordingly.

In terms of underlying causes or circumstances leading to levels not being achieved, the NSA assesses in the monitoring report that ROMATSA achieved the Safety targets in 2025 (Level C) for 2/5 Management Objectives namely Safety Risk Management and Safety Assurance, the rest of the safety management objectives (Safety Policy and Objectives, Safety Promotion and Safety Culture) were assessed by the NSA at Level B, as per the final reporting exercise of EoSM (1st of June 2026). Furthermore, in order to reach Level C on the remaining management objects, the ANSP has to improve elements related to: the Just Culture Policy, to incorporate the types of operational behaviours which are unacceptable by the Organization; Human Factors (HF) Expert/ Specialist with a relevant academic degree and / or professional experience recognized by a professional body; the periodic monitoring of the key suppliers (quarterly as per the EoSM guidance) and HF factors in the related agreements; hazard identification; competency of the staff and contractors who directly support air navigation service provision - which are criteria requested in the EoSM questionnaire for the required level.

The NSA notes in the monitoring report that the NSA maintains its continuous oversight of the ANSP on the elements regarding to the Safety Performance. In addition, the NSA invited the ANSP, in July 2026, for a dedicated meeting on EoSM compliance measures that should be taken and implemented by the ANSP ROMATSA in the next period, to fully comply with the EoSM requirements for a superior level (e.g. from Level B to Level C).

