## **TZ2.1. SECTION 1 -- UNIT COST**

### **TZ2.1.1. AUC VS. DUC**

In 2025, the terminal AUC was -0.1% (or -2.97 RON2022, -0.6 €2022) lower than the planned DUC. This results from the combination of lower than planned terminal costs in real terms (-2.2%, or -1.0 MRON2022, -0.2 M€2022) and lower than planned TNSUs (-2.1%). It should be noted that the actual inflation index in 2025 was +2.9 p.p. higher than planned.

### **TZ2.1.2. TERMINAL CHARGING ZONE 2 SERVICE UNITS**

The difference between actual and planned TNSUs (-2.1%) falls outside the ±2% dead-band, but does not exceed the ±10% threshold foreseen in the traffic risk sharing mechanism. The resulting loss of terminal revenues is therefore shared between the ANSP and the airspace users (see the main ANSP regulatory result).

### **TZ2.1.3. TERMINAL CHARGING ZONE 2 COSTS BY ENTITY**

Actual real terminal costs are -2.2% (-0.2 M€2022) lower than planned. This is the result of lower costs for the main ANSP, ROMATSA (-2.2%, or -0.2 M€2022) and.

### **TZ2.1.4. TERMINAL CHARGING ZONE 2 COSTS FOR THE MAIN ANSP (ROMATSA) AT CHARGING ZONE LEVEL**

Based on the additional information to the terminal reporting tables, the lower than planned terminal costs in real terms for ROMATSA in 2025 (-2.2%, or -0.2 M€2022) result from:

- Lower than planned staff costs (-2.3%),

- Lower than planned other operating costs (-2.3%),

- Consistent with the planned depreciation (+0.0%),

- Consistent with the planned cost of capital (+0.0%).

### **TZ2.1.5. ASSESSMENT OF THE ACTUAL PERFORMANCE IN THE CHARGING ZONE REPORTED BY THE NSA**

The NSA of Romania provides the following overall assessment of the actual performance in 2025 at charging zone level:

insert information from monitoring report

### **TZ2.1.6. EXPLANATION OF THE DIFFERENCES BETWEEN ACTUAL AND DETERMINED COSTS AT CHARGING ZONE LEVEL REPORTED BY THE NSA**

The NSA provides the following explanation for the differences between actual and determined costs in the charging zone:

insert information from monitoring report

### **TZ2.1.7. RECOMMENDATIONS FORMULATED BY THE NSA TO THE ANSP (ROMATSA) TO RECTIFY THE SITUATION AND ACTIONS TAKEN BY THE ANSP**

The NSA 2025 monitoring report indicates the following recommendations formulated by the NSA:

insert information from monitoring report

ROMATSA reports the implementation of the following actions:

insert information from monitoring report

### **TZ2.1.8. NOTES**

#### **TZ2.1.8.1. NOTE 1**

#### **TZ2.1.8.2. NOTE 2**

