## ERT1.2. En route capacity incentive scheme {#ert1.2.-en-route-capacity-incentive-scheme .Heading-2-ER}

The FABEC NSAs report neither a financial penalty, nor a financial bonus, for either of the en route ANSPs operating over the Netherlands, because of the 2025 performance.

Individual en route incentive targets were set for both LVNL and MUAC (global).

For LVNL, the local incentive target for en route ATFM delays, due to CRSTMP causes only, was set at 0.1 mins/flight, (with a deadband of +/- 0.02 mins).

The FABEC NSAs report an achieved CRSTMP performance, for LVNL, of 0.09 mins/flight using data from the ansperformance.eu dashboard including post ops adjustments. \[NB The attribution of original delay causes on the ansperformance.eu dashboard is unverified.\]

Although the local target was surpassed, the en route incentive capacity performance for LVNL fell inside the deadband, where no bonus is applicable.

For MUAC, the local incentive target for en route AFTM delays, due to CRSTMP causes only, was set at 0.19 mins/flight, (with a deadband of +/- 0.04 mins).

The FABEC NSAs report an achieved CRSTMP performance of 0.18 mins/flight using data from the ansperformance.eu dashboard including post ops adjustments. \[NB The attribution of original delay causes on the ansperformance.eu dashboard is unverified.\]

Although the local target was surpassed, the en route incentive capacity performance for MUAC fell inside the deadband, where no bonus is applicable.

