## 2.2.1.A. KPI #1

### Assessment of the achieved level of actual performance in the environment KPA

The Netherlands achieved the KEA target in 2025. The performance slightly improved compared to 2024.

### Has the ANSP implemented any major operational or structural changes (incl. any new fixed assets put into operation) during the calendar year impacting performance in this key performance area? Please outline the relevant changes and their estimated impact

In March 2025 PYXIS 2A was implemented, an airspace redesign in the northeast of the Netherlands, northwest of Germany and south of Denmark. The change means a dualisation of two Amsterdam in and outbound routes but more important for this PI is that it is a preparation for the establishment of a cross border military area which will be the best compromise between improving the military mission effectiveness and minimising the impact on civil traffic. The area is planned for 2026.

PYXIS resulted in shorter routes for some city pairs, but longer routes for other city pairs. Hence, the impact on HFE performance is difficult to determine and depends on the traffic demand.

### Progress on the implementation of the measures committed to in the ERNIP

\[LVNL, MUAC to confirm ERNIP status\]

### Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved

### Recommendations to the ANSP to rectify the situation

### Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why

### Follow up of the remedial measures indicated in the previous monitoring report(s)

