## 2.3.3 ATCO Planning 4

### Additional comments

The actual ATCO figures are slightly lower than assumed in the performance plan. LVNL was able to deliver the required operational performance and stayed within the target for en-route delay.

### Additional comments

The return on training investments and the impact of the additional training effort is clearly reflected in the training results and the total number of trainees in the training program. The outflow of ATCOs is higher than foreseen in the plan. The outflow figures are also impacted by the increased use of unplanned leave, such as parental leave and maternity leave.

### Description of the training process, including details on the effective failure rate and the process used to allocate newly qualified ATCOs between ACC, APP and TWR positions

The return on training investments and the impact of the additional training effort is clearly reflected in the training results and the total number of trainees in the training program.

