## 2.3.1.A. KPI #1

### Identification and analysis of the reasons and circumstances resulting in the achieved level of actual performance of the en-route ATFM delay per flight KPI

LVNL achieved the target in 2025, although performance was worse than in 2024. The main reasons were severe weather and special events. Re-routings associated with security measures for the NATO summit in June caused overdemand in adjacent centres, and the delay from their regulations was re-attributed to LVNL. Furthermore, severe thunderstroms in July and parajumping events in August caused a decrease in sector capacity, and hence significant delays.

### Description of the adjustments to the capacity plan included in adopted performance plan

For LVNL, the NOP 2025-2029 shows no bottleneck expected for Amsterdam ACC.

According to the Network Operations Plan (NOP) 2025-2029 no capacity bottlenecks were expected for Amsterdam ACC. Capacity can still be increased until the traffic demand reaches the 2019 levels. As such, it is consistent with the required performance and no adjustments are needed.

### Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved

### Recommendations to the ANSP to rectify the situation

### Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why

LVNL: Target met --- no remedial measures required.

### Follow up of the remedial measures indicated in the previous monitoring report(s)

