## 2.3.3 ATCO Planning 1

### Additional comments

It is well understood that ATCO hiring and assignment is one of the major driver for current capacity and staffing issues solving. Nevertheless, DSNA considers that they cannot be considered as a commitment due to the high level of uncertainties related to such ATCO recruitment plans management. These figures, even when provided on annual basis, can only be regarded as snapshot information, i.e. a situation at one point in time which does not guarantee a realistic view throughout the entire duration of RP4: technically the ATCO planning is and will always be subject to change. In addition, for ANSPs having more than one national ACC, ATCO hiring plan are managed at ANSP level but changes in traffic volumes or flows and volatility or local human ressources factors can influence the assignment to different ACCs and the details of the planned evolution of ATCO numbers can also be socially sensitive.

There are many factors with a high level of uncertainty that have an impact on the ATCO planning: first of all there are classical uncertainty factors of general staff planning like the actual rate of retirement, the absence rate of employees, as well as maternity and parent leave. Moreover, ATCOs mobility has become a severe issue recently, leading to high rate of unforeseen leaves.

Another factor which cannot be significantly mitigated further impacting the availability of ATCOs is the number of suitable applicants, the failure rate of the theoretical training at the academies and the success rate during the on-the-job training phases of trainees.

The final retirement age is set by law, but ANSPs can only assume a certain amount of people opting out/in. It is common culture now that companies offer varying working hours to enable employees to adjust their work to different phases of their life. Again, ANSPs can only assume a certain amount of people opting in/out. On top of all that, future social agreements will significantly determine the ATCO availability per person and by that the total available FTE.

Any benchmarking should also consider that the demographic situation can also evolve and might require to hire to an extent not aligned to the traffic demand. FTE refers to a different amount of working time per year/ANSP and are not harmonised among ANSPs but are subject to national laws and labour regulations.

It should also be noted that some social agreements regarding numbers of additional ATCO to be recruited during RP4 and working conditions (salaries, extra hours, rostering) could be renegociated after the submission of this FABEC performance plan. Outcomes of such negotiations will have an impact on those values.

In addition, it should be noted that DSNA and the French NSA are currently working on an update of the methodology used to compute these ATCO in OPS FTE values for RP4 monitoring, especially ATCO in OPS at APP/TWR and on other duties, which individual monitoring is quite new and still needs to be finetuned and harmonized.

DSNA ongoing plan is to reduce and consolidate the number of APP, reducing the number of ATCO in OPS at APP and priotize ACC assignment for ATCOs during RP4.

### Additional comments

As planned, during RP3 and along RP4, DSNA strategy is to recruit and train as much ATCO as possible fo fill the staffing gap at ACCs and also to consolidate and reduce the number of APP centres in order to reduce ATCO in OPS at APP and reassign them to ACCs where and when possible.

2025 ATCO in OPS values are increasing.

### Description of the training process, including details on the effective failure rate and the process used to allocate newly qualified ATCOs between ACC, APP and TWR positions

The training process is organized as follows :

- 2 years for the initial training,

- 3 years in average at the unit training (with an objectif to come to 2 years unit training in 2027).

During the two years initial training, ATCOs will get Tower, Approach and Area Licenseing for both procedural and radar qualifications. (ADC, APP, APS, ACP, ACS). They are then liable to work in every control center DSNA has in charge.

Initial Training is sub-contracted to a Training Organisation called ENAC in Toulouse (French school). DSNA takes an important part in this initial Training since ATCOs from DSNA (60 in 2024) are dedicated to work as instructors for the school and DSNA is also participated in handling the examination for ratings.

Once they finish school and initial training, ATCOs are dedicated to one ATC unit and 90% of them go to ACCs or biggest Airport units (Roissy, Orly, Nice, \...), when 10% go to units with human resource shortage.

In Airports units, when ATCOs are qualified in TOWER positions, they work on their own on these sectors half time while still on unit training for approach, before having their full unit training enabling them to work both approach and tower.

The DSNA average failure rate is around 8% amongst the population who started inital training till full unit training. It is around 9% if only unit training is considered.

Since ATCOs leave ENAC school with all ratings on their licence, DSNA offers to people failing their unit training in ACCs or biggest airports a chance to qualify in regional airport.

