## TRM1.1. Terminal and airport ANS ATFM arrival delay per flight (KPI#2) {#trm1.1.-terminal-and-airport-ans-atfm-arrival-delay-per-flight-kpi2 .Heading-2-TZ}

Average ATFM arrival delay in France was 1.02 min/arr in 2025, the first year of RP4. The **performance has worsened compared to 2024**, last year of RP3, when there were 0.63 min/arr.

The national average is primarily driven by delays at Nice airport, which suffered 4.12 min/arr compared to 1.71 min/arr in 2024, an increase over 140% due to staffing and capacity-demand balancing issues. Nice presents the third highest ATFM Arrival delay across RP4 airports.

Other main airports presented results close to \~1 min/arr: Paris -- Charles de Gaulle (0.93 min/arr compared to 0.32 min/arr in 2024), Paris-Orly (0.90 compared to 1.38 min/arr in 2024), Marseille (1.36 min/arr compared to 0.50 min/arr in 2024) and Toulouse (0.78 min/arr compared to 0.39 min/arr in 2024).

Lyon showed almost no delay (0.01 min/arr) and the average for the remaining 48 airports was 0.51 min/arr.

The average for RP4 airports subject to monitoring of ATFM Arrival delay across Member States in 2025 was 0.97 min/arr.

