## 2.3.2.C. PI #3

### Please provide background information on the actual performance: - If performance improved compared to previous years, please describe the measures that were implemented (if any), - If performance deteriorated compared to previous years, please explain the reasons which lead to the deterioration, and describe the improvement measures which are planned to improve performance. How does the NSA intend on monitoring their effectiveness on performance

Regarding ATC part of the delays and related corrective measures, please do refer to 2.3.1.B. KPI#2.

The values reflect the difficulties encountered in LFMN last year mainly due to staffing issues.

LFPG (-1,08) and LFPO (-2,55) improved.

### If the data at airport level are not available, please explain the reasons why data is missing and describe the measures planned to resolve the situation

All cause departure delay is very generic and ATFM delay is only a small contributor. Departure delay can be generated by ATFM en-route delay (not only local airport, but the complete Network) but also reactionary and turnaround delay, technical issues with the aircraft, airport operations, problems with passengers and or luggage, etc. In other words, it is not always possible to address a specific reason as this delay is quite generic. It would be more interesting to check the overall ANSP share against the share of the other network stakeholders (airports and AOs) and also show the weather induced subshare.

