## 2.2.2.D. PI #4

### What initiatives were implemented or are planned that will improve this PI and how does the NSA intend on monitoring their effectiveness on performance?

The 2025 values show a deterioration for LFMN and LFPG linked to the traffic increase and volatility, the overall DSNA ATC capacity performance but also impacted by works on the airport side.

### If the data at airport level are not available, please explain the reasons why data is missing and describe the measures planned to resolve the situation

Regarding LFML (Marseille airport), te Airport data flow (APDF) has been implemented 2019 but with some technical issues regarding block data. Beginning 2020, when within the framework of a project on implementing A-CDM concept at Marseille airport, additional exchanges took place regarding lacking information (AOBT/AIBT) and how to provide it through the airport data flow but it could not be implemented during the covid 19 phase.

Eurocontrol has contacted Marseille airport authorities to tackle the issue. The French NSA will support Eurocontrol and Marseille airport in order to identify remaining issues and implement the on block data provision as soon as possible.

Ongoing work with good progress has been made for the implementation of ECRA at LFML.

