## **TZ1.1. SECTION 1 -- UNIT COST**

### **TZ1.1.1. AUC VS. DUC**

In 2025, the terminal AUC was +3.8% (or +3.78 €2022) higher than the planned DUC. This results from the combination of lower than planned TNSUs (-3.9%) and slightly lower than planned terminal costs in real terms (-0.2%, or -0.1 M€2022).

### **TZ1.1.2. TERMINAL CHARGING ZONE 1 SERVICE UNITS**

The difference between actual and planned TNSUs (-3.9%) falls outside the ±2% dead-band, but does not exceed the ±10% threshold foreseen in the traffic risk sharing mechanism. The resulting loss of terminal revenues is therefore shared between the ANSP and the airspace users (see the main ANSP regulatory result).

### **TZ1.1.3. TERMINAL CHARGING ZONE 1 COSTS BY ENTITY**

Actual real terminal costs are -0.2% (-0.1 M€2022) lower than planned. This is the result of lower costs for the MET service provider (-5.5%, or -0.2 M€2022) and the NSA (-19.3%, or -0.1 M€2022) and slightly higher costs for the main ANSP, DSNA (+0.2%, or +0.1 M€2022).

### **TZ1.1.4. TERMINAL CHARGING ZONE 1 COSTS FOR THE MAIN ANSP (DSNA) AT CHARGING ZONE LEVEL**

Based on the additional information to the terminal reporting tables, the slightly higher than planned terminal costs in real terms for DSNA in 2025 (+0.2%, or +0.1 M€2022) result from:

- Significantly higher than planned staff costs (+5.3%), mainly due to an increase in staff wages in line with the new social agreement as well as higher pension costs due to an increase in the national index of CAS Pension (state-managed pension scheme applicable to DSNA) as decided by the French government in 2025.

- Significantly lower than planned other operating costs (-7.4%), due to delays in the recognition of some operational expenses related to the implementation of projects in CDG and Orly (new ATC systems).

- Significantly higher than planned depreciation (+5.8%), due to higher cost of investments and catching up with delayed RP3 amortization.

- Significantly lower than planned cost of capital (-20.6%), due to lower NBV of fixed assets (-25.4%) combined with a lower than planned weighted average cost of capital rate, mainly resulting from lower average interest on debt.

- The deduction of costs for VFR exempted flights which were not included in the determined costs.

### **TZ1.1.5. ASSESSMENT OF THE ACTUAL PERFORMANCE IN THE CHARGING ZONE REPORTED BY THE NSA**

The NSA of France provides the following overall assessment of the actual performance in 2025 at charging zone level:

*"Actual costs are in line with determined costs (only -0.2% at 2022 prices). Actual unit cost is slightly higher than the target (+3.8% at 2022 prices)."*

### **TZ1.1.6. EXPLANATION OF THE DIFFERENCES BETWEEN ACTUAL AND DETERMINED COSTS AT CHARGING ZONE LEVEL REPORTED BY THE NSA**

No information was provided in the NSA 2025 Monitoring Report.

### **TZ1.1.7. RECOMMENDATIONS FORMULATED BY THE NSA TO THE ANSP (DSNA) TO RECTIFY THE SITUATION AND ACTIONS TAKEN BY THE ANSP**

The NSA indicates that:

"*No specific recommendation is made by the French NSA at this stage regarding costs, as actual costs are perfectly in line with determined costs for 2025.*

*Regarding the actual unit costs, 2025 achievement is slightly higher than the target, but this is due to the difference between the actual traffic compared to the STATFOR forecast (-3,9%). The domestic traffic is recovering at a slower pace than expected, compared to international and overflights."*

### **TZ1.1.8. NOTES**

#### **TZ1.1.8.1. NOTE 1**

#### **TZ1.1.8.2. NOTE 2**

