## **ER1.2. SECTION 2 - ACTUAL UNIT COSTS INCURRED BY THE USERS**

### **ER1.2.1. FOCUS ON EN ROUTE AUCU MONITORING AT CHARGING ZONE LEVEL**

The actual en route unit cost incurred by airspace users (AUCU) in respect of activities performed in 2025 (1 579.74 CZK or 64.06 €) is -0.6% lower than the nominal DUC (1 589.13 CZK or 64.44 €) which includes DUC initially charged: 1 590.60 CZK (or 64.50 € ), and DUC to be charged retroactively: -1.47 CZK (or -0.06 € ). The difference between the AUCU and the nominal DUC (-9.40 CZK/SU or -0.38 €/SU) is due to:

- the positive inflation adjustment resulting from higher than planned inflation (+9.33 CZK/SU or +0.38 €/SU);

- the impact of adjustments resulting from the costs exempted from cost sharing mechanism (-22.35 CZK/SU or -0.91 €/SU). It should be noted that the NSA of the Czech Republic decided not to charge the difference in pension costs for 2025 to the airspace users (some +1.2 MCZK, corresponding to -0.48 CZK/SU or -0.02 €/SU).

- the addition of the traffic adjustment (+0.06 CZK/SU or +0.01 €/SU) for the costs not subject to traffic risk sharing;

- the impact of financial incentives (+7.16 CZK/SU or +0.29 €/SU);

- the deduction of other revenues (-3.39 CZK/SU or -0.14 €/SU); and,

- the application of a lower unit rate as foreseen in Art. 29(6) in year 2025 (-0.21 CZK/SU or -0.01 €/SU).

The share of the regulatory result (see next sub-section) in the AUCU (before the deduction of other revenues) is 5.5%.

Costs exempt from cost sharing for 2025 presented here are based on preliminary figures and remain subject to revision pending the receipt of the NSA Reports on the verification of cost sharing due by 1 September 2026. Any changes may affect the analysis of Actual Costs for Users and the Regulatory Results.

### **ER1.2.2. INITIATIVES IMPLEMENTED OR PLANNED THAT WILL IMPROVE THIS PI REPORTED BY THE NSA**

No information on such initiatives was provided in the NSA 2025 Monitoring Report.

### **ER1.2.3. NOTES** 

#### **ER1.2.3.1. NOTE 1**

#### **ER1.2.3.1. NOTE 2**

