## **ER1.1. SECTION 1 -- UNIT COST**

### **ER1.1.1. AUC VS. DUC**

In 2025, the en route AUC was -0.8% (or -11.15 CZK2022, -0.45 €2022) lower than the planned DUC. This results from the combination of slightly lower than planned en route costs in real terms (-0.8%, or -28.9 MCZK2022, -1.2 M€2022) and TSUs that are in line with the plan.

### **ER1.1.2. EN ROUTE SERVICE UNITS**

The difference between actual and planned TSUs (-0.04%) falls inside the ±2% dead-band. Hence, the loss of en route revenues is borne by the ANSPs.

### **ER1.1.3. EN ROUTE COSTS BY ENTITY**

Actual real en route costs are -0.8% (-1.2 M€2022) lower than planned. This is the result of lower costs for the main ANSP, ANS CR (-1.0%, or -1.3 M€2022) and slightly higher costs for the NSA/EUROCONTROL (+0.3%) and the MET service provider (+2.8%, or +0.1 M€2022).

### **ER1.1.4. EN ROUTE COSTS FOR THE MAIN ANSP (ANS CR) AT CHARGING ZONE LEVEL**

Based on the additional information to the en route reporting tables, the slightly lower than planned en route costs in real terms for ANS CR in 2025 (-1.0%, or -1.3 M€2022) result from:

- Higher than planned staff costs (+1.3%), mainly due to the high inflation experienced in 2022 and 2023 feeding through into employee compensation.

- Other operating costs consistent with the plan.

- Significantly lower than planned depreciation (-11.7%), mainly because some planned system upgrades were postponed.

- Significantly higher than planned cost of capital (+8.3%), mainly due to a higher proportion of equity financing, with equity being much more expensive than debt.

- Significantly higher than planned deduction for VFR exempted flights (+23.6%).

### **ER1.1.5. ASSESSMENT OF THE ACTUAL PERFORMANCE IN THE CHARGING ZONE REPORTED BY THE NSA**

The NSA of Czech Republic provides the following overall assessment of the actual performance in 2025 at charging zone level:

"*The actual DUC was slightly lower than determined and the target was met.*"

### **ER1.1.6. EXPLANATION OF THE DIFFERENCES BETWEEN ACTUAL AND DETERMINED COSTS AT CHARGING ZONE LEVEL REPORTED BY THE NSA**

The NSA provides the following explanation for the differences between actual and determined costs in the charging zone:

"*The lower actual DUC is result of situation where lower depreciation (cca 11 %) was not offset by an increase in personnel (cca 1,9 %) or other costs. On the top of that the inflation was higher than predicted.*"

### **ER1.1.7. RECOMMENDATIONS FORMULATED BY THE NSA TO THE ANSP (ANS CR) TO RECTIFY THE SITUATION AND ACTIONS TAKEN BY THE ANSP**

The NSA 2025 monitoring report indicates the following recommendations formulated by the NSA:

"*To maintain the efforts keeping ANSP in healthy financial condition being able to cope the current challenges (not restoring traffic as expected and the war in Ukraine). ANSPs should continue its cost-cutting measures while not undermining future capacity and keep the achieved level of Safety.*"

ANS CR reports the implementation of the following actions:

"*ANS CR continues to cut costs while maintaining its ability to serve a larger volume of traffic. It is focusing on the scalability of its operations, which we consider essential in the current geopolitical situation. CHMI is a state-funded organization whose ability to respond flexibly is limited and its cost development depends mainly on government decision.*"

### **ER1.1.8. NOTES**

#### **ER1.1.8.1. NOTE 1**

#### **ER1.1.8.2. NOTE 2**

