## **2.3.1.B. KPI #2**

### **Identification and analysis of the reasons and circumstances resulting in the achieved level of actual performance of the arrival ATFM delay per flight KPI**

The failure to meet the target is due solely to a few days throughout the year when, due to weather conditions, significant delays were recorded at LKPR. Since this involved only a few days, it does not make economic sense to build additional capacity to cover these fluctuations; therefore, no corrective measures have been established.

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

The main reason for the delay was the weather occorued within a few days. The main reason was the bad weather, which lasted only a few days.

### **Recommendations to the ANSP to rectify the situation**

Since this involved only a few days, it does not make economic sense to build additional capacity to cover these fluctuations; therefore, no corrective measures have been established.

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

As mentioned above, the failure to meet the target was due to several days of bad weather. From an economic perspective, it does not make sense to build additional capacity that will only be used for a few days a year; therefore, no remedial measures have been adopted or proposed.

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

N/A the target was met in the previous reporting cycle.

