## **ER1.3.  SECTION 3 -- REGULATORY RESULT**

### **ER1.3.1. ANS CR NET GAIN/LOSS ON ACTIVITY IN THE CZECH REPUBLIC EN ROUTE CHARGING ZONE IN 2025**

ANS CR reported a net loss of -0.6 M€, as a combination of a loss of -1.2 M€ arising from the cost sharing mechanism, with a loss of -0.1 M€ arising from the traffic risk sharing mechanism and a gain of +0.7 M€ relating to financial incentives.

### **ER1.3.2. ANS CR OVERALL REGULATORY RESULT (RR) FOR THE EN ROUTE ACTIVITY**

Ex-post, the overall RR, taking into account the net loss from the en route activity mentioned above (-0.6 M€) and the actual RoE (+9.2 M€), amounts to +8.7 M€ (6.1% of the en route revenues). The resulting ex-post rate of return on equity is 7.7%, which is lower than the 8.2% planned in the PP (see also Note 1 below).

### **ER1.3.3. NOTES** 

#### **ER1.3.3.1. NOTE 1**

The ex-post RR does not take into account the application of the lower unit rate as per Art. 29.6 (loss in revenues amounts to -0.5 MCZK or less than -0.1 M€ for 2025).

#### **ER1.3.3.2. NOTE 2**

# **TZ1. TERMINAL CHARGING ZONE - CZECH REPUBLIC**

