## **2.3.2.C. PI #3**

### **Please provide background information on the actual performance: - If performance improved compared to previous years, please describe the measures that were implemented (if any), - If performance deteriorated compared to previous years, please explain the reasons which lead to the deterioration, and describe the improvement measures which are planned to improve performance. How does the NSA intend on monitoring their effectiveness on performance**

The main causes of the delay are: En-route delay - 16,83 %; Airline delay - 14,87 %; Airport delay - 6,94 %; Weather - 5,19 %; Security & Immigration - 1,42 % and Reactionary - 54,78 %. The PI is better than in the previous years.

In the 2025 and 2026 season, a major reconstruction of the main RWY is underway and operational measures are being taken to improve the situation, which NSA closely monitors in regular meetings with the slot coordinator and with the airport operator. The measures described in last year\'s report will continue to be further developed by the airport operator.

### **If the data at airport level are not available, please explain the reasons why data is missing and describe the measures planned to resolve the situation**

N/A

