## **2.3.1.A. KPI #1**

### **Identification and analysis of the reasons and circumstances resulting in the achieved level of actual performance of the en-route ATFM delay per flight KPI**

Completion of the airspace optimization project - partial changes to the ACC Praha sectorization - increas of capacity

Ongoing training of air traffic controllers and changes in training to achieve greater success rate

Continues development of the main ATM system TopSky,

Traffic volumes were in line with expectations and the performance plan, and there were no exceptional circumstances

Weather phenomena was rather favourable, including neighbouring countries.

### **Description of the adjustments to the capacity plan included in adopted performance plan**

N/A

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

N/A

### **Recommendations to the ANSP to rectify the situation**

N/A

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

N/A

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

In 2024, this KPI target was slightly exceeded by 0.02. The higher delay was caused by a difference in the methodology used by ANS CR compared to the EUROCONTROL standard (ANS CR incorrectly allocated part of the en-route delay to the terminal segment). No corrective measures were necessary.

