## **TZ1.3. SECTION 3 -- REGULATORY RESULT**

### **TZ1.3.1. ANS CR NET GAIN/LOSS ON ACTIVITY IN THE CZECH REPUBLIC TERMINAL CHARGING ZONE IN 2025**

ANS CR reported a net gain of +0.2 M€, as a combination of a loss of -0.2 M€ arising from the cost sharing mechanism, with a gain of +0.6 M€ arising from the traffic risk sharing mechanism and a loss of -0.2 M€ relating to financial incentives.

### **TZ1.3.2. ANS CR OVERALL REGULATORY RESULT (RR) ON ACTIVITY IN THE TERMINAL CHARGING ZONE** 

Ex-post, the overall RR, taking into account the net gain from the terminal activity mentioned above (+0.2 M€) and the actual RoE (+1.1 M€), amounts to +1.3 M€ (5.2% of the terminal revenues). The resulting ex-post rate of return on equity is 9.7%, which is higher than the 8.2% planned in the PP (see also Note 1 below).

### **TZ1.3.3. NOTES**

#### **TZ1.3.3.1. NOTE 1**

The ex-post RR does not take into account the application of the lower terminal unit rate as per Art. 29.6 (loss of revenue amounts to -7.2 M€ for 2025).

#### **TZ1.3.3.2. NOTE 2**
