## 2.2.2.I. PI #9

### What initiatives were implemented or are planned that will improve this PI and how does the NSA intend on monitoring their effectiveness on performance?

Netherlands:

• Implementation of the PYXIS 2A project entitling a dualisation of 2 Amsterdam in and outbound routes. More important for this PI is that it is a preparation for the establishment of a cross-border military area which will be the best compromise to improve the military mission effectiveness with a minimum impact on civil traffic. The area is planned for 2026.

• Preparation for the move of the JOJO Air-to-Air Refuelling track to the LENA track (implemented in February 2026), allowing unrestricted climbs and, important for this PI, more direct routings while supporting effective military operations.

Belgium/Luxembourg :

• The implementation of the straightening of the sector boundaries between MUAC and Reims, as planned, in January 2025.

• The implementation of cross-border FRA with Reims ACC West Sectors.

Germany:

• Efforts for the preparation of XMAN operations for EDDF (implemented in March 2026).

• Implementation of the PYXIS 2A project entitling a dualisation of 2 routes. More important for this PI is that it is a preparation for the establishment of a cross-border military area which will be the best compromise to improve the military mission effectiveness with a minimum impact on civil traffic. The area is planned for 2026.

• Preparation for the move of the JOJO Air-to-Air Refuelling track to the LENA track (implemented in February 2026), allowing unrestricted climbs and, important for this PI, more direct routings while supporting effective military operations.

