## SAF1.1. Effectiveness of Safety Management (EoSM) (KPI#1)

In 2025, Skeyes did not meet the planned maturity levels set out in its performance plan for any of the five components of the EoSM. Skeyes scored A for all the safety management objectives and needs significant improvement for the EoSM in order to reach the targets by the end of RP4.

As described in the monitoring report, Skeyes has not achieved the expected intermediate targets. In terms of main measures put in place to achieve the safety performance targets, the report defines the following elements:

- Safety risk management: Human factors integration, revision of internal and external interfaces.

- Safety assurance: updated audit cycle to ensure sustained compliance in RP4.

- Safety culture development: conduct of regular safety culture assessment across the organisation.

- Benchmarking and peer learning.

- Monitoring and corrective actions: Corrective action plans will be launched whenever deviations from the safety targets are observed.

As the planned levels were not achieved, Belgium explains in the monitoring report the reasons leading to this situation; Skeyes is not always able to demonstrate compliance with the guidance provided in the EoSM questionnaire. In addition, Skeyes did not make use of the time allotted to provide and update the justification and evidence required to meet the intermediate targets.

In terms of remedial actions implemented or planned, as described in the monitoring report, a compliance monitoring plan has been established by Skeyes, with compliance monitoring audits planned. Internal SMS audit has been performed in 2025, CAP will be implemented to correct the findings.

The NSA describes in the monitoring report that the intended measures to be undertaken to remedy the situation are continuous oversight and possible enforcement measures.

