## 2.3.1.A. KPI #1

### Identification and analysis of the reasons and circumstances resulting in the achieved level of actual performance of the en-route ATFM delay per flight KPI

skeyes achieved the target set with a yearly performance of 0.08 minute per flight. This performance is similar to 2024 (0.08 min per flight), despite a 4.4% increase in traffic, demonstrating that skeyes has been able to demonstrate greater capacity.

### Description of the adjustments to the capacity plan included in adopted performance plan

According to the latest Network Operations Plan (NOP 2026), no capacity bottleneck is expected for EBBUACC. The level of performance achieved in 2025 shows that capacity should be sufficient in 2026.

### Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved

### Recommendations to the ANSP to rectify the situation

### Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why

According to the latest Network Operations Plan (NOP 2026), no capacity bottleneck is expected for EBBUACC. The level of performance achieved in 2025 shows that capacity should be sufficient in 2026.

### Follow up of the remedial measures indicated in the previous monitoring report(s)

