### **TZ1.1. SECTION 1 -- UNIT COSTTZ1.1.1. AUC VS. DUC**

In 2025, the terminal AUC was -2.2% (or -5.77 €2022) lower than the planned DUC. This results from the combination of lower than planned terminal costs in real terms (-1.7%, or -0.7 M€2022) and slightly higher than planned TNSUs (+0.4%).

### **TZ1.1.2. TERMINAL SERVICE UNITS**

The difference between actual and planned TNSUs (+0.4%) falls inside the ±2% dead-band. Hence, the gain of additional terminal revenues is kept by the ANSPs.

### **TZ1.1.3. TERMINAL COSTS BY ENTITY**

Actual real terminal costs are -1.7% (-0.7 M€2022) lower than planned. This is the result of lower costs for the main ANSP, skeyes (-1.8%, or -0.7 M€2022) and slightly higher costs for the NSA (+1.7%, or +0.01 M€2022).

### **TZ1.1.4. TERMINAL COSTS FOR THE MAIN ANSP (SKEYES) AT CHARGING ZONE LEVEL**

Based on the additional information to the terminal reporting tables, the slightly lower than planned terminal costs in real terms for skeyes in 2025 (-1.8%, or -0.7 M€2022) result from:

- Slightly higher than planned staff costs (+1.7%).

- Significantly lower than planned other operating costs (-13.7%), mainly due to lower than planned maintenance and external support costs (including lower costs for IT strategy, HR business partner support, as well as risk and internal control external support).

- Slightly lower than planned depreciation (-0.9%).

- Significantly lower than planned cost of capital (-6.8%), mainly due to a lower than planned asset base.

### **TZ1.1.5. ASSESSMENT OF THE ACTUAL PERFORMANCE IN THE CHARGING ZONE REPORTED BY THE NSA**

The NSA of Belgium provides the following overall assessment of the actual performance in 2025 at charging zone level:

*"Overall, performance is slightly above budget on staff costs but largely offset by significant underspending in other operating expenses, resulting in an overall favourable cost position. Depreciation is broadly on track, while lower capital costs further contribute to a positive variance versus budget."*

### **TZ1.1.6. EXPLANATION OF THE DIFFERENCES BETWEEN ACTUAL AND DETERMINED COSTS AT CHARGING ZONE LEVEL REPORTED BY THE NSA**

The NSA provides the following explanation for the differences between actual and determined costs in the charging zone:

*The staff costs are 1% above the budget of 2025.*

*Other operating costs represent 86% of the budget foreseen for 2025. The underspent is driven by lower maintenance and lower external support costs versus budget (lower costs for IT strategy, HR business partner and risk & internal control external support costs).*

*The depreciation costs remain slightly below the budget: 99% of planned costs have materialized.*

*The cost of capital is lower than foreseen in the budget, mainly due to a lower fixed asset base."*

### **TZ1.1.7. RECOMMENDATIONS FORMULATED BY THE NSA TO THE ANSP (SKEYES) TO RECTIFY THE SITUATION AND ACTIONS TAKEN BY THE ANSP**

The NSA 2025 monitoring report indicates the following recommendations formulated by the NSA:

*"Lack of time between the delivery of the data from the ANSPs and the deadline for submission did not allow an analysis of the situation."*

No information was provided by skeyes in the NSA 2025 Monitoring Report.

### **TZ1.1.8. NOTES**

#### **TZ1.1.8.1. NOTE 1**

#### **TZ1.1.8.2. NOTE 2**

