## 2.2.1.A. KPI #1

### Assessment of the achieved level of actual performance in the environment KPA

Free Route Airspace (FRA) is considered the largest enabler for improving KEA. However, upper airspace in Belgium (above FL245) is delegated to MUAC and is therefore out of scope for skeyes. Additionally as KEA is a horizontal en-route flight efficiency indicator, an area of 40 nm around the origin & destination airport is excluded from the calculation. This leaves only little room for improvement within skeyes airspace.

### Has the ANSP implemented any major operational or structural changes (incl. any new fixed assets put into operation) during the calendar year impacting performance in this key performance area? Please outline the relevant changes and their estimated impact

cf. comment above - therefore no stuctural or operational change has been planned by skeyes.

### Progress on the implementation of the measures committed to in the ERNIP

skeyes: Over the past years AUP and UUP procedures have been updated in line with ERNIP Part 3, ensuring that any airspace made available is immediately published to NM through a UUP.

### Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved

### Recommendations to the ANSP to rectify the situation

### Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why

### Follow up of the remedial measures indicated in the previous monitoring report(s)

