## **TZ1.2. SECTION 2 -- ACTUAL UNIT COST INCURRED BY THE USERS**

### **TZ1.2.1. FOCUS ON TERMINAL AUCU MONITORING AT CHARGING ZONE LEVEL**

The actual terminal unit cost incurred by airspace users (AUCU) in respect of activities performed in 2025 (215.63 €) is -25.1% lower than the nominal DUC (287.89 €), which includes DUC initially charged: 298.82 €, and DUC to be charged retroactively: -10.93 €. The difference between the AUCU and the DUC (-72.26 €/SU) is due to:

- the negative inflation adjustment resulting from lower than planned inflation (-0.50 €/SU);

- the impact of adjustments resulting from the costs exempted from cost sharing mechanism (-0.94 €/SU);

- the deduction of the traffic adjustment (-0.09 €/SU) for the costs not subject to traffic risk sharing;

- the impact of financial incentives (+0.35 €/SU);

- the impact of the modulation of charges (-2.30 €/SU); and

- the deduction of other revenues (-68.78 €/SU), corresponding to financing provided by the Belgian State in accordance with the fourth management contract.

The share of the regulatory result (see next sub-section) in the AUCU (before the deduction of other revenues) is 4.9%.

Costs exempt from cost sharing for 2025 presented here are based on preliminary figures and remain subject to revision pending the receipt of the NSA Reports on the verification of cost sharing due by 1 September 2026. Any changes may affect the analysis of Actual Costs for Users and the Regulatory Results.

### **TZ1.2.2. INITIATIVES IMPLEMENTED OR PLANNED THAT WILL IMPROVE THIS PI REPORTED BY THE NSA**

The NSA of Belgium provides the following information regarding the initiatives:

*"Lack of time between the delivery of the data from the ANSPs and the deadline for submission did not allow an analysis of the situation"*

### **TZ1.2.3. NOTES** 

#### **TZ1.2.3.1. NOTE 1**

#### **TZ1.2.3.1. NOTE 2**

