## **ER1.3.  SECTION 3 -- REGULATORY RESULT**

### **ER1.3.1. SKEYES NET GAIN/LOSS ON ACTIVITY IN THE BELGIUM-LUXEMBOURG EN ROUTE CHARGING ZONE IN 2025**

Skeyes reported a net gain of +13.3 M€, as a combination of a gain of +10.8 M€ arising from the cost sharing mechanism, with a gain of +2.5 M€ arising from the traffic risk sharing mechanism.

### **ER1.3.2. SKEYES OVERALL REGULATORY RESULT (RR) FOR THE EN ROUTE ACTIVITY**

Ex-post, the overall RR, taking into account the net gain from the en route activity mentioned above (+13.3 M€) and the actual RoE (+4.3 M€), amounts to +17.5 M€ (10.0% of the en route revenues). The resulting ex-post rate of return on equity is 33.3%, which is much higher than the 8.1% planned in the PP. See also Note 1 below.

### **ER1.3.3. NOTES** 

#### **ER1.3.3.1. NOTE 1**

The ex-post RR for en-route does not take into account the application of the lower unit rate as per Art. 29.6 (loss of revenue amounts to -3.3M€ for 2025).

#### **ER1.3.3.2. NOTE 2**

# **TZ1. TERMINAL CHARGING ZONE - BELGIUM BRUSSELS**

