## PRB1.6. Cost-efficiency {#prb1.6.-cost-efficiency .Heading-2-ER}

- The en route 2025 actual unit cost of Belgium-Luxembourg was 91.28€2022, -5.9% lower than the determined unit cost (97.00€2022). The terminal 2025 actual unit cost of Belgium was 258.69€2022, -2.2% lower than the determined unit cost (264.46€2022).

- The en route 2025 actual service units (2.73M) were +1.5% higher than the determined service units (2.69M).

- The en route 2025 actual total costs were -11.7M€2022 (-4.5%) lower than determined with all cost categories registering lower-than-planned costs, except staff costs. The gap is mainly due to lower other operating costs of Skeyes (-9.2M€2022, or -27.6%). The NSA attributed this decrease to lower maintenance and external support costs than planned.

- A deviation from the criteria to achieve capacity targets was considered justified for Belgium-Luxembourg. Actual costs for the measures necessary to achieve those targets were lower than determined (-1.8M€2022, or -9.7%), mainly due to lower depreciation (-1.8M€2022, or -83.5%) than planned.

- Skeyes spent 19.2M€2022 in 2025 related to costs of investments for both en route and terminal charging zones, -5.4% less than determined (20.3M€2022). According to the NSA, this reduction is mainly due to project delays and postponements, as well as lower costs for IT and data equipment.

- The en route actual unit cost incurred by users in 2025 was 102.11€ (-3.2% below the 2025 DUC). The terminal actual unit cost incurred by users was 215.63€ (-25.1% below the 2025 DUC) for Belgium and 275.46€ (-14.9% below the 2025 DUC) for Luxembourg. The difference between the AUCU and the DUC for the terminal charging zones is mainly driven by other revenues.

- The en route regulatory result for skeyes amounted to +17.5M€, or 10.0% of the 2025 revenue. This may indicate that the airspace users are charged for costs which have not materialised in 2025.

