## **TZ1.3. SECTION 3 -- REGULATORY RESULT**

### **TZ1.3.1. AVINOR NET GAIN/LOSS ON ACTIVITY IN THE NORWAY TERMINAL CHARGING ZONE IN 2025**

Avinor reported a net gain of +1.5 M€, as a combination of a gain of +1.6 M€ arising from the cost sharing mechanism, with a loss of -0.2 M€ arising from the traffic risk sharing mechanism.

### **TZ1.3.2. AVINOR OVERALL REGULATORY RESULT (RR) ON ACTIVITY IN THE TERMINAL CHARGING ZONE** 

Ex-post, the overall RR, taking into account the net gain from the terminal activity mentioned above (+1.5 M€) and the actual RoE (+2.3 M€), amounts to +3.8 M€ (7.9% of the terminal revenues). The resulting ex-post rate of return on equity is 19.4%, which is higher than the 11.8% planned in the PP.

### **TZ1.3.3. NOTES**

#### **TZ1.3.3.1. NOTE 1**

Ex-ante and ex-post RoE are computed based on the notional gearing of 60% debt used in the RP4 PP. The actual gearing of Avinor for 2025 should be reported as it impacts the overall regulatory result for that year.

#### **TZ1.3.3.2. NOTE 2**
