## **2.3.3 ATCO Planning 1**

### **Additional comments**

ATCOs on other duties have increast. Mainly ATCOs in training

### **Additional comments**

The reduction or increase in ATCOs are reported as the net effect.

### **Description of the training process, including details on the effective failure rate and the process used to allocate newly qualified ATCOs between ACC, APP and TWR positions**

Avinor is not licensed to provide the AB-INITO part for initial training for ATCO students, this is provided by an external provider with and Reg.(EU) 2015/340 approval. The training starts in September and finishes in June the following year.

On return to Norway the students undertake a 3-week transition training course in preparation for working in Norwegian airspace. Then they move on to unit training. The unit training consists of four phases with a PRE-OJT of 2 months followed by three OJT-phases of 1.5 months, 4.5 months and 4 months respectively. Average failure rate is 20% over the last 12 years.

Allocation between units, positions and ratings is done in accordance with the agreement between Avinor and the ATCO union. (Seniority and a 3-year period bound to Avinor ANS after the ATCO license is achieved). Included in the number of trainees planned to enter the training program(s) during the year are the trainees starting the first phase of the training (initial training) without any previous qualifications and the trainees starting their on-the-job training (unit training). The number of trainees is increased in 2024 and 2025 in order to meet an aging demographic.

