## PRB1.4. Environment {#prb1.4.-environment .Heading-2-ER}

- Norway registered a KEA performance of 1.60%. Their target of 1.28% was not achieved and Norway did not contribute positively to Union-wide performance. The NSA states that cross border free route airspace has been implemented and the overall performance is influenced by constraints related to Russia's war of aggression against Ukraine and the Middle East and Kashmir conflicts resulting in circumnavigating closed airspace.

- Both KEP and KES deteriorated in comparison with 2024.

- VFE of the actual en route trajectory was 79.35%, which was better than the average Union-wide performance.

- The average time in level flight during descent and climb both improved compared to 2024.

- Additional taxi-out time was 4.32 min/flight which improved marginally from 4.52 min/flight in 2024, and additional taxi-in time was 1.17 min/flight which improved compared to 1.49 min/flight in 2024.

- Additional time in the arrival sequencing and metering area deteriorated to 2.96 min/flight from 2.64 min/flight in 2024.

- Airport data for Bergen airport was not reported for 2025 despite being subject to monitoring as per the Regulation.

