## **ER1.3.  SECTION 3 -- REGULATORY RESULT**

### **ER1.3.1. AVINOR NET GAIN/LOSS ON ACTIVITY IN THE NORWAY CONTINENTAL EN ROUTE CHARGING ZONE IN 2025**

Avinor reported a net gain of +0.9 M€, as a combination of a gain of +1.1 M€ arising from the cost sharing mechanism, with a loss of -0.2 M€ arising from the traffic risk sharing mechanism.

### **ER1.3.2. AVINOR OVERALL REGULATORY RESULT (RR) FOR THE EN ROUTE ACTIVITY**

Ex-post, the overall RR, taking into account the net gain from the en route activity mentioned above (+0.9 M€) and the actual RoE (+8.9 M€), amounts to +9.9 M€ (8.8% of the en route revenues). The resulting ex-post rate of return on equity is 11.5%, which is higher than the 10.4% planned in the PP. See also Note 1 below.

### **ER1.3.3. NOTES** 

#### **ER1.3.3.1. NOTE 1**

Ex-ante and ex-post RoE are computed based on the notional gearing of 60% debt used in the RP4 PP. The actual gearing of Avinor for 2025 should be reported as it impacts the overall regulatory result for that year.

#### **ER1.3.3.2. NOTE 2**

# **TZ1. TERMINAL CHARGING ZONE -- NORWAY**

