## **2.2.1.A. KPI #1**

### **Assessment of the achieved level of actual performance in the environment KPA**

Cross border free route airspace implemented. Due to airspace constraint related to the war in Ukraine, Middle East and the Kashmir conflict, the overall performance is influenced by circuimnavigating closed airspace.

### **Has the ANSP implemented any major operational or structural changes (incl. any new fixed assets put into operation) during the calendar year impacting performance in this key performance area? Please outline the relevant changes and their estimated impact**

No major operational or structural changes implemented.

### **Progress on the implementation of the measures committed to in the ERNIP**

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

Avinor has implemented cross-boarder-free-route-airspace so that all aircraft have the opportunity to fly as short as possible in Norwegian airspace. Since the KEA is measured from take-off to landing regardless of how short they fly, the performance will be impaired by detours that are flown outside norwegian airspace.

### **Recommendations to the ANSP to rectify the situation**

No specific recommendations.

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

No remedial measures taken.

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

No follow up measures indicated in the previous monitoring report(s)

