## **TZ1.1. SECTION 1 -- UNIT COST**

### **TZ1.1.1. AUC VS. DUC**

In 2025, the terminal AUC was -4.1% (or -94.75 NOK2022, -9.38 €2022) lower than the planned DUC. This results from the combination of lower than planned terminal costs in real terms (-4.5%, or -23.7 MNOK2022, -2.3 M€2022) and slightly lower than planned TNSUs (-0.3%).

### **TZ1.1.2. TERMINAL SERVICE UNITS**

The difference between actual and planned TNSUs (-0.3%) falls inside the ±2% dead-band. Hence, the loss of terminal revenues is borne by the ANSPs.

### **TZ1.1.3. TERMINAL COSTS BY ENTITY**

Actual real terminal costs are -4.5% (-2.3 M€2022) lower than planned. This is the result of lower costs for the main ANSP, Avinor (-4.6%, or -2.4 M€2022) and higher costs for the MET service provider (+0.2%), the NSA (+11.9%, or +0.01 M€2022).

### **TZ1.1.4. TERMINAL COSTS FOR THE MAIN ANSP (AVINOR) AT CHARGING ZONE LEVEL**

Based on the additional information to the terminal reporting tables, the lower than planned terminal costs in real terms for Avinor in 2025 (-4.6%, or -2.4 M€2022) result from:

- Significantly lower than planned staff costs (-6.2%), mainly due to lower pension costs. Actual pension costs were below determined costs, primarily driven by changes to the defined benefit pension scheme (SPK) and the related pension assumptions, including the discount rate, expected return, pension increase and social security increase. Lower than planned overtime costs for Towers also contributed to the decrease.

- Significantly lower than planned other operating costs (-5.2%), mainly due to lower than planned insurance premiums.

- Slightly higher than planned depreciation (+1.6%), reflecting minor adjustments across the project portfolio.

- Higher than planned cost of capital (+3.5%), mainly due to a higher WACC, resulting from an increase in the average interest on debts.

- Significantly lower than planned deduction for VFR exempted flights (-14.1%).

### **TZ1.1.5. ASSESSMENT OF THE ACTUAL PERFORMANCE IN THE CHARGING ZONE REPORTED BY THE NSA**

The NSA of Norway provides the following overall assessment of the actual performance in 2025 at charging zone level:

*"The real en route unit costs are -4.1% lower than the DUC mainly driven by the lower costs as the actual service units are only -0.3% lower than the determined."*

\[It should be noted that the extract from the NSA 2025 monitoring report cited above refers to "en-route unit costs" whereas figures presented reflect terminal costs and service unit differences and it is reported under "terminal ANS" section of the report.\]

### **TZ1.1.6. EXPLANATION OF THE DIFFERENCES BETWEEN ACTUAL AND DETERMINED COSTS AT CHARGING ZONE LEVEL REPORTED BY THE NSA**

The NSA provides the following explanation for the differences between actual and determined costs in the charging zone:

*"Actual staff costs are 6.4 % lower than determined costs in 2025, equivalent of an underspend of 25.3 MNOK. The variance is mainly attributable to pension costs, with actual pension costs coming in NOK 14.8 million below determined costs, mainly driven by plan changes in the defined benefit pension scheme (SPK), as well as changes in the underlying pension assumptions (including discount rate and expected return, pension increase and social security increase). Another contributing factor is that overtime costs for Towers were lower than determined."*

### **TZ1.1.7. RECOMMENDATIONS FORMULATED BY THE NSA TO THE ANSP (AVINOR) TO RECTIFY THE SITUATION AND ACTIONS TAKEN BY THE ANSP**

No information was provided by the NSA in the NSA 2025 Monitoring Report.

Avinor reports the implementation of the following actions:

*"An amount of -9.9 MNOK of the reduced pension costs are treated as an unforeseen change and carried forward to airspace users in n+2."*

### **TZ1.1.8. NOTES**

#### **TZ1.1.8.1. NOTE 1**

#### **TZ1.1.8.2. NOTE 2**

