## **2.3.1.B. KPI #2**

### **Identification and analysis of the reasons and circumstances resulting in the achieved level of actual performance of the arrival ATFM delay per flight KPI**

The actual terminal and airport ANS ATFM arrival delay per flight of 0,13min./flt. at a national level in 2025, still significant below the national target set to 0,50 min./flt. Actual performance is so far in RP4 better than set in the PP.

A significant part of the delays are reported in 2025 are connected to weather conditions at ENGM in January

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

Capacity performance target being achieved in 2025.

### **Recommendations to the ANSP to rectify the situation**

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

No spesific remedial measures indicated in the previous monitoring report(s).

