## **2.3.1.A. KPI #1**

### **Identification and analysis of the reasons and circumstances resulting in the achieved level of actual performance of the en-route ATFM delay per flight KPI**

The actual en-route atfm actual delay per flight of 0,04 min./flt. in 2025 was significant below the national target set to 0,16 min./flt. The delays in 2025 are mainly related ATC capacity in July and August and Non-ATC during the authumn period.

The reasons and circumstances resulting in the achieved level of actual performance such as less traffic than expected due to the war in Ukraine, Middle-East and Kashmir conflict.

### **Description of the adjustments to the capacity plan included in adopted performance plan**

Planned implementation of upper/lower concept for sector 8 in June 2026.

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

Capacity performance target being achieved in 2025.

### **Recommendations to the ANSP to rectify the situation**

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

No spesific remedial measures indicated in the previous monitoring report(s)

