## **ER1.1. SECTION 1 -- UNIT COST**

### **ER1.1.1. AUC VS. DUC**

In 2025, the en route AUC was -1.9% (or -10.41 NOK2022, -1.03 €2022) lower than the planned DUC. This results from the combination of lower than planned en route costs in real terms (-2.1%, or -27.6 MNOK2022, -2.7 M€2022) and slightly lower than planned TSUs (-0.1%).

### **ER1.1.2. EN ROUTE SERVICE UNITS**

The difference between actual and planned TSUs (-0.1%) falls inside the ±2% dead-band. Hence, the loss of en route revenues is borne by the ANSPs.

### **ER1.1.3. EN ROUTE COSTS BY ENTITY**

Actual real en route costs are -2.1% (-2.7 M€2022) lower than planned. This is the result of lower costs for the main ANSP, Avinor (-2.1%, or -2.6 M€2022), the NSA/EUROCONTROL (-2.0%, or -0.2 M€2022) and the MET service provider (-0.5%) and higher costs for the other ANSP (KJE, +4.4%, or +0.1 M€2022).

### **ER1.1.4. EN ROUTE COSTS FOR THE MAIN ANSP (AVINOR) AT CHARGING ZONE LEVEL**

Based on the additional information to the en route reporting tables, the lower than planned en route costs in real terms for Avinor in 2025 (-2.1%, or -2.6 M€2022) result from:

- Lower than planned staff costs (-3.3%), mainly reflecting unforeseen change in pension costs (amounting to -19.5 MNOK in nominal terms), driven primarily by changes to the defined benefit pension scheme (SPK) and the related pension assumptions, including the discount rate, expected return, pension increase and social security increase.

- Higher than planned other operating costs (+1.9%), mainly due to higher consultancy costs and STAMNETT-related costs in Tech, as well as the write-off of receivables and purchases.

- Lower than planned depreciation (-2.1%), mainly due to projects not being completed according to plan. It should be noted that the 2025 actual depreciation cost has been adjusted up by 10.8 MNOK by the revenues from the Union assistance programmes of 2022.

- Slightly higher than planned cost of capital (+0.6%), mainly due to a higher WACC, partly offset by lower net current assets.

- Higher than planned deduction for VFR exempted flights (+1.8%).

### **ER1.1.5. ASSESSMENT OF THE ACTUAL PERFORMANCE IN THE CHARGING ZONE REPORTED BY THE NSA**

The NSA of Norway provides the following overall assessment of the actual performance in 2025 at charging zone level:

*"The real en route unit costs are -1.9% lower than the DUC mainly driven by the lower costs as the actual service units are only -0.1% lower than the determined."*

### **ER1.1.6. EXPLANATION OF THE DIFFERENCES BETWEEN ACTUAL AND DETERMINED COSTS AT CHARGING ZONE LEVEL REPORTED BY THE NSA**

The NSA provides the following explanation for the differences between actual and determined costs in the charging zone:

*"The main driver behind the cost reduction (28.5 MNOK) when comparing the actual costs to the determined is lower pension expenses. Unforeseen changes in pension costs for En Route are calculated to be a total of (19.5) MNOK, mainly driven by plan changes in the defined benefit pension scheme (SPK), as well as changes in the underlying pension assumptions (including discount rate and expected return, pension increase and social security increase). The amount will be carried forward and deducted from the unit rate in n+2."*

### **ER1.1.7. RECOMMENDATIONS FORMULATED BY THE NSA TO THE ANSP (AVINOR) TO RECTIFY THE SITUATION AND ACTIONS TAKEN BY THE ANSP**

No information was provided by the NSA in the NSA 2025 Monitoring Report.

Avinor reports the implementation of the following actions:

*"An amount of -19.5 MNOK of the reduced pension costs are treated as an unforeseen change and carried forward to airspace users in n+2."*

### **ER1.1.8. NOTES**

#### **ER1.1.8.1. NOTE 1**

#### **ER1.1.8.2. NOTE 2**

