## PRB1.3. Safety {#prb1.3.-safety .Heading-2-ER}

- In 2025, ENAIRE achieved the planned maturity levels set out in its performance plan for all five components of the EoSM. In more detail, ENAIRE exceeded the planned levels in all areas, reaching the highest level D in all components.

- In 2025, EA met the planned maturity levels set out in its performance plan for all five components of the EoSM. In more detail, EA exceeded the planned level in the area of Safety Risk Management, reaching level D together with Safety Culture component.

- In 2025, Skyway met the planned maturity levels set out in its performance plan for four out of five components of the EoSM. In more detail, the area where Skyway missed the planned level was Safety Policy and Objectives.

- The rate of runway incursions (RI) was 2.14 at airport level, lower than the Union-wide average, and lower than the rate of RIs in 2024. The rate of RIs with ANS contribution was 0.50, lower than the Union-wide average, and lower than the rate of RIs with ANS contribution in 2024.

- The rate of separation minima infringements (SMIs) at State level was 4.26, and at ANSP level 6.67. Rate of SMIs at State level was below the Union-wide average, whereas at ANSP level the rate was above the Union-wide average. When comparing to 2024, rate of SMIs has decreased at both State level and at ANSP level.

