## **2.2.1.A. KPI #1**

### **Assessment of the achieved level of actual performance in the environment KPA**

Throughout 2025, the KEA value showed a month-by-month improvement, from 3,30% in January to 3,23% in December, despite a 4,7% increase in traffic.

More than 2,47 million flights were managed in 2025, representing a 4,7% increase compared to 2024. Additionally, growing adverse weather conditions frequently require deviations from the planned route; July, August, September and October accumulate almost 65% of the delay generated by weather during 2025.

### **Has the ANSP implemented any major operational or structural changes (incl. any new fixed assets put into operation) during the calendar year impacting performance in this key performance area? Please outline the relevant changes and their estimated impact**

As a result of the monitoring tasks carried out by AESA it was informed the following to the Commission:

Measures such as the continuous deployment of new connectivities and direct routes. Airspace optimization through the progressive deployment of Free Route Airspace (FRA) across all FIRs will allow aircraft to fly more direct routes, as well as on gaining more airspace flexibility by implementing flexible sectors configurations with the project "Bricks". Enhanced ATFM coordination between Network Manager (NM) and ANSPs will help mitigate congestion by improving tactical flow management and optimizing sector capacities dynamically. The reinforcement of the controller staffing levels that is being developed by ENAIRE will continue and will help address operational bottlenecks, reducing the need for ATFM measures that often penalize the route efficiency. Flexible use of airspace (FUA) will be prioritized to maximize available capacity while minimizing constraints imposed by restricted and military areas, increasing availability times for flight planning, freeing up cruising levels for overflights and modifying the geometry of some of these areas. Both ENAIRE and the Military are working in SESAR project. New DCTs have been implemented and new agreements have been reached between Enaire and the military authorities regarding certain military areas applicable during the summer of 2025. Some of these agreements have been maintained over time (including new FUA-R areas adjustments to area reservations in line with actual use, among others).

Implementing these measures collectively will contribute to a more efficient, resilient, and performance driven airspace network, enabling a more probable compliance with KEA targets while accommodating the very high growing traffic demand still expected for the coming years.

Following coordination with ENAIRE, additional information is provided below:

- Regarding FRA-Cross border Free Route Airspace it is noted that following coordination with the SDM and ENAIRE at the meeting held on 21 October to follow up on CP1 projects, it was concluded that the project is likely to be completed in 2027. In 2025, work was carried out on the TTM implementation, and two phases were defined.

- Additional actions developed under the FUA consideration include: ensuring availability of frequently used ad-hoc areas in CACD (to maximize route availability), elaboration of Dynamic Management Mil Areas Procedure, implementation of a new set of FUA Indicators, LARA V5 update and a global increase of the availability of Air Space structures for the CAG.

- Throughout 2025, work has continued on the implementation of PBN procedures.

### **Progress on the implementation of the measures committed to in the ERNIP**

The 2025 plans included in the ERNIP that may have an impact on KEA are specified below

• FUA measures -- Civil Military coordination

• ESPORTFRA: Work is on-going during 2025 to continue improve the Free Route estructure within Spain and Portugal. Working is on-going for crossborder initiatives. ESPORTFRA Phase 1 will be published 14 May 2026.

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

Although the target was not met, the trend in the indicator is considered positive because the decline has been steady throughout the year, despite a 4.7% increase in traffic compared with 2024. The high demand has led to congestion in key airspace sectors, requiring the implementation of ATFM measures and route deviations, leading to suboptimal trajectories and operational inefficiencies which have negatively impacted en-route efficiency. The high increase of severe adverse weather conditions in Spain, especially in the Mediterranean area, such as convective phenomena, thunderstorms, turbulence, and strong winds, frequently require deviations from the planned route, leading to increased route extensions. Staffing limitations have required the implementation of ATFM measures which have also contributed to not to reach optimal operational en-route efficiency. The fact that FRA implementation is going on with some delays (from 2025 to 2027) have had the effect to eat up the beneficial effects of other measures put in place. The growing military activity due to the geopolitical situation limit the ability to optimize flight paths. Airlines\' cost optimization strategies prioritize lower route charges over minimum distance, penalizing the KEA indicator.

The non-compliance of KEA was anticipated before the end of the year and was informed to the Commission according to Regulation (EU) 2019/317 Article 37 (1), concluding that despite the improvement in the indicator and that the projects were generally being implemented on time, the delay in the implementation of FRA and the other issues highlighted have contributed to the failure to meet the target.

### **Recommendations to the ANSP to rectify the situation**

AESA, ENAIRE, Ministry of Transport and the Spanish Air Force are all working and collaborating very closely to address the structural airspace problems that contribute to the route inefficiency. The measures to be implemented to achieve the targets are those considered in ESPP4. The environmental plan within the ESPP4 has being implemented mostly as it was defined except FRA, one of the most relevant project.

When FRA project is fully implemented, aircrafts will be allowed to fly more direct routes, reducing unnecessary deviations. Enhanced ATFM coordination between Network Manager (NM) and ANSPs will help mitigating congestion. Sector reconfiguration and flexible use of airspace (FUA) will maximize available capacity. Reinforcing controller staffing levels and optimizing sector workload distribution will contribute improving operational bottlenecks reducing the need for excessive route extension.

Encourage ENAIRE to continue working on actions planned in the ESPP4 Performance Plan, particularly FRA project which has been postponed from 2025 to 2027.

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

To improve KEA performance and enhance en-route flight efficiency, a series of strategic and operational measures will be considered:

- Firstly, in the short term, the continuous deployment of new connectivities and direct routes, reducing unnecessary deviations and non-direct routes.

ENAIRE also will continue working on the airspace optimization through the progressive deployment of Free Route Airspace (FRA) across all FIRs will allow aircraft to fly more direct routes, as well as on gaining more airspace flexibility by implementing flexible sectors configurations with the project "Bricks".

- Secondly, enhanced ATFM coordination between Network Manager (NM) and ANSPs will help mitigate congestion by improving tactical flow management and optimizing sector capacities dynamically, not only in bad weather situations but in demand -- capacity imbalance situations with the application of a specific procedure in the framework of the Cross Border Weather and Capacity Procedure.

- The reinforcement of the controller staffing levels that is being developed by ENAIRE will continue in 2026 and will help address operational bottlenecks, reducing the need for ATFM measures that often penalize the route efficiency.

- Additionally, flexible use of airspace (FUA) will be prioritized to maximize available capacity while minimizing constraints imposed by restricted and military areas, increasing availability times for flight planning, freeing up cruising levels for overflights and modifying the geometry of some of these areas. Both ENAIRE and the Military are working in SESAR project regarding the development and implementation of DMA type 3 as well as in the implementation of the SESAR 115 Solution for the accommodation of RPAS in controlled airspace, and are developing a Procedure for the dynamic management of Areas.

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

AESA continues its monitoring activities in RP4, particularly that of the KPIs associated with a target to be met, which is monitored on a monthly and annual basis. With them, it is possible to keep track of the evolution of the indicators and to maintain an adequate coordination and communication with the parties involved.

Additionally, before the end of the year and having previously made a forecast of the possible final values of the KPIs, AESA monitors the implementation status of the projects mentioned in the ESPP4 Performance Plan as well as new projects that may have been included in the NOP and ERNIP and that can have a positive effect in the environmental area, in order to know their evolution as well as the impact on the corresponding indicators.

The measures (specially FRA and FUA) are being implemented and future improvements are expected to be observed in the comig years.

