## TRM1.3. Additional time in terminal airspace (PI#6) {#trm1.3.-additional-time-in-terminal-airspace-pi6 .Heading-2-TZ}

Six Spanish airports are subject to the monitoring of this indicator: Madrid -- Barajas, Barcelona, Palma de Mallorca, Málaga, Gran Canaria and Alicante.

Additional time in Madrid -- Barajas in 2025 decreased to 2.63 min/dep, 6% lower than 2024 value -- last year of RP3 -- of 2.81 min/arr.

Additional time in Barcelona in 2025 increased to 3.65 min/dep, 6% higher than 2024 value -- last year of RP3 -- of 3.43 min/ arr.

Additional time in Palma de Mallorca in 2025 was equal to 2.65 min/dep, very close to 2024 value -- last year of RP3 -- of 2.64 min/ arr.

Additional time in Málaga in 2025 decreased to 3.38 min/dep, 5% lower than 2024 value -- last year of RP3 -- of 3.57 min/ arr.

Additional time in Gran Canaria in 2025 decreased to 3.44 min/dep, 15% lower than 2024 value -- last year of RP3 -- of 4.04 min/ arr.

Additional time in Alicante in 2025 decreased to 2.72 min/dep, 4% lower than 2024 value -- last year of RP3 -- of 2.84 min/ arr.

The average for RP4 airports subject to monitoring of this indicator across Member States in 2025 was 2.98 min/arr.

