## **2.3.2.C. PI #3**

### **Please provide background information on the actual performance: - If performance improved compared to previous years, please describe the measures that were implemented (if any), - If performance deteriorated compared to previous years, please explain the reasons which lead to the deterioration, and describe the improvement measures which are planned to improve performance. How does the NSA intend on monitoring their effectiveness on performance**

2025 values are lower than the 2024 values, despite of the increase in traffic this year.

However, it should be noted that all-cause departure delay is very generic and ATFM delay is only a small contributor. Departure delay can be generated by ATFM en-route delay (not only local airport, but the complete Network), but also reactionary and turnaround delay, technical issues with the aircraft, airport operations, problems with passengers and/or luggage, etc. In other words, it is not always possible to address a specific reason as this delay is quite generic. Consequently, without a clear focus of the problem to address, it is not feasible to establish measures that can significantly impact the improvement of the indicator, beyond those already mentioned in section 2.2.2.D. PI #4 of this monitoring report.

This PI is monitored by AESA. Should any significant deviations be identified, the possible causes will be analysed as part of the annual monitoring process, in collaboration with the relevant stakeholder.

### **If the data at airport level are not available, please explain the reasons why data is missing and describe the measures planned to resolve the situation**

