## TRM1.1. Additional time in taxi-out phase (PI#4)

Six Spanish airports are subject to the monitoring of this indicator: Madrid -- Barajas, Barcelona, Palma de Mallorca, Málaga, Gran Canaria and Alicante. All of them except Alicante maintained the indicator within 0.1 minutes of variation compared to 2024.

Additional time in Madrid -- Barajas in 2025 was equal to 3.62 min/dep, very close to 2024 value -- last year of RP3 -- of 3.65 min/dep.

Additional time in Barcelona in 2025 was equal to 3.82 min/dep, very close to 2024 value -- last year of RP3 -- of 3.78 min/dep.

Additional time in Palma de Mallorca in 2025 was equal to 3.64 min/dep, very close to 2024 value -- last year of RP3 -- of 3.70 min/dep.

Additional time in Málaga in 2025 increased to 3.43 min/dep, 4% higher than 2024 value -- last year of RP3 -- of 3.31 min/dep.

Additional time in Gran Canaria in 2025 decreased to 3.01 min/dep, 4% lower than 2024 value -- last year of RP3 -- of 3.12 min/dep.

Additional time in Alicante in 2025 increased to 3.23 min/dep, 5% higher than 2024 value -- last year of RP3 -- of 3.09 min/dep.

The average for RP4 airports subject to monitoring of this indicator across Member States in 2025 was 3.61 min/dep.

