## **2.3.2.A. PI #1**

### **Please provide background information on the actual performance: - If performance improved compared to previous years, please describe the measures that were implemented (if any), - If performance deteriorated compared to previous years, please explain the reasons which lead to the deterioration, and describe the improvement measures which are planned to improve performance. How does the NSA intend on monitoring their effectiveness on performance**

The result for 2025 (aggregate of the 7 airports subject to monitoring) improves by 0,4% the result of the previous year, being all results well above the value of 80% set in Regulation (EU) No. 255/2010 of the Commission. ANSPs analyse trends which, if negative, would be corrected. Based on current figures, ANSPs does not believe it is necessary to establish specific improvement measures.

This PI is monitored by AESA. Should any significant deviations be identified, the possible causes will be analysed as part of the annual monitoring process, in collaboration with the relevant stakeholder.

