## TRM1.4. Air traffic control pre-departure delay (PI#2) {#trm1.4.-air-traffic-control-pre-departure-delay-pi2 .Heading-2-TZ}

The calculation of the ATC pre-departure delay is based on the data provided by the airport operators through the Airport Operator Data Flow (APDF) which is properly implemented at all 6 Spanish airports subject to monitoring of this indicator.

However, there are several quality checks before EUROCONTROL can produce the final value which is established as the average minutes of pre-departure delay (delay in the actual off block time) associated to the IATA delay code 89 (through the APDF, for each delayed flight, the reasons for that delay have to be transmitted and coded according to IATA delay codes.

However, sometimes the airport operator has no information concerning the reasons for the delay in the off block, or they cannot convert the reasons to the IATA delay codes. In those cases, the airport operator might:

- Not report any information about the reasons for the delay for that flight (unreported delay)

- Report a special code to indicate they do not have the information (code ZZZ)

- Report a special code to indicate they do not have the means to collect and/or translate the information (code 999)

To be able to calculate with a minimum of accuracy the PI for a given month, the minutes of delay that are not attributed to any IATA code reason should not exceed 40% of the total minutes of pre-departure delay observed at the airport.

Finally, to be able to produce the annual figure, at least 10 months of valid data is requested by EUROCONTROL.

The high share of unidentified delay reported by 4 out of the 6 Spanish airports under monitoring (Madrid, Barcelona, Gran Canaria and Palma de Mallorca) prevent the calculation of this indicator. Ibiza is not subject to the monitoring of this indicator.

Delay in Alicante in 2025 was equal to 0.60 min/dep, very close to 2024 value-- last year of RP3 -- of 0.63 min/dep.

Delay in Málaga in 2025 was equal to 0.48 min/dep, very close to 2024 value-- last year of RP3 -- of 0.53 min/dep.

The average for RP4 airports subject to monitoring of ATC pre-departure delay across Member States and for which enough data is available in 2025 was 0.74 min/dep.

