## **2.3.3 ATCO Planning 1**

### **Additional comments**

### **Additional comments**

\"Number of additional ATCOs in OPS planned to start working in the OPS room (FTEs)\" it\'s been considered all the operative ATCOs (C4) who started working for all reasons: CMCD, transfer, secondment, article 88 (II ATCOs collective bargaining agreement), new recruitments, unpaid leave return (voluntary or without job post reservation), change of designation, etc.

\"Number of ATCOs in OPS planned to stop working in the OPS room (FTEs)\" it\'s been considered all the operative ATCOs (C4) who stopped working for all reasons: retirements, RAE or RA concessions, dismissals, CMCD, transfer, end of a secondment, end of article 88 application, voluntary unpaid leave,change of designation, etc.

### **Description of the training process, including details on the effective failure rate and the process used to allocate newly qualified ATCOs between ACC, APP and TWR positions**

The allocation of positions among the different ENAIRE units is carried out before the air traffic controller recruitment process is opened. Following the internal staff transfer process, the vacancies are offered through the competitive selection process, having been calculated on the basis of expected traffic and other operational parameters.

Candidates who pass the selection process are given 18 months to meet the required qualifications, including the SATCO licence with all ratings and rating endorsements, a valid Class 3 Medical Certificate (CIMA), and the required level of language proficiency.

Once candidates have signed their contract with ENAIRE, they may begin unit training at their assigned unit.

The failure rate is low.

