## **TZ1.2. SECTION 2 -- ACTUAL UNIT COST INCURRED BY THE USERS**

### **TZ1.2.1. FOCUS ON TERMINAL AUCU MONITORING AT CHARGING ZONE LEVEL**

The actual terminal unit cost incurred by airspace users (AUCU) in respect of activities performed in 2025 (15.80 €) is -87.6% lower than the nominal DUC (127.83 €) (see Note 1 below regarding the calculation of AUCU for Spain TCZ). The difference between these two figures (-112.03 €/SU) is due to:

- the deduction of other revenues (-76.68 €/SU) corresponding to the amount received by ENAIRE through the contract with the airport operator (Aena) for aerodrome services;

- the positive inflation adjustment resulting from higher than planned inflation (+0.61 €/SU);

- the impact of adjustments resulting from the costs exempted from cost sharing mechanism (-1.14 €/SU);

- the deduction of the traffic risk sharing adjustments (-1.29 €/SU);

- the deduction of the traffic adjustment (-0.20 €/SU) for the costs not subject to traffic risk sharing; and,

- the application of a lower unit rate as foreseen in Art. 29(6) in year 2025 (-33.34 €/SU).

The share of the regulatory result (see next sub-section) in the AUCU (before the deduction of other revenues) is 20.6% (see Note 2 below).

Costs exempt from cost sharing for 2025 presented here are based on preliminary figures and remain subject to revision pending the receipt of the NSA Reports on the verification of cost sharing due by 1 September 2026. Any changes may affect the analysis of Actual Costs for Users and the Regulatory Results.

### **TZ1.2.2. INITIATIVES IMPLEMENTED OR PLANNED THAT WILL IMPROVE THIS PI REPORTED BY THE NSA**

The NSA of Spain provides the following information regarding the initiatives:

*"An annual cost verification is carried out."*

### **TZ1.2.3. NOTES** 

#### **TZ1.2.3.1. NOTE 1**

Spain (specifically ENAIRE) only charges a portion of terminal determined costs (approximately 20%) to the airspace users through terminal navigation charges, while the rest is financed through the income relating to contractual arrangement between ENAIRE and the airport operator Aena (disclosed under Other revenues). This should be considered when interpreting the analysis above.

Furthermore, as is the case for all charging zones, the AUCU and, in particular, its components (adjustments related to 2025 activity) disclosed for the Spanish terminal charging zone here are derived using the data reported in Table T2A. However, Spain (specifically ENAIRE) only carries forward a portion of calculated adjustments into the terminal unit rate (approximately 20%, which are attributable to the \"*final approach determined costs*\"). Due to this specificity, the components of AUCU presented here do not represent the adjustments actually carried forward into future unit rates.

#### **TZ1.2.3.1. NOTE 2**

