## **2.2.2.D. PI #4**

### **What initiatives were implemented or are planned that will improve this PI and how does the NSA intend on monitoring their effectiveness on performance?**

The additional taxi out time (aggregated for the 6 airports monitored in RP4) has remained stable (+0,01 min/flight) compared with 2024 while traffic has increased by 3,5%.

In general, the highest additional taxi-out times throughout the year occur during the high season months of each airport, variations in this indicator are related to traffic especially at airports such as LEPA and LEMG.

In 2025 taxi times at LEMG and LEAL are higher than 2024 (+3,7% for LEMG and +4,5% for LEAL) due to traffic increase (+7% in LEMG and +16% in LEAL). Additionally, Barcelona and Palma airports experienced frequent adverse weather conditions over several months.

There is work in progress regarding the improvement of A-CDM in Madrid, Barcelona, Palma y Málaga:

- The project related to more accurate Taxi times/stand is almost finished.

- New TWR UPDATE A-DPI has already been implemented.

LEIB is monitored together with these 6 airports as it is one of the airports considered in the Spanish performance plan (ESPP4) for RP4. In 2025 it reaches a value of 2,97, lower (-5,4%) than the 2024 value (3,14). The additional taxi-out time (aggregated for the 7 airports monitored in RP4) has a value of 3,53 the same as in 2024.

This PI is monitored by AESA. Should any significant deviations be identified, the possible causes will be analysed as part of the annual monitoring process, in collaboration with the relevant stakeholder.

### **If the data at airport level are not available, please explain the reasons why data is missing and describe the measures planned to resolve the situation**

