## TRM1.5. Average departure delay from all causes per flight (PI#3) {#trm1.5.-average-departure-delay-from-all-causes-per-flight-pi3 .Heading-2-TZ}

Six Spanish airports are subject to the monitoring of this indicator: Madrid -- Barajas, Barcelona, Palma de Mallorca, Málaga, Gran Canaria and Alicante. All of them except Madrid decreased their average departure delay by at least one minute.

Delay in Madrid -- Barajas in 2025 was equal to 16.52 min/dep, very close to 2024 value -- last year of RP3 -- of 16.65 min/dep.

Delay in Barcelona in 2025 decreased to 16.67 min/dep, 12% lower than 2024 value -- last year of RP3 -- of 18.98 min/dep.

Delay in Palma de Mallorca in 2025 decreased to 20.31 min/dep, 11% lower than 2024 value -- last year of RP3 -- of 22.89 min/dep. Still, Palma had the third highest delay among airports under RP4 monitoring.

Delay in Málaga in 2025 decreased to 17.48 min/dep, 18% lower than 2024 value -- last year of RP3 -- of 21.20 min/dep.

Delay in Gran Canaria in 2025 decreased to 14.27 min/dep, 17% lower than 2024 value -- last year of RP3 -- of 17.22 min/dep.

Delay in Alicante in 2025 decreased to 17.69 min/dep, 7% lower than 2024 value -- last year of RP3 -- of 19.02 min/dep.

The average for RP4 airports subject to monitoring of all causes pre-departure delay across Member States in 2025 was 16.47 min/dep.
