## **2.2.1.A. KPI #1**

### **Assessment of the achieved level of actual performance in the environment KPA**

Performance is well inline with the target. The performance is still affected by the restrictions concerning Russia (and Kaliningrad), which is reflected in the targets for RP4.

### **Has the ANSP implemented any major operational or structural changes (incl. any new fixed assets put into operation) during the calendar year impacting performance in this key performance area? Please outline the relevant changes and their estimated impact**

No. The main measure to increase the performance whitin this KPI is project SWEA. Implementation of Airspace project Swea delayed to november 2027, with the aim to improve traffic flow efficiency to/from the Stockholm area.

### **Progress on the implementation of the measures committed to in the ERNIP**

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

N/A

### **Recommendations to the ANSP to rectify the situation**

N/A

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

N/A

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

