## **ER1.1. SECTION 1 -- UNIT COST**

### **ER1.1.1. AUC VS. DUC**

In 2025, the en route AUC was -3.6% (or -26.41 SEK2022, -2.49 €2022) lower than the planned DUC. This results from the combination of significantly lower than planned en route costs in real terms (-9.0%, or -198.5 MSEK2022, -18.7 M€2022) and significantly lower than planned TSUs (-5.6%).

### **ER1.1.2. EN ROUTE SERVICE UNITS**

The difference between actual and planned TSUs (-5.6%) falls outside the ±2% dead-band, but does not exceed the ±10% threshold foreseen in the traffic risk sharing mechanism. The resulting loss of en route revenues is therefore shared between the ANSP and the airspace users (see the main ANSP regulatory result).

### **ER1.1.3. EN ROUTE COSTS BY ENTITY**

Actual real en route costs are -9.0% (-18.7 M€2022) lower than planned. This is the result of lower costs for the main ANSP, LFV (-12.0%, or -17.5 M€2022), the NSA/EUROCONTROL (-2.4%, or -0.7 M€2022), the other ANSPs (ACR, ARV, SDATS and CNS providers, -1.0%, or -0.3 M€2022) and the MET service provider (-4.1%, or -0.3 M€2022).

### **ER1.1.4. EN ROUTE COSTS FOR THE MAIN ANSP (LFV) AT CHARGING ZONE LEVEL**

Based on the additional information to the en route reporting tables, the significantly lower than planned en route costs in real terms for LFV in 2025 (-12.0%, or -17.5 M€2022) result from:

- Significantly lower than planned staff costs (-18.4%), mainly due to the variation in pension costs (-172 MSEK, or some -15 M€2022) reflecting a combined effect of higher interest rates (which lowered the level of pension liability) and higher pension indexation (which increased pension liability). It should be noted that the difference in pension costs will be returned to the airspace users through the cost exempt from cost sharing mechanism. Staff costs (excluding pensions) were also lower than planned due to delayed recruitments.

- Slightly higher than planned other operating costs (+0.2%).

- Significantly lower than planned depreciation (-6.1%), mainly due to "*lower depreciations on ATM and COM assets due to delayed investments*".

- Significantly higher than planned cost of capital (+59.7%) mainly reflecting much higher than planned proportion of financing through equity as well as higher actual interest rate on debt.

### **ER1.1.5. ASSESSMENT OF THE ACTUAL PERFORMANCE IN THE CHARGING ZONE REPORTED BY THE NSA**

The NSA of Sweden provides the following overall assessment of the actual performance in 2025 at charging zone level:

\"*Overall lower actual unit cost in real terms because of lower actual costs exceeding the effect of lower traffic. Note that excluding the effect of uncontrollable costs of LFV by 170 m SEK the DUC would be appr. \~ 750 SEK. A similar effect is difficult to anticipate the upcoming years.*\"

### **ER1.1.6. EXPLANATION OF THE DIFFERENCES BETWEEN ACTUAL AND DETERMINED COSTS AT CHARGING ZONE LEVEL REPORTED BY THE NSA**

The NSA provides the following explanation for the differences between actual and determined costs in the charging zone:

*"The most impacting effect and reason behind the lower actual costs relates to LFV pensions. Due to a change in the discount rate the pension costs are reported 172 million SEK lower than planned. This amount will be reimbursed to the users according to article 28 in the next reference period when all the years changes have been consolidated. The argument behind consolidating through an entire period is to have the possibility to smoothing out the effect of this uncontrollable item in order to not have unproportional effects on the unit rate. Lower pension costs are also identified in other organizations, however, since applying different pension schemes these are not considered uncontrollable.*

*Besides the pension effects, staff costs are lower than planned. The major explanation is lower costs of technical staff, CNS, ATM and IT, but also operational support staff. The main deviations are found at main-ANSP LFV, but also SMHI, ARV and CNS Ps.*

*Operational costs are higher than planned partly by consultants instead of hired staff. Eurocontrol costs are lower by 10 m SEK, which is a combination of lower costs and a favourable development of the Swedish currency.*

*Depreciation costs are lower and postponements and delays are the main explanations. Some changes to major investments at LFV is expected and will be consulted. Changes according to article 28 is disclosed in Swedens Cost risk sharing report for 2025.*

*Cost of capital is higher due to higher interest rates and to some extent higher share of equity than in the plan. Changes according to article 28 is disclosed in Swedens Cost risk sharing report for 2025.*

*The cost of Search and Rescue, a service provided by the Swedish Maritime Authority, is set to equal to the determined costs."*

### **ER1.1.7. RECOMMENDATIONS FORMULATED BY THE NSA TO THE ANSP (LFV) TO RECTIFY THE SITUATION AND ACTIONS TAKEN BY THE ANSP**

The NSA 2025 monitoring report indicates that:

"*No official recommendations made. There is an ongoing discussion on the share of equity calculation with one of the providers. Concerning Search and Rescue, the Swedish Maritime Authority is under the process of updating the allocation model valid for distribution of costs among their respective users. NSA has some concerns on the model\'s applicability and this will be subject to consultation*."

LFV reports the implementation of the following actions:

*"Concerning the WACC issue the provider is assisted by an external consulting firm. There is also a meeting date decided provider/NSA to discuss the progress of the work. Regarding cost allocation model for Search and Rescue this is subject to consultation as a first step."*

### **ER1.1.8. NOTES**

#### **ER1.1.8.1. NOTE 1**

#### **ER1.1.8.2. NOTE 2**

