## SAF1.4. Rate of separation minima infringements (SMIs) (PI#2)

At State level, Sweden reported 8 separation minima infringements (SMI) in their airspace during 2025. The rate of separation minima infringements was lower than Union-wide average (2.26 vs 7.10). At ANSP level, Sweden reported 8 SMIs with ATS/CNS contribution. The rate of separation minima infringements at ANSP level was lower than the Union-wide average (2.26 vs 6.0).

When comparing to 2024, the rate of separation minima infringements has decreased slightly at State level (2.25 vs 2.52) and increased at ANSP level (2.25 vs 1.4).

According to the monitoring report, NCA is continuously monitoring the number of SMI's and does also follow up on relevant actions taken with reference to the ANSP investigation report for the SMI. Sweden notes that there was data only available for LFV at this submission.

Furthermore, Sweden notes that the number of controlled flight hours is only available for LFV as reported previous years at the time of this reporting. The reporting corresponds to ACE data, ACCs and APPs. For other purposes and reporting these values, controlled hours of SDATS, ACR and AFAB, have been estimated to the best possible extent. Values can, probably, be extracted from the relevant systems but unfortunately not in time of this deadline.

