## PRB1.3. Safety {#prb1.3.-safety .Heading-2-ER}

- In 2025, LFV NUAC achieved the planned maturity levels set out in its performance plan for four out of five components. LFV NUAC missed the planned level in the Safety Risk Management component of the EoSM.

- In 2025, ACR achieved the planned maturity levels set out in its performance plan for four out of five components. ACR missed the planned level in the Safety Risk Management component of the EoSM.

- In 2025, AFAB did not achieve their planned maturity levels in four out of five components of the EoSM. AFAB reached the planned level only in the component of Safety Policy and Objectives.

- In 2025, SDATS did not achieve the planned maturity levels set out in its performance plan for three out of five components. SDATS missed the planned level in the Safety Risk Management, Safety Assurance and Safety Promotion components of the EoSM.

- The rate of runway incursions (RI) was 3.47 at airport level, higher than the Union-wide average, and lower than the rate of RIs in 2024. The rate of RIs with ANS contribution was 0.50, lower than the Union-wide average, and stable compared to 2024.

- The rate of separation minima infringements (SMI) was 2.26 at State level and equal to the SMIs at ANSP level, with both indicators below the Union-wide average. When comparing to 2024, the rate of SMIs has decreased slightly at State level and increased at ANSP level.

