## **2.3.3 ATCO Planning 1**

### **Additional comments**

### **Additional comments**

Planned ATCOs were based on the situation in 2023 and outcome is based on true figures 2025, there were different assumptions on for instance parental leave than what actually has been.

### **Description of the training process, including details on the effective failure rate and the process used to allocate newly qualified ATCOs between ACC, APP and TWR positions**

General information ATCO-training in LFV:

New courses start two times every year, already from the start ATCO students are allocated to either En route (APP/ACC-course) or Tower (TWR/APP-course) - there is no point where you can change course.

ATCO training includes 1,5 Year at EPN (ATS Academy) and 1 year of local training/OJT.

26 ACC students start at the academy in 2025, a part is financed by the military. Estimated 20 students out of the 24 will be checked out 2,5 years after the start att the ATS academy.

12 TWR/APP students started training at the academy in 2025, to a larger extent financed by the military, only civil-financed ATCO students reported, these are financed through en route charges, terminal charge or in contract with airport operators.

Success-rate for LFV ATCO students is based on the last 100 ATCO students in completed classes.

The latest figures are for Initial Training 78 % and for Unit Training 77 % (figures not to be added, not the same courses included).

