## **2.2.2.I. PI #9**

### **What initiatives were implemented or are planned that will improve this PI and how does the NSA intend on monitoring their effectiveness on performance?**

AMC Sweden states that during 2025, just like in previous years, they have maintained an ongoing dialogue with both SAAB (by far the largest user of AMA) and with the Swedish Armed Forces in order to improve this indicator. AMC can note that their customers have become significantly better at utilizing areas they have booked, as well as canceling areas that are not used.

Please note that, due to rounding, the total number of hours for the state may differ from the sum of the hours reported for each ACC.

Swedish Transport Agency is represented in AMC Sweden and monitors the work and performance.

Take note that the data in RP4_FUA_IND_2025_Jan_Dec available at https://www.sesperformance.eu/dataportal/data/ is not in consistency with data provided in these tables. The data from the SES portal states 94,48 percent.

