## **2.3.1.A. KPI #1**

### **Identification and analysis of the reasons and circumstances resulting in the achieved level of actual performance of the en-route ATFM delay per flight KPI**

Sufficient en-route capacity was provided, resulting in the achieved performance. The total minutes of delay (after post-ops adjusments) amounted to 13 319 (2024: 6 357). The traffic was slightly lower than 2024 and in the performance plan.

The performance is in line with expectations. SE RP4 plan as such reflected the effects of Russia\'s war of aggresion against Ukraine and the severe effects the restrictions have had on Swedish overflights, and the possibility of a reopening. For incentive purposes regarding 2025 the NOP delay forecast from May 2024 was used (please note that the incentive assessment is based on the NOP forecast rather than the reference values.). The delay forecast of Sweden was at the time 0,04. So, taking the lower traffic versus plan into account, the result for 2025 was anticipated.

### **Description of the adjustments to the capacity plan included in adopted performance plan**

No adjustments done. The main focus is on training ATCOs due to the demographic situation and also realizing the effects of SWEA and FIS project.

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

### **Recommendations to the ANSP to rectify the situation**

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

The capacity and the delays reported is not considered too call for specific remedial measures. The NSA and the main-ANSP have regular meetings to discuss different scenarios and capacity planning.

