## SAF1.1. Effectiveness of Safety Management (EoSM) (KPI#1)

[LFV]{.underline}

In 2025, LFV NUAC achieved the planned maturity levels set out in its performance plan for four out of five components. LFV NUAC missed the planned level in the Safety Risk Management component of the EoSM.

According to the monitoring report, Sweden notes that from Swedish experience the evaluation form via the EoSM reporting is a new form with slightly different criteria and evaluation forms. Sweden notes that LFV still has high focus on safety targets, but the new form gives different values in the table above even though the actual work has not differed. LFV has been on target in each area for several years and there are no indications through audits, reviews etc. that they do not fulfil the achieved levels.

In terms of main measures put in place to achieve the planned levels, the monitoring report defines the following elements:

- Well known SMS. Training in SMS. Yearly review of SMS.

- Regular review of hazards and risks and associated processes.

- A system for investigation and follow up of results. Internal audits. Follow up on targets.

- Refresher training and well established forms of communication.

- A reporting system and follow up (also investigative) that gives feedback to the reporter.

[ACR]{.underline}

In 2025, ACR achieved the planned maturity levels set out in its performance plan for four out of five components. ACR missed the planned level in the Safety Risk Management component of the EoSM.

In terms of main measures put in place to achieve the planned levels, the monitoring report defines the following elements:

- Established and well-known SMS. Training in SMS. Procedures for improvement of SMS.

- Risk and hazards are identified in change processes. Assessment of level of risk acceptable. New and updated processes for monitoring and evaluation of risks and hazards.

- System for handling of occurrence reports. Exchange with others for best practices. Internal audits.

- Refresher training. Monthly reports.

- Good reporting culture. Reports are disseminated. Safety culture surveys.

[AFAB]{.underline}

AFAB did not meet their planned target in four out of five components of the EoSM. AFAB reached the target only in the component of Safety Policy and Objectives.

Sweden notes in the monitoring report that AFAB has not reached all target levels. Evaluation is conducted via the EoSM-report, and the Swedish Transport Agency performed an extra audit during 2025 due to concerns regarding the safety culture. The company no longer preforms ATS. ACR is the ATSP in action from first of April 2026. In addition, AFAB has improved their safety risk management by reviewing risks annually, comparing risks against tolerability criteria, and training staff on how to reduce risk. AFAB has been working throughout the year to fill all vacancies in management. AFAB also works to improve in all areas based on recommendations from a safety culture audit.

In terms of main measures put in place to achieve the planned levels, the monitoring report defines the following elements:

- Well known SMS and policy. Yearly review of SMS. Management has safety on the agenda at meetings.

- Yearly review of risks and hazards. Training in risk reduction. New staff.

- Audit plan. Safety analysis twice a year. Trends are followed up.

- Training of staff, both internal and external. Follow up by safety survey. New staff.

- Feedback on reports. Take result from safety analysis into account for refresher training.

[SDATS]{.underline}

In 2025, SDATAS achieved the planned maturity levels set out in its performance plan for three out of five components. SDATS missed the planned level in the Safety Risk Management and Safety Promotion components of the EoSM.

In terms of main measures put in place to achieve the planned levels, the monitoring report defines the following elements:

- Well-established policy: An approach to disseminating the throughout the organization. Safety performance monitoring: Continuous tracking of safety metrics and outcomes.

- Well established hazard logs. Monitoring function. Safety action group.

- Internal audits. Safety review board. Monitoring function.

- Awareness training. Well disseminated chain of information.

- Reporting culture. Exchange of information with others.

