## PRB1.4. Environment {#prb1.4.-environment .Heading-2-ER}

- Sweden registered a KEA performance of 1.71% compared to its target of 1.73% and contributed positively towards achieving the Union-wide target. The NSA states performance is consistent with the target. This is despite still being affected by the restrictions concerning Russia (and Kaliningrad), which is reflected in the targets for RP4.

- KEP and KES remained stable in comparison with 2024.

- VFE of the actual trajectory was at 77.2%, which was better than the Union-wide average.

- The average time in level flight during descent and climb both deteriorated compared to 2024, but with performance remaining better than most other Member States.

- Additional taxi-out time was 2.65 min/flight which improved compared to 2024, and additional taxi-in time was 1.27 min/flight, which also improved compared to 1.44 min/flight in 2024.

- Additional time in the arrival sequencing and metering area deteriorated to 2.54 min/flight in 2025 from 2.18 min/flight in 2024.

