## **TZ1.3. SECTION 3 -- REGULATORY RESULT**

### **TZ1.3.1. LFV NET GAIN/LOSS ON ACTIVITY IN THE SWEDEN TERMINAL CHARGING ZONE IN 2025**

LFV reported a net loss of -0.2 M€, as a combination of a loss of -0.003 M€ arising from the cost sharing mechanism, with a loss of -0.3 M€ arising from the traffic risk sharing mechanism and a gain of +0.1 M€ relating to financial incentives.

### **TZ1.3.2. LFV OVERALL REGULATORY RESULT (RR) ON ACTIVITY IN THE TERMINAL CHARGING ZONE** 

Ex-post, since LFV does not report any terminal assets and, in turn, no RoE (see Note 1 below for details), the overall RR equals the net loss from the terminal activity mentioned above (-0.2 M€, some -1.4% of the terminal revenues).

### **TZ1.3.3. NOTES**

#### **TZ1.3.3.1. NOTE 1**

LFV does not report any terminal ANS assets, as these are owned by another ANSP (Swedavia), which is responsible for managing approach and airport infrastructure, including that used for the provision of ATS. Consequently, no ex-ante or ex-post regulatory result can be calculated for LFV at terminal level.

Therefore, when interpreting the actual cost-efficiency performance in the terminal charging zone and, in particular, the RR, both ANSPs should be considered together.

#### **TZ1.3.3.2. NOTE 2**
