## **2.3.1.B. KPI #2**

### **Identification and analysis of the reasons and circumstances resulting in the achieved level of actual performance of the arrival ATFM delay per flight KPI**

Only a few occasions in 2025 with arrival delay into Arlanda, mostly caused by weather events like snow or CBs in the TMA.

Historically, weather related issues like the ones referred to have always constituted, by far, most to restrictions/delays. This is also reflected in the incentive scheme determined by the NSA. For details see section on Terminal Incentives Capacity Scheme below.

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

### **Recommendations to the ANSP to rectify the situation**

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

