## ERT1.1. En route ATFM delay per flight (KPI#1)

-   Hungary had 1 198k flights in 2025, up from 1 100k flights in 2024.

-   HungaroControl applied en route ATFM regulations resulting in 660k minutes of delay, a significant reduction from the 2 895k minutes in 2024.

-   As part of the strategic traffic re-orientation programme (S25/NTDM) operated by the Network Manager, there were 46k minutes of en route ATFM delay reattributed **to HungaroControl** (plus 5k re-attributed to the KFOR sectors which fall outside the SES performance scheme); 36k minutes of delay originating in Budapest ACC were re-attributed **to other ANSPs.**

-   Under the auspices of the Route Network (RN) Scenarios during Capacity & Weather Based Operations between June and September 2025, an additional 16k minutes of en route ATFM delay were re-attributed **to HungaroControl** -- with \<1k minutes of delay originating in Budapest ACC, being re-attributed **to other ANSPs**.

-   When the above post-operations re-attributions are factored in, the total en route delay for HungaroControl in 2025 was 695k minutes in 2025 down from 3 014k minutes in 2024.

