## PRB1.7. Investments {#prb1.7.-investments .Heading-2-ER}

- HungaroControl planned a total asset value for new investments in RP4 of 175.4M€2022, of which 48.3% relates to new major investments. HungaroControl planned 6 new major investments for RP4, of which 4 have started and 2 have not yet started. HungaroControl reported 1 additional major investment not foreseen as part of the performance plan which has not yet started.

- In 2025, HungaroControl underspent -0.9M€2022 (-55.4%) in costs related to new major investments. This is mainly attributable to delayed developments.

- According to the reporting tables, HungaroControl underspent -4.5M€2022 (-11.9%) in costs related to investments in 2025. These amounts must be reimbursed to the airspace users through a reduction of future unit rate(s), unless the NSA decides after consultation with the users, that the ANSP must not reimburse a part of the difference according to article 28 of Regulation (EU) 2019/317.

- HungaroControl reported 0.1M€2022 in funding from Union assistance programmes in 2025.
