## PRB1.6. Cost-efficiency {#prb1.6.-cost-efficiency .Heading-2-ER}

- The en route 2025 actual unit cost of Hungary was 28.24€2022, -8.4% lower than the determined unit cost (30.81€2022). The terminal 2025 actual unit cost was 256.88€2022,

- -9.4% lower than the determined unit cost (283.49€2022).

- The en route 2025 actual service units (4.4M) were +9.5% higher than the determined service units (4.0M).

- The en route 2025 actual total costs were slightly higher than determined (+0.4M€2022, or+0.3%). This is entirely driven by higher staff costs, as all other cost categories registered lower costs than planned. Staff costs for HungaroControl were +4.9M€2022 higher than planned (+9.2%). The NSA explained this increase by higher-than-planned personnel expenditure related to measures for increasing capacity and pay rises reflecting inflation.

- A deviation from the criteria to achieve capacity targets was considered justified for Hungary. Actual costs for the measures necessary to achieve those targets were lower than determined (-0.8M€2022, or -11.7%), mainly due to lower other operating costs (-0.7M€2022, or -18.9%) than planned.

- HungaroControl spent 33.1M€2022 in 2025 related to costs of investments for both en route and terminal charging zones, -11.9% less than determined (37.5M€2022). The NSA explained that this reduction is mainly due to postponed investments and delayed developments.

- The en route actual unit cost incurred by users in 2025 was 32.66€ (-8.4% below the 2025 DUC), while the terminal actual unit cost incurred by users was 277.22€ (-13.7% below the 2025 DUC). The difference between the AUCU and the DUC for both terminal and en route charging zones is mainly driven by the traffic risk sharing adjustment.

