## PRB1.5. Capacity {#prb1.5.-capacity .Heading-2-ER}

- Hungary registered 0.55 minutes of average en route ATFM delay per flight during 2025, which has been adjusted to 0.58 during the post-ops adjustment process, thus achieving the local target value of 0.85. Delays in Hungary decreased by -2.17 minutes per flight year-on-year.

- Delays were highest in July, August and September, driven by a combination of ATC capacity, weather and other non-ATC causes.

- The share of delayed flights with delays longer than 15 minutes in Hungary decreased by -9 percentage points compared to 2024.

- The number of ATCOs in OPS was 117 being below the 2025 plan in Budapest ACC by -14 FTE.

- The yearly total of sector opening hours in Budapest ACC was 36,288, showing a 4% increase compared to 2024.

- Budapest ACC registered 31.83 IFR movements per sector opening hour in 2025, an increase of 5%.

- Hungary registered an average airport arrival ATFM delay of 0.04 minutes per flight in 2025, thus achieving the local target of 0.1 minutes. Compared to 2024, average arrival ATFM delays in Hungary were 0.04 minutes per flight higher in 2025.

