## **2.2.1.A. KPI #1**

### **Assessment of the achieved level of actual performance in the environment KPA**

Based on the decision of the European Commission, during RP4 the impact of the Ukrainian Russian conflict was taken into account when setting the target for horizontal en-route flight efficiency. As a result of this, the Hungarian performance in the first year of RP4 fully met the established target.

### **Has the ANSP implemented any major operational or structural changes (incl. any new fixed assets put into operation) during the calendar year impacting performance in this key performance area? Please outline the relevant changes and their estimated impact**

Since Hungary is a member of one of the largest European FRA systems, SEE FRA, and furthermore has a cross-border FRA operational agreement in place with Austria, which is part of SECSI FRA, no new measures were required to achieve the established target.

### **Progress on the implementation of the measures committed to in the ERNIP**

The cross border FRA operation between Hungary and Austria had been implemented in accordance with the ERNIP in fall 2024. The same kind of FRA operation with Croatia is planned for spring 2026, but the full merger of the SEE FRA and SECSI FRA is planned for 2029.

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

n/a

### **Recommendations to the ANSP to rectify the situation**

n/a

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

n/a

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

n/a

