## **TZ1.3. SECTION 3 -- REGULATORY RESULT**

### **TZ1.3.1. HASP NET GAIN/LOSS ON ACTIVITY IN THE GREECE TERMINAL CHARGING ZONE IN 2025**

HASP reported a net loss of -0.7 M€, as a combination of a loss of -0.6 M€ arising from the cost sharing mechanism, with a gain of +0.2 M€ arising from the traffic risk sharing mechanism and a loss of -0.4 M€ relating to financial incentives.

### **TZ1.3.2. HASP OVERALL REGULATORY RESULT (RR) ON ACTIVITY IN THE TERMINAL CHARGING ZONE** 

Ex-post, the overall RR, taking into account the net loss from the terminal activity mentioned above (-0.7 M€) and the actual RoE (+0.2 M€), amounts to -0.6 M€ (-2.3% of the terminal revenues). The resulting ex-post rate of return on equity is negative (-17.6%), compared to the 4.6% planned in the PP (see also Note 1 below).

### **TZ1.3.3. NOTES**

#### **TZ1.3.3.1. NOTE 1**

The ex-post RoE cannot be correctly calculated because of a very low total asset base, due to: 1) the exclusion of net current assets from the calculation of the total asset base; 2) a very low net book value of existing fixed assets in operation.

#### **TZ1.3.3.2. NOTE 2**
