## SAF1.3. Rate of runway incursions (RIs) (PI#1)

Greece reported 2 runway incursions (RI) at Athens airport during 2025. When comparing the RIs at airport level to Union-wide level, Greece was lower than Union-wide average (0.69 vs 2.53).

Greece reported 2 runway incursions with ATS/CNS contribution in 2025. When comparing airport level with ATS/CNS contribution to the Union-wide level, Greece was slightly below the Union-wide average (0.69 vs 0.96).

The rate of runway incursions has decreased compared to 2024 at airport level (0.69 vs 3.91) and remained stable at ATS/CNS contribution-level (0.69 vs 0.73).

The monitoring report notes that the improvements in both RI and SMI performance indicators are mainly through internal compliance monitoring, investigation of occurrences and systematic training of ATCOs.

The NSA notes in the monitoring report that it intends to monitor the effectiveness on performance mainly through the annual oversight cycle, oversight of occurrence reporting and oversight of change management.

