## **2.3.1.A. KPI #1**

### **Identification and analysis of the reasons and circumstances resulting in the achieved level of actual performance of the en-route ATFM delay per flight KPI**

The traffic increase experienced in 2025 resulted in capacity-related delays; however, their impact was mitigated by the additional availability of ATCOs under the agreement on extra shifts for the 2025--2027 period, combined with high tactical flexibility and the use of advanced ATFCM techniques. The capacity increase achieved during summer 2025 exceeded the initially forecast operational levels, indicating that the system responded more effectively than originally anticipated.Ηowever it was not sufficient to recover the pre-existing capacity gap.

### **Description of the adjustments to the capacity plan included in adopted performance plan**

The requirement for increased sector openings in 2026 will be partly addressed by the existing agreement for the period 2025-2027, the evolution of the recruitment plan, the planned airspace changes and the continuous flexibility in the use of advanced ATFCM.

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

The 2025 capacity target was not met primarily due to ATC staffing and secondarily due to Weather.

### **Recommendations to the ANSP to rectify the situation**

Adequate personnel (mainly ATCOs), proper rostering to meet anticipated demand and modernisation of infrastructure.

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

Materialisation of planned recruitment, modernisation of infrastructure, optional incentive to accelerate proper Capex deployment.

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

Planned recruitment targets have not been met so far, modernisation of infrastructure still pending.

