## **ER1.3.  SECTION 3 -- REGULATORY RESULT**

### **ER1.3.1. HASP NET GAIN/LOSS ON ACTIVITY IN THE GREECE EN ROUTE CHARGING ZONE IN 2025**

HASP reported a net gain of +5.7 M€, as a combination of a gain of +9.6 M€ arising from the cost sharing mechanism, with a loss of -1.3 M€ arising from the traffic risk sharing mechanism and a loss of -2.6 M€ relating to financial incentives.

### **ER1.3.2. HASP OVERALL REGULATORY RESULT (RR) FOR THE EN ROUTE ACTIVITY**

Ex-post, the overall RR, taking into account the net gain from the en route activity mentioned above (+5.7 M€) and the actual RoE amounts to +5.8 M€ (3.3% of the en route revenues). The resulting ex-post rate of return on equity is 592.6%, which is higher than the 4.6% planned in the PP (see also Note 1 below).

### **ER1.3.3. NOTES** 

#### **ER1.3.3.1. NOTE 1**

The ex-post RoE cannot be correctly calculated because of a very low total asset base which results from: 1) the exclusion of net current assets from the calculation of the total asset base, and 2) a very low net book value of existing fixed assets in operation.

#### **ER1.3.3.2. NOTE 2**

# **TZ1. TERMINAL CHARGING ZONE - GREECE**

