## **2.3.1.B. KPI #2**

### **Identification and analysis of the reasons and circumstances resulting in the achieved level of actual performance of the arrival ATFM delay per flight KPI**

The primary cause of the delays was excessive demand. In order to improve the situation, the following mitigation measures were adopted: additional availability of ATCOs in line with the agreement on extra shifts for the period 2025--2027, enhanced tactical flexibility, the application of advanced ATFCM techniques, and the use of PBN procedures.

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

Airport and terminal capapcity was not met primarily due to ATC capacity and staffing and secondarily due to Weather and ATC dispruptions.

### **Recommendations to the ANSP to rectify the situation**

Adequate personnel (mainly ATCOs), proper rostering to meet anticipated demand and modernisation of infrastructure.

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

Materialisation of planned recruitment, modernisation of infrastructure, optional incentive to accelerate proper Capex deployment.

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

Planned recruitment targets have not been met so far, modernisation of infrastructure still pending.

