## **TZ1.1. SECTION 1 -- UNIT COST**

### **TZ1.1.1. AUC VS. DUC**

In 2025, the terminal AUC was +1.0% (or +1.54 €2022) higher than the planned DUC. This results from the combination of higher than planned terminal costs in real terms (+1.9%, or +0.5 M€2022) and slightly higher than planned TNSUs (+0.9%).

### **TZ1.1.2. TERMINAL SERVICE UNITS**

The difference between actual and planned TNSUs (+0.9%) falls inside the ±2% dead-band. Hence, the gain of additional terminal revenues is kept by the ANSPs.

### **TZ1.1.3. TERMINAL COSTS BY ENTITY**

Actual real terminal costs are +1.9% (+0.5 M€2022) higher than planned. This is the result of higher costs for the main ANSP, HASP (+1.9%, or +0.5 M€2022) and the NSA (+6.3%, or +0.1 M€2022) and lower costs for the MET service provider (-12.5%).

### **TZ1.1.4. TERMINAL COSTS FOR THE MAIN ANSP (HASP) AT CHARGING ZONE LEVEL**

Based on the additional information to the terminal reporting tables, the slightly higher than planned terminal costs in real terms for HASP in 2025 (+1.9%, or +0.5 M€2022) result from:

- Significantly higher than planned staff costs (+5.8%), mainly driven by an increase in staff numbers.

- Significantly lower than planned other operating costs (-11.6%),

- Significantly lower than planned depreciation (-7.8%), mainly due to a delay in the implementation of two projects for Athens International Airport \"Eleftherios Venizelos\", which are expected to be put into operation in 2026 instead of 2025 as originally planned.

- Significantly lower than planned cost of capital (-9.0%), mainly due to the delay in the implementation of the investment plan.

- Slightly lower than planned deduction for VFR exempted flights (-0.4%).

### **TZ1.1.5. ASSESSMENT OF THE ACTUAL PERFORMANCE IN THE CHARGING ZONE REPORTED BY THE NSA**

The NSA of Greece provides the following overall assessment of the actual performance in 2025 at charging zone level:

"*There is a small increase in the actual real terminal unit cost compared with the determined one.*"

### **TZ1.1.6. EXPLANATION OF THE DIFFERENCES BETWEEN ACTUAL AND DETERMINED COSTS AT CHARGING ZONE LEVEL REPORTED BY THE NSA**

The NSA provides the following explanation for the differences between actual and determined costs in the charging zone:

"*Actual total terminal costs in real terms are 1.9% higher due to higher staff costs and higher than anticipated inflation.*"

### **TZ1.1.7. RECOMMENDATIONS FORMULATED BY THE NSA TO THE ANSP (HASP) TO RECTIFY THE SITUATION AND ACTIONS TAKEN BY THE ANSP**

No information was provided in the NSA 2025 Monitoring Report.

### **TZ1.1.8. NOTES**

#### **TZ1.1.8.1. NOTE 1**

#### **TZ1.1.8.2. NOTE 2**

