## **2.3.3 ATCO Planning 1**

### **Additional comments**

### **Additional comments**

The ACCs are physically co-located in terms of system and personnel, however the ATC procedures, staff and corresponding infrastructure throughout Greece concerns two distinct ACCs.

### **Description of the training process, including details on the effective failure rate and the process used to allocate newly qualified ATCOs between ACC, APP and TWR positions**

Allocation among ACC, APP and TWR positions is conducted prior to the qualification of ATCOs during their initial training based on the operational needs and the recruitment plan of HASP.The training process is in accordance with the provisions of EE 2015/340 as amended and in force and the relevant AMC of EASA and fully described in the relevant UTPs. All training is conducted in-house since HASP is certified by HCAA as an ATCO Training Organisation. The training programmes provided are:

-ATCO INITIAL TRAINING (BASIC+RATING)

-UNIT TRAINING (TRANSITIONAL-pre-OJT-OJT)

- CONTINUATION TRAINING (REFRESHER+CONVERSION)

- OJTI/STDI TRAINING

-ASSESSOR TRAINING

All above trainings are conducted according to the provisions of (EU) 2015/340, (EU) 2018/1139, ICAO Annex 1, Personnel Licensing.

Initial training for ATCOs lasts six to seven months and the unit training one to three years depending to the complexity of the unit, the provided services , the number of the necessary ratings/endorsements according to the UTPs e.tc.

Moreover all Greek ATCOs are highly qualified university graduates, succeeding in a demanding recruiting process and therefore the failure rate is minimal.

