## TRM1.5. Average departure delay from all causes per flight (PI#3)

Six German airports are subject to the monitoring of this indicator: Frankfurt, Munich, Berlin, Düsseldorf, Hamburg and Cologne/Bonn. All of them have decreased their average pre-departure delay by at least 10% and in one case up to a 35% reduction.

Delay in Frankfurt in 2025 decreased to 18.88 min/dep, 19% lower than 2024 value -- last year of RP3 -- of 23.17 min/dep.

Delay in Munich in 2025 decreased to 12.83 min/dep, 35% lower than 2024 value -- last year of RP3 -- of 19.66 min/dep.

Delay in Berlin in 2025 decreased to 16.04 min/dep, 10% lower than 2024 value -- last year of RP3 -- of 17.82 min/dep.

Delay in Düsseldorf in 2025 decreased to 14.19 min/dep, 15% lower than 2024 value -- last year of RP3 -- of 16.74 min/dep.

Delay in Hamburg in 2025 decreased to 14.42 min/dep, 22% lower than 2024 value -- last year of RP3 -- of 18.48 min/dep.

Delay in Cologne/Bonn in 2025 decreased to 17.61 min/dep, 20% lower than 2024 value -- last year of RP3 -- of 21.97 min/dep.

The average for RP4 airports subject to monitoring of all causes pre-departure delay across Member States in 2025 was 16.47 min/dep.
