## **ER1.2. SECTION 2 - ACTUAL UNIT COSTS INCURRED BY THE USERS**

### **ER1.2.1. FOCUS ON EN ROUTE AUCU MONITORING AT CHARGING ZONE LEVEL**

The actual en route unit cost incurred by airspace users (AUCU) in respect of activities performed in 2025 (77.90 €) is -0.7% lower than the nominal DUC (78.43 €) which includes DUC initially charged: 79.83 €, and DUC to be charged retroactively: -1.40 €. The difference between the AUCU and the nominal DUC (-0.53 €/SU) is due to:

- the positive inflation adjustment resulting from higher than planned inflation (+0.13 €/SU);

- the impact of adjustments resulting from the costs exempted from cost sharing mechanism (-0.14 €/SU);

- the deduction of the traffic adjustment (-0.04 €/SU) for the costs not subject to traffic risk sharing;

- the impact of financial incentives (-0.32 €/SU); and,

- the deduction of other revenues (-0.15 €/SU).

The share of the regulatory result (see next sub-section) in the AUCU (before the deduction of other revenues) is 3.8%.

Costs exempt from cost sharing for 2025 presented here are based on preliminary figures and remain subject to revision pending the receipt of the NSA Reports on the verification of cost sharing due by 1 September 2026. Any changes may affect the analysis of Actual Costs for Users and the Regulatory Results.

### **ER1.2.2. INITIATIVES IMPLEMENTED OR PLANNED THAT WILL IMPROVE THIS PI REPORTED BY THE NSA**

The NSA of Germany provides the following information regarding the initiatives:

*"During the last years the PI was primarily influenced by adjustments for traffic risk sharing and inflation as well as the incurred malus from the incentive scheme. The indicator is monitored on an ongoing basis while the possibility and necessity of a regulatory adjustment through Art. 29(6) is being assessed respectively.*

*Referring to (...) the cost-exempt from cost-sharing, please be aware that the value provided is provisional since the verification in accordance with Article 28 (7) of IR (EU) 2019/317 is not yet finalised since it is only due by 1 September 2026."*

### **ER1.2.3. NOTES** 

#### **ER1.2.3.1. NOTE 1**

#### **ER1.2.3.1. NOTE 2**

