## TRM1.4. Air traffic control pre-departure delay (PI#2) {#trm1.4.-air-traffic-control-pre-departure-delay-pi2 .Heading-2-TZ}

Six German airports are subject to the monitoring of this indicator: Frankfurt, Munich, Berlin, Düsseldorf, Hamburg and Cologne/Bonn. However, the share of unidentified delay reported by Cologne/Bonn was above 40% for more than 2 months in the year during the entire RP3, preventing the calculation of this indicator for this airport.

Delay in Frankfurt in 2025 was equal to 0.13 min/dep, very close to 2024 value -- last year of RP3 -- of 0.11 min/dep.

Delay in Munich in 2025 was equal to 0.02 min/dep, whereas in 2024 - last year of RP3 -- there was no reported ATC pre-departure delay.

Delay in Berlin in 2025 was equal to 0.40 min/dep, very close to 2024 value -- last year of RP3 -- of 0.39 min/dep.

Delay in Düsseldorf in 2025 was equal to 0.11 min/dep, the same as 2024 value-- last year of RP3.

Delay in Hamburg in 2025 was equal to 0.37 min/dep, very close to 2024 value-- last year of RP3 -- of 0.42 min/dep.

The average for RP4 airports subject to monitoring of ATC pre-departure delay across Member States and for which enough data is available in 2025 was 0.74 min/dep.

