## 2.3.2.E. PI #5

### Please provide background information on the actual performance: - If performance improved compared to previous years, please describe the measures that were implemented (if any), - If performance deteriorated compared to previous years, please explain the reasons which lead to the deterioration, and describe the improvement measures which are planned to improve performance. How does the NSA intend on monitoring their effectiveness on performance

With the specifics of traffic in the different airspaces under their responsibilites, the values are hardly comparable between different area control centres. This indicator will therefore become more interesting during the course of RP4. Yet, already the comparison of the values for EDWW, EDUU, EDGG, EDMM show, that not only did they handle more traffic with less delay, especially in the categories capacity and staffing, but also did the throughput increase by between 2,7% (EDWW) and 14,8% (EDUU). The German NSA concludes that the additional traffic did at least to a relevant degree occurr in peak hours, which makes the development of CAP KPI#1 even more noticable.

