## TRM1.3. Additional time in terminal airspace (PI#6)

Six German airports are subject to the monitoring of this indicator: Frankfurt, Munich, Berlin, Düsseldorf, Hamburg and Cologne/Bonn. In most cases there was less than 0.1 minutes of difference compared to 2024.

Additional time in Frankfurt in 2025 increased to 3.05 min/arr, 6% higher than 2024 value -- last year of RP3 -- of 2.87 min/arr.

Additional time in Munich in 2025 increased to 2.76 min/arr, 6% higher than 2024 value -- last year of RP3 -- of 2.61 min/arr.

Additional time in Hamburg in 2025 was equal to 2.39 min/arr, very close to 2024 value -- last year of RP3 -- of 2.34 min/arr.

Additional time in Berlin in 2025 was equal to 2.34 min/arr, very close to 2024 value -- last year of RP3 -- of 2.38 min/arr.

Additional time in Düsseldorf in 2025 was equal to 1.99 min/arr, very close to 2024 value -- last year of RP3 -- of 1.95 min/arr.

Additional time in Cologne-Bonn in 2025 was equal to 1.91 min/arr, very close to 2024 value -- last year of RP3 -- of 1.98 min/arr.

The average for RP4 airports subject to monitoring of this indicator across Member States in 2025 was 2.98 min/arr.

