## SAF1.3. Rate of runway incursions (RIs) (PI#1)

Germany reported 70 runway incursions (RI) during 2025 for all airports listed in the performance plans (15). When comparing the rate of RIs at airport level to Union-wide level, Germany was higher than Union-wide average (3.69 vs 2.53).

Germany reported 14 runway incursions with ATS/CNS contribution in 2025. When comparing the rate of RIs at airport level with ATS/CNS contribution, Germany was slightly lower than Union-wide average (0.74 vs 0.96).

The rate of runway incursions at both levels has increased compared to 2024, when Germany reported 0 RIs.

As described in the monitoring report, as part of the occurrence management at DFS, each reported RI and SMI is analysed individually and, if necessary, lessons are derived from the insights and measures are developed to prevent recurrence of the safety-relevant event as far as possible. Furthermore, trend analyses are performed continuously, taking into consideration information from all SMS processes.

The monitoring report also states that BAF monitors the effectiveness following 373 and 376 of the applicable EU Regulation, ensuring that occurrence management and the derivation of safety measures are appropriately implemented.

