## 2.2.1.A. KPI #1

### Assessment of the achieved level of actual performance in the environment KPA

In 2025, the target in the KPA environment has been met, as KEA reached a value of 2,47 %. This value is 0,15 percentage points below the target, and also below the KEA value of 2024 (2,53 p.p.).

Source of above shown values: SES DB (https://www.sesperformance.eu/dataportal/vis/2025/)

### Has the ANSP implemented any major operational or structural changes (incl. any new fixed assets put into operation) during the calendar year impacting performance in this key performance area? Please outline the relevant changes and their estimated impact

In 2025, ten out of thirteen AIRACs have been used for several route changes. The PYXIS/ZEBRA implementation in March 2025 was successful improving the overall capacity in Bremen ACC and Maastricht UAC with increased MME (military mission effectiveness). Throughout the year en-route and RAD updates were implemented to accompany the various PBN implementations for several airports in accordance with CP1.

Besides that, the major change has been made through flight plan adherence. In 2025, air traffic controllers were instructed not to issue non-standard flight level clearances or shortcuts in order to avoid undermining regulated airspace.

### Progress on the implementation of the measures committed to in the ERNIP

DFS confirms that all planned ERNIP measures have been implemented as foreseen.

### Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved

### Recommendations to the ANSP to rectify the situation

### Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why

### Follow up of the remedial measures indicated in the previous monitoring report(s)

The status of the following measures indicated in previous monitoring reports changed:

1\. ERL/DON sector optimization: The division level between 2nd and 3rd sector has been raised. That measure has proven successful.

2\. Karlsruhe UAC re-design sector group South Part 1: The old sectors ISA and CHI have been merged to form the new AMM sector. As fewer personel is needed to monitor that new sector an increase in capacity was acchieved. Implementation was finished March 2026.

3\. Karlsruhe UAC re-design sector group South Part 2: Lateral optimization of ERL/DON sectors is currently in planning.

The status of further indicated measures hasn\'t changed compared to the 2024 monitoring report.

