## ERT1.2. En route capacity incentive scheme {#ert1.2.-en-route-capacity-incentive-scheme .Heading-2-ER}

The FABEC NSAs report that, because the overall FABEC capacity incentive target was missed, no FABEC ANSP could be eligible for a bonus. However, financial penalties could still be imposed.

Individual en route incentive targets were set for both DFS and MUAC (global).

For DFS, the local incentive target for en route ATFM delays, due to CRSTMP causes only, was set at 0.26 mins/flight, (with a deadband of +/- 0.05 mins).

The FABEC NSAs report an achieved CRSTMP performance, for DFS, of 0.57 mins/flight using data from the ansperformance.eu dashboard including post ops adjustments. \[NB The attribution of original delay causes on the ansperformance.eu dashboard is unverified.\]

Subsequently, DFS is liable for a financial penalty of € 4 809 209, for its 2025 en route capacity performance.

For MUAC, the local incentive target for en route AFTM delays, due to CRSTMP causes only, was set at 0.19 mins/flight, (with a deadband of +/- 0.04 mins).

The FABEC NSAs report an achieved CRSTMP performance, for MUAC, of 0.18 mins/flight using data from the ansperformance.eu dashboard including post ops adjustments. \[NB The attribution of original delay causes on the ansperformance.eu dashboard is unverified.\]

The en route incentive capacity performance for MUAC fell inside the deadband, where no malus is applicable.

