## PRB1.4. Environment {#prb1.4.-environment .Heading-2-ER}

- Germany registered a KEA performance of 2.47% compared to the local breakdown value of 2.62%. Whilst the FABEC target was not achieved, Germany contributed positively towards Union-wide performance.

- Both KEP and KES remained improved in comparison with 2024. The improvement in KES shows that Germany has improved the element of horizontal flight efficiency that is under its control.

- VFE of the actual en route trajectory was at 77.2%, which was better than the average Union-wide performance.

- The average time in level flight during descent and climb were both stable compared to 2024, with minor deteriorations in performance compared to 2024.

- Additional taxi-out time was stable in 2025 compared to 2024 and additional taxi-in time was 1.75 min/flight which improved marginally compared to 1.83 min/flight in 2024.

- Additional time in the arrival sequencing and metering area deteriorated marginally to 2.64 min/flight from 2.53 min/flight in 2024.

