## PRB1.5. Capacity {#prb1.5.-capacity .Heading-2-ER}

- Germany registered 0.89 minutes of average en route ATFM delay per flight during 2025, which has been adjusted to 0.95 during the post-ops adjustment process, thus not achieving the local target value of 0.39. Delays in Germany decreased by -0.61 minutes per flight year-on-year.

- Delays were highest in June and July, mostly driven by weather and ATC capacity.

- The share of delayed flights with delays longer than 15 minutes in Germany decreased by -7 percentage points compared to 2024.

- The 2025 actual number of ATCOs in OPS across the four German ACCs was 1,230, which was 1% above the planned level 1,217. Actual ATCOs in OPS were higher than the planned level for Langen ACC (+5%), while for Munich ACC this was -2% lower. For Karlsruhe UAC and Bremen ACC the actual number of ATCOs was in line with the planned level.

- The yearly total of sector opening hours across all the German ACCs was 424,216, -4% lower than in 2024. Bremen, Langen and Munich ACCs all had a reduction in sector opening hours by over -5% compared to 2024, while for Karlsruhe UAC the reduction was less marked (-1%).

- Bremen ACC registered 6.52 IFR movements per sector opening hour in 2025, being 7% above 2024 levels. Karlsruhe UAC registered 13.85 IFR movements per sector opening hour in 2025, 5% above 2024 levels. Langen ACC registered 10.24 IFR movements per sector opening hour in 2025, 10% above 2024 levels. Munich ACC registered 10.97 IFR movements per sector opening hour in 2025, 12% above the 2024 level.

- Germany registered an average airport arrival ATFM delay of 0.37 minutes per flight in 2025, thus achieving the local target of 0.43 minutes. Compared to 2024, average arrival ATFM delays in Germany were -0.09 minutes per flight lower in 2025.

- The main drivers of delays were weather, accounting for 0.30 of the total delays, and other non-ATC causes, responsible for 0.06.

