## **TZ1.1. SECTION 1 -- UNIT COST**

### **TZ1.1.1. AUC VS. DUC**

In 2025, the terminal AUC was -1.6% (or -3.96 €2022) lower than the planned DUC. This results from the combination of lower than planned terminal costs in real terms (-2.1%, or -6.7 M€2022) and slightly lower than planned TNSUs (-0.5%).

### **TZ1.1.2. TERMINAL SERVICE UNITS**

The difference between actual and planned TNSUs (-0.5%) falls inside the ±2% dead-band. Hence, the loss of terminal revenues is borne by the ANSPs.

### **TZ1.1.3. TERMINAL COSTS BY ENTITY**

Actual real terminal costs are -2.1% (-6.7 M€2022) lower than planned. This is the result of lower costs for the main ANSP, DFS (-1.8%, or -5.8 M€2022), the MET service provider (-15.0%, or -0.7 M€2022) and the NSA (-15.0%, or -0.2 M€2022).

### **TZ1.1.4. TERMINAL COSTS FOR THE MAIN ANSP (DFS) AT CHARGING ZONE LEVEL**

Based on the additional information to the terminal reporting tables, the slightly lower than planned terminal costs in real terms for DFS in 2025 (-1.8%, or -5.8 M€2022) result from:

- Slightly lower than planned staff costs (-0.9%), mainly due to lower than planned ATC staff.

- Slightly higher than planned other operating costs (+0.3%).

- Significantly lower than planned depreciation (-16.0%), mainly due to "*changes in the projects MaRS and TANGe*".

- Significantly lower than planned cost of capital (-8.8%), which is understood to mainly reflect the fact that the actual cost of capital is netted off using an *"interest income from temporarily invested fixed deposits"* (see also the analysis of Regulatory Result for details).

- No deduction of exceptional costs which were included as part of the determined cost-base for DFS for 2025 (negative amount). This negative amount of -1.6 M€ (in nominal terms) which was used to reduce the chargeable cost base for 2025 is understood to be related to depreciation costs charged to the airspace users but not spent during RP2.

### **TZ1.1.5. ASSESSMENT OF THE ACTUAL PERFORMANCE IN THE CHARGING ZONE REPORTED BY THE NSA**

The NSA of Germany provides the following overall assessment of the actual performance in 2025 at charging zone level:

*"Actual overall costs were below determined costs in 2025 mainly due to depreciation. Staff costs and costs of capital were also below respective determined values but to a lesser extend. Actual unit costs were below DUC but lower than expected traffic partially offset the positive cost development.*

*Note: The determined costs for DFS in 2025 included an exceptional item for depreciation costs charged but not spent during RP2. They lowered the amounts charged to airspace users in 2025 but aren\'t reflected in the actual costs structure of the given year."*

### **TZ1.1.6. EXPLANATION OF THE DIFFERENCES BETWEEN ACTUAL AND DETERMINED COSTS AT CHARGING ZONE LEVEL REPORTED BY THE NSA**

The NSA provides the following explanation for the differences between actual and determined costs in the charging zone:

*"DFS: Lower than planned staff costs are rooted in a reduced number of ATCOs. The largest cost reduction is observed within depreciation due to changes and delays in the projects MaRS and TANGe. Lower costs of capital stems from higher-than-expected interest income on temporarily invested fixed deposits.*

*DWD: Staff costs, especially pension costs, were below planned values and are the main contributor to lower actual costs.*

*NSA: Changes in actual costs are mainly rooted in expenses for personnel as actual staffing level is below the planned staffing level. Furthermore, costs for temporary workers are shown within other operating costs instead of staff costs which slightly increased the other operating costs."*

### **TZ1.1.7. RECOMMENDATIONS FORMULATED BY THE NSA TO THE ANSP (DFS) TO RECTIFY THE SITUATION AND ACTIONS TAKEN BY THE ANSP**

The NSA 2025 monitoring report indicates the following recommendations formulated by the NSA:

*"As regards DFS, the NSA recommends adhering to planned investment schedules more strictly and monitoring upcoming delays in project schedules more closely."*

DFS reports the implementation of the following actions:

*"DFS is committed to adhering to the investment schedule as laid out in the performance plan and implementing planned measures on time. Any shortfalls are analysed and, if possible, actively managed to minimise delays in current and future investment implementation."*

### **TZ1.1.8. NOTES**

#### **TZ1.1.8.1. NOTE 1**

#### **TZ1.1.8.2. NOTE 2**

