## 2.3.1.B. KPI #2

### Identification and analysis of the reasons and circumstances resulting in the achieved level of actual performance of the arrival ATFM delay per flight KPI

The performance in 2025 regarding KPI#2 at German airports was within the target and showed a slight improvement compared to the previous year. 80% of the ATFM arrival delay were caused by adverse weather situations. Delays directly attributable to the performance of the ANSP occurred in isolated events.

### Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved

N/A

### Recommendations to the ANSP to rectify the situation

N/A

### Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why

Any remaining staffing issues at DFS are tackeled with the intensified ATCO recruitment and training. Technical issues regarding voice-/radio communication and radio in tower EDDF derived from a faulty software update. The issue was solved with another update at the beginning of 2026.

### Follow up of the remedial measures indicated in the previous monitoring report(s)

The agreed collaborative wheather mitigation measures at EDDF developed in 2025 are being monitored and further developed. Together with the other remedial measures, it is subject to monitoring by the German NSA.

