## **2.2.1.A. KPI #1**

### **Assessment of the achieved level of actual performance in the environment KPA**

The slight improvement in KEA in 2025 is mainly driven by changes in traffic composition. Asian longhaul cargo traffic has contributed positively to the aggregated KEA value. The effects of sanctions and the continued closure of Russian airspace remain unchanged and the resulting rerouting patterns have stabilised.

### **Has the ANSP implemented any major operational or structural changes (incl. any new fixed assets put into operation) during the calendar year impacting performance in this key performance area? Please outline the relevant changes and their estimated impact**

No major operational or structural changes in 2025.

### **Progress on the implementation of the measures committed to in the ERNIP**

FRA is fully implemented in Estonia. Preparations for the implementation of FINEST continued in 2025. The impact on environmental KPIs will be assessed once the first sector becomes operational in 2027. The Borealis ENV WG met in 2025 and discussions focused on environmental performance indicators, including contrails, as well as the exchange of best practices and enhanced collaboration among participating ANSPs.

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

### **Recommendations to the ANSP to rectify the situation**

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

The situation remains unchanged compared to the previous reporting period. The main factors affecting KEA remain outside the control of both the ANSP and the NSA.

