## **2.3.3 ATCO Planning 1**

### **Additional comments**

In 2025, the ANSP employed a total of 39 ATCO FTEs in operations (OPS) allocated to the en route cost base. This consists of 25 FTEs in ACC, 14 FTEs in APP, and 0 FTEs in TWR. Additionally, 14 FTEs were allocated to other duties.

### **Additional comments**

ACC ATCO FTEs are based on the actual working hours report, showing 25 FTEs operational at the ACC level in 2025. Since no new ACC ATCOs were recruited, this means more working hours were dedicated to ACC operations, resulting in a corresponding reduction in other OPS and non-OPS (ADMIN) sectors.

### **Description of the training process, including details on the effective failure rate and the process used to allocate newly qualified ATCOs between ACC, APP and TWR positions**

The allocation of air traffic controllers is based on traffic volume forecasts.

In 2025, one trainee who started training in 2024 did not successfully complete the course. The low rate of possible failures is because pre-COVID ATCOs are prioritised restoring competences.

Unit training for EETN ADC is 90 hours, but not less than 1 month and EETN APS and ACS 180 hours, but not less than 3 months. Unit training is carried out by EANS. Unit training consists of transitional, simulator and on-the-job training phases.

ATCO Basic training is carried out annually by the Estonian Aviation Academy, ensuring availability of candidates for future operational needs.

