## **2.3.1.A. KPI #1**

### **Identification and analysis of the reasons and circumstances resulting in the achieved level of actual performance of the en-route ATFM delay per flight KPI**

The actual performance is better than the target value of 0,06. This reflects the continued low level of traffic in the Estonian airspace influenced by the geopolitical situation in the region. The low level of delay shows that capacity is not a limiting factor and that the system is able to absorb traffic demand, including a moderate increase in flights driven by Asian cargo operations.

### **Description of the adjustments to the capacity plan included in adopted performance plan**

When setting the performance targets for RP4 Estonia adopted a cautious and forward looking approach.

This approach reflects the significant uncertainty related to traffic development in the region due to the impact of geopolitical and trade developments. Estonia has experienced a substantial reduction in traffic in recent years, but future developments remain uncertain, including the possibility of traffic recovery or sudden changes in traffic flows.

Therefore, maintaining a more conservative target ensures that sufficient capacity is planned and preserved to accommodate potential increases in demand.

NSA will continue to monitor traffic evolution and capacity utilisation and if needed will assess whether adjustments to the capacity plan are required in the future.

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

### **Recommendations to the ANSP to rectify the situation**

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

In 2025 the number of ATCO fatigue related reports decreased, indicating an improvement compared to the previous year. This suggests that the increased focus on fatigue management, including targeted monitoring and Fatigue Safety Action Group recommendations has contributed to mitigating fatigue related risks.

