## SAF1.4. Rate of separation minima infringements (SMIs) (PI#2)

At State level, Estonia reported 5 separation minima infringements (SMI) in their airspace during 2025. The rate of separation minima infringements was slightly higher than Union-wide average (7.98 vs 7.10). At ANSP level, Estonia reported 4 SMIs with ATS/CNS contribution. The rate of separation minima infringements at ANSP level was slightly higher than the Union-wide average (6.39 vs 6.0).

When comparing to 2024, the rate of separation minima infringements has increased at both State level (7.98 vs 4.87) and at ANSP level (6.39 vs 4.87).

As described in the monitoring report, Estonia notes that the occurrence rate remains very low in relation to the number of flights and separation minima infringements are therefore not addressed in the State Safety Plan. Earlier ATM system software updates for conflict detection are considered effective mitigation measures.

Furthermore, the monitoring report states that EANS continues to review incidents and implement corrective measures. The Estonian Transport Administration monitors their effectiveness through audits. Overall, the level remains low and the safety performance can be considered stable.

