## PRB1.6. Cost-efficiency {#prb1.6.-cost-efficiency .Heading-2-ER}

- The en route 2025 actual unit cost of Croatia was 33.78€2022, -8.6% lower than the determined unit cost (36.96€2022). Croatia does not have a terminal charging zone.

- The en route 2025 actual service units (3.2M) were +6.8% higher than the determined service units (3.0M).

- The en route 2025 actual total costs were -2.6M€2022 (-2.4%) lower than determined, with all cost categories registering lower-than-planned costs, except staff costs. This is mainly due to lower other operating costs (-2.8M€2022, or -15.1%) and depreciation (-2.5M€2022, or -18.4%) for Croatia Control. The NSA explained this decrease by the deferral of investment projects which resulted in lower-than-expected expenditures, as well as lower intellectual services and travel costs. This was partially compensated by higher staff costs than planned (+3.7M€2022, or +5.8%) for Croatia Control, which the NSA attributed to an adjustment of labour expenses reflecting inflationary pressures.

- Croatia Control costs of investments were 15.5M€2022 in 2025, -14.4% less than determined (18.0M€2022). According to the NSA, this is mainly due to delays in the entry into operation of some projects and reduced availability of ATCOs for non-operational duties.

- The en route actual unit cost incurred by users in 2025 was 37.96€ (-7.5% below the 2025 DUC). The difference between the AUCU and the DUC is mainly driven by other revenues and the traffic risk sharing adjustment.

