## SAF1.1. Effectiveness of Safety Management (EoSM) (KPI#1)

In 2025, Croatia Control achieved the planned maturity levels set out in its performance plan for all five components of the EoSM.

Croatia Control exceeded the planned maturity levels in Safety Policy and Objectives.

As described in the monitoring report, the Croatia Control's (CCL) Safety Management System is constantly achieving target maturity levels in accordance with EoSM. SMS is monitored by CCL internal and external processes, as well as by the NSA via continuous oversight where service provider is expected to provide evidence. CCL regularly updates its compliance matrix on the basis of which it regularly demonstrates compliance with the requirements.

As for the measures put in place to achieve the safety performance targets, the monitoring report states that Croatia Control operates a proactive safety management system that aims to identify safety risks early and to limit, mitigate, or avoid these risks. Three main leading safety performance indicators, which are closely monitored at Croatia Control, are the Effectiveness of the Safety Management System (SMS), the application of the severity classification of the Risk Analysis Tool (RAT) and the reporting of Just Culture. Lagging safety performance indicators such as the trend in separation infringements provide additional data which help to establish safety trends. The safety processes have met the high standards and will continue to develop to continue meeting and exceeding the expectations. Croatia Control\'s Safety Management System is constantly achieving target maturity levels in accordance with EoSM. Croatia Control Annual Report is published on the CCL website and contains Safety data and KPI\'s. Usage of Safety Tools (ETOKAI, ASMT, CMMS and other) makes possible to monitor day to day safety performance. NSA is conducting a continuous oversight to assure that measures are put in place in order to achieve safety performance targets.

