# TZ1. TERMINAL CHARGING ZONE - ROMANIA ZONE 1

## TZ1.1. SECTION 1 – UNIT COST

### TZ1.1.1. AUC VS. DUC

In 2025, the terminal AUC was 0.0% (or -0.08 RON2022, -0.02 €2022) lower than the planned DUC. This results from the combination of significantly higher than planned TNSUs (+7.7%) and significantly higher than planned terminal costs in real terms (+7.7%, or +9.7 MRON2022, +2.0 M€2022). It should be noted that the actual inflation index in 2025 was +2.9 p.p. higher than planned.

### TZ1.1.2. TERMINAL CHARGING ZONE 1 SERVICE UNITS

The difference between actual and planned TNSUs (+7.7%) falls outside the ±2% dead-band, but does not exceed the ±10% threshold foreseen in the traffic risk sharing mechanism. The resulting gain of additional terminal revenues is therefore shared between the ANSP and the airspace users (see the main ANSP regulatory result).

### TZ1.1.3. TERMINAL CHARGING ZONE 1 COSTS BY ENTITY

Actual real terminal costs are +7.7% (+2.0 M€2022) higher than planned. This is the result of higher costs for the main ANSP, ROMATSA (+7.7%, or +2.0 M€2022) and the NSA (+10.0%, or +0.0 M€2022).

### TZ1.1.4. TERMINAL CHARGING ZONE 1 COSTS FOR THE MAIN ANSP (ROMATSA) AT CHARGING ZONE LEVEL

Based on the additional information to the terminal reporting tables, the significantly higher than planned terminal costs in real terms for ROMATSA in 2025 (+7.7%, or +2.0 M€2022) result from:

- Significantly higher than planned staff costs (+7.4%),

- Significantly higher than planned other operating costs (+7.4%),

- Significantly higher than planned depreciation (+10.0%),

- Significantly higher than planned cost of capital (+10.0%).

### TZ1.1.5. ASSESSMENT OF THE ACTUAL PERFORMANCE IN THE CHARGING ZONE REPORTED BY THE NSA

The NSA of Romania provides the following overall assessment of the actual performance in 2025 at charging zone level:

insert information from monitoring report

### TZ1.1.6. EXPLANATION OF THE DIFFERENCES BETWEEN ACTUAL AND DETERMINED COSTS AT CHARGING ZONE LEVEL REPORTED BY THE NSA

The NSA provides the following explanation for the differences between actual and determined costs in the charging zone:

insert information from monitoring report

### TZ1.1.7. RECOMMENDATIONS FORMULATED BY THE NSA TO THE ANSP (ROMATSA) TO RECTIFY THE SITUATION AND ACTIONS TAKEN BY THE ANSP

The NSA 2025 monitoring report indicates the following recommendations formulated by the NSA:

insert information from monitoring report

ROMATSA reports the implementation of the following actions:

insert information from monitoring report

### TZ1.1.8. NOTES

#### TZ1.1.8.1. NOTE 1

#### TZ1.1.8.2. NOTE 2
