## **2.2.2.F. PI #6**

### **What initiatives were implemented or are planned that will improve this PI and how does the NSA intend on monitoring their effectiveness on performance?**

The NSAs are monitoring the performance by using the SES dashboards

https://www.sesperformance.eu/dataportal/vis/2025/

Direct coordination between NSAs and ANSPs is done regularly and additionally ad-hoc when required. The FABEC Performance Management Group also provides additional reports to the FABEC Financial and Performance Committee (FPC) where required.

\-\-- Germany \-\--

DFS is constantly optimising its approach system in order to improve capacity (open STARS)

and to reduce detours (adjustments in IAPs during PBN transition).

\-\-- Netherlands \-\--

No specific measures are planned. Performance is significantly driven by usage of parallel runways, for which traffic is lined up further from the runway than for non-parallel approaches, to ensure vertical separation when turning to base leg. The performance during non-parallel approaches determines the reference time. The runway combination itself depends largely on weather conditions and using noise preferent runways as much as possible, as is as such difficult to steer by LVNL.

\-\-- Switzerland \-\--

In LSZH, XMAN, AOP (thanks to the TTA used through the TTMS tool implemented by Zurich Airport) and Leading Optimised Runway Delivery (LORD) projects should help improving performance.

In LSGG, the deployment of an AMAN and LORD should help improve the performance.

\-\-- France \-\--

Values for LFPO and LFPG achievements are standard thanks to AMAN/XMAN implementation. Improved AMAN usage at LFMN and extended AMAN with LFMM should enable better results as from 2026.

\-\-- Belgium \-\--

skeyes : no initiative is currently planned at skeyes.

### **If the data at airport level are not available, please explain the reasons why data is missing and describe the measures planned to resolve the situation**

N/A

