## **2.2.1.A. KPI #1**

### **Assessment of the achieved level of actual performance in the environment KPA**

FABEC-LEVEL ASSESSMENT:

In 2025, FABEC did not achieve its en route horizontal flight efficiency target. The actual KEA value of 3.06% exceeded the target of 2.89% by 0.17 percentage points. The shortfall is attributable to France, which was the only FABEC state not to achieve its national KEA target. All other FABEC States met or outperformed their respective targets.

Germany achieved a KEA of 2.47% against a target of 2.62%, a continued improvement also compared to 2024 (2.53%). The Netherlands achieved its KEA target with a slight improvement compared to 2024. Switzerland achieved 4.14% against a target of 4.34%, slightly below 2024 levels due to increased traffic pressure at the Swiss FIR interfaces. France KEA reached a value of 3,32% vs the target set at the value of 2,87% (quite similar to previous years and slightly better than in 2023).

\-\--

Germany:

In 2025, the target in the KPA environment has been met, as KEA reached a value of 2,47 %. This value is 0,15 percentage points below the target, and also below the KEA value of 2024 (2,53 p.p.).

Source of above shown values: SES DB (https://www.sesperformance.eu/dataportal/vis/2025/)

\-\--

Netherlands:

The Netherlands achieved the KEA target in 2025. The performance slightly improved compared to 2024.

\-\--

Switzerland:

In 2025, Switzerland has met its KPA environment target, with the KEA reaching 4.14% compared to the goal of 4.34%, a difference of 0.20 percentage points.

Performance slightly decreased in 2025 compared to 2024 due to increased traffic which is the main factor for a deterioration of flight trajectories. The positive trend set by the Free Route Airspace (FRA) in 2023 and 2024 while still playing may have reach its limit for absobing new trafic without impairing too drastically KEA. Trafic forecast

The expansion and growing use of Free Route Airspace (FRA) enables more direct and efficient flight planning. While FRA had a limited effect on KEA, it significantly improved KEP performance, especially at the Swiss-German border (cross-border FRA), allowing for more direct planned routes. These more efficient trajectories reduce fuel consumption, as aircraft can carry less fuel and thus fly lighter.

Within Switzerland, the internal KEA component stands at 0.8%, indicating that 99.2% of trajectories between CH FIR entry and exit points are direct showing stability. The most notable improvement from 2023 occurred at the CH FIR interface, with a 10% efficiency gain, likely due to cross-border FRA enhancements and fewer industrial actions in neighboring countries.

This case once again highlights that the KEA indicator does not fully reflect the performance of the air navigation service provider. Performance is influenced by multiple interdependent factors, such as safety, capacity, cost-efficiency, and weather, and responsibility is shared among various stakeholders, including airspace users and the Network Manager (NM).

\-\--

France:

In 2025, the target has not been met, as KEA reached a value of 3,32%, where the target was set at the value of 2,87%. Performance was quite similar to previous years, which is slightly better than in 2023.

As it has already been the case during the previous years, there are strong interdependencies between horizontal flight efficiency, ATFM delays and traffic levels In 2025, as it is described in the en route capacity monitoring chapters, the performance has still been impacted by capacity and staffing issues at Reims & Brest ACCS but mainly strongly impacted by Marseille ACCs low performance and very high en route ATFM delays (see en route capacity chapter), generating major rerouting and longer routes for a large amount of flights.

\-\--

Belgium:

Free Route Airspace (FRA) is considered the largest enabler for improving KEA. However, upper airspace in Belgium (above FL245) is delegated to MUAC and is therefore out of scope for skeyes. Additionally as KEA is a horizontal en-route flight efficiency indicator, an area of 40 nm around the origin & destination airport is excluded from the calculation. This leaves only little room for improvement within skeyes airspace.

\-\--

MUAC: Not applicable

### **Has the ANSP implemented any major operational or structural changes (incl. any new fixed assets put into operation) during the calendar year impacting performance in this key performance area? Please outline the relevant changes and their estimated impact**

DFS:

In 2025, ten out of thirteen AIRACs have been used for several route changes. The PYXIS/ZEBRA implementation in March 2025 was successful improving the overall capacity in Bremen ACC and Maastricht UAC with increased MME (military mission effectiveness). Throughout the year en-route and RAD updates were implemented to accompany the various PBN implementations for several airports in accordance with CP1.

Besides that, the major change has been made through flight plan adherence. In 2025, air traffic controllers were instructed not to issue non-standard flight level clearances or shortcuts in order to avoid undermining regulated airspace.

\-\--

LVNL:

In March 2025 PYXIS 2A was implemented, an airspace redesign in the northeast of the Netherlands, northwest of Germany and south of Denmark. The change means a dualisation of two Amsterdam in and outbound routes but more important for this PI is that it is a preparation for the establishment of a cross border military area which will be the best compromise between improving the military mission effectiveness and minimising the impact on civil traffic. The area is planned for 2026.

PYXIS resulted in shorter routes for some city pairs, but longer routes for other city pairs. Hence, the impact on HFE performance is difficult to determine and depends on the traffic demand.

\-\--

skyguide:

Free Route Airspace Switzerland (FRACH), referenced in ERNIP 92.065, was implemented in December 2022, positively influencing HFE performance since then. Its primary objective was to enhance skyguide's service to airspace users by enabling shorter flight paths and simplifying the Route Availability Document (RAD) where feasible.

At the same time, Cross-Border FRA between Switzerland and Germany (CHE/DEU, ERNIP 102.006) was launched. This initiative introduced limited cross-border operations using mandatory FRA points strategically placed away from ATC sector boundaries to minimize flight distances between FRA zones. Further enhancements are planned to expand cross-border FRA operations and reduce network inefficiencies.

A FABEC study comparing February 2023 to February 2020 highlighted the benefits of cross-border FRA. It showed improvements in HFE for both internal and interface components. With strike days excluded, the study found that:

- HFE-KEP improved by 0.88%, indicating shorter planned trajectories and reduced fuel requirements.

- HFE-KEA improved by 0.22%.

Additional Cross-Border FRA are planned between 2026 and 2028 to improve operations between Switzerland and France (CHE/FRA ERNIP 102.036, CHE/FRA ERNIP 102.028)

\-\--

DSNA:

main mesasures addressing KEA underachievement in France are in the capacity field, by trying to enhanced DSNA ACC capacity issues which should enable better flight efficiency ; another important measure to be implemented in France will be the full enhcnaced FRA implementation as per CP1 regulation, which has progressed in 2025 and has been fully implemented above flight level 305 in all French airspace 19th March 2026. More details on measures to address both capacity and environment performance in France are given in the dedicated annex to this monitoring report (French capacity and environment remedial measures).

\-\--

skeyes : cf. comment above - therefore no stuctural or operational change has been planned by skeyes.

### **Progress on the implementation of the measures committed to in the ERNIP**

DFS confirms that all planned ERNIP measures have been implemented as foreseen.

skyguide\'s FRA-CH and cross-border FRA measures are progressing as planned (ERNIP entries 92.065 and 102.006). Further cross-border FRA developments at the CHE/FRA border (102.036, 102.028) are planned for 2026-2028.

DSNA is currently implementing ERNIP measures as planned; a major achievement is the full enhcnaced FRA implementation as per CP1 regulation, which has progressed in 2025 and has been fully implemented above flight level 305 in all French airspace 19th March 2026. A more detailed view on ERNIP measures implementation desciption by DSNA is provided in the dedicated annex to this monitoring report (French capacity and environment remedial measures).

skeyes: Over the past years AUP and UUP procedures have been updated in line with ERNIP Part 3, ensuring that any airspace made available is immediately published to NM through a UUP.

\[LVNL, MUAC to confirm ERNIP status\]

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

French NSA:

High traffic levels and delays in Reims and Marseille - which is very much interdependent with HFE - and high peak traffic levels during Summer and traffic volatility in general, adverse weather condition had a negative impact on DSNA HFE performance in 2025.

It should also be recalled that, regarding HFE, other stakeholders behaviour have an impact on the KPI : use of airspace by the military, fuel efficiency choices made by air space users, NM recommendation not to provide direct routes (flight it as it is planned concept), meteorological issues \... It is also recognized by the NM that KEA reduction is structurally limited (at European level, it should be difficult) to go under 2% with the current airspace structure).

DSNA is also implementing new projects and measures that should have a positive impact on environment but more in the vertical field or in line with better fuel efficiency.\"

### **Recommendations to the ANSP to rectify the situation**

French NSA:

A specific meeting has been organized with DSNA in order to gather both explanations and information about remedial measures already launched and identify potential additional measures that could be implemented by DSNA in 2025 and beyond to tackle non temporary environment issues.

The following recommendations / course of actions have been discussed and agreed with DSNA:

- Measures already identified, coordinated with the Network Manager and published in the ERNIP;

- A set of specific remedial measures put in place by DSNA or already planned in 2025 to mitigate identified non temporary issues at the French ACCs have been presented to the French NSA and are listed in the table below and provided in more details in the dedicated annex to this monitoring report (French capacity and environment remedial measures). : the French NSA will be kept informed by DSNA of their timely implementation, of the expected benefit and of any issue in the implementation plan, and a follow-up meeting will be organized 2nd Semester 2026;

- An analysis of potential risks on 2025 and beyond underperformance has been carried over and required potential remedial measures to address such a situation have been discussed; they are also addressed hereafter and in the dedicated annex already mentioned, with the actions taken by the NSA to monitor future performance through its surveillance program. \"

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

French NSA:

As already said, main measures to improve KEA achievements by DSNA rely on addressing capacity issues in order to provide better routing to airspace users in a less congested area. Other measures address the priorisation of TRA use, the final and full implementaiton in France of the enha,ced FRA as per CP1 (done 19th March 2026), dynamic RAD implementation but also measures addressing environment in general such as green operations implementation and the implementaiton of the GreenATM label at DSNA (level 3 reached in 2025).

Please refer to the dedicated annex to this monitoring report (French capacity and environment remedial measures) for more details.

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

French NSA:

As explained above, the French NSA is kept informed of any development related to the implementation of capacity and environment remedial and corrective measures. In particular:

- A follow-up meeting has been organized by the French NSA with DSNA operational directorate in May 2025 to check the implementation of the measures;

- The French NSA has been invited to the two yearly DSNA strategic users\' consultation meetings held in 2025 and spring 2026 which include an update on all strategic and operational measures taken by DSNA to improve capacity and environment performances, prepare Summer season 2026 and on the investment program.

German NSA:

The status of the following measures indicated in previous monitoring reports changed:

1\. ERL/DON sector optimization: The division level between 2nd and 3rd sector has been raised. That measure has proven successful.

2\. Karlsruhe UAC re-design sector group South Part 1: The old sectors ISA and CHI have been merged to form the new AMM sector. As fewer personel is needed to monitor that new sector an increase in capacity was acchieved. Implementation was finished March 2026.

3\. Karlsruhe UAC re-design sector group South Part 2: Lateral optimization of ERL/DON sectors is currently in planning.

The status of further indicated measures hasn\'t changed compared to the 2024 monitoring report.

