## **2.3.2.B. PI #2**

### **Please provide background information on the actual performance: - If performance improved compared to previous years, please describe the measures that were implemented (if any), - If performance deteriorated compared to previous years, please explain the reasons which lead to the deterioration, and describe the improvement measures which are planned to improve performance. How does the NSA intend on monitoring their effectiveness on performance**

German NSA:

This data is not collected by DFS.

No indicator specific initiatives are planed by DFS.

The Netherlands NSA:

data gap noted.

Swiss NSA:

Performance improved in both Geneva and Zurich airports, no specific measures were implemented.

French NSA:

Performance evolution is linked with the overall traffic evolution and general ATC terminal performance. In 2025, the situation impoved at LFPO, and LFMN despite their respective delay situation.

BE NSA:

Those data are not collected by skeyes as they are generated by the airport. No specific action is planned by skeyes.

### **If the data at airport level are not available, please explain the reasons why data is missing and describe the measures planned to resolve the situation**

In 2025, again the quality threshold for unidentified delays has not reached the 50% quality threshold at Roissy Charles de Gaulle airport to validate the 2025 data flow, the 1st condition for publication. This airport currently mainly uses the code \[ZZZ\], which indicates that ATCOs have not always the information about the origin of the various delays. This situation has still to be examined in detail with the ad-hoc airport and DSNA experts in order to find a solution to fix this recurrent issue for RP4.

NL NSA:

As was the case for RP3, this data should be provided by the airport, not the ANSP.

German NSA:

Among the relevant airports of the German TNC charging zone, again in 2025, EDDK was the only one which could not produce sufficientyl reliable data. To the knowledge of the German NSA, in order to improve the situation EUROCONTROL regularly contacts the airports to check on the status of the reporting and provide support in the final correct implementation of the APDF. EUROCONTROL is also part of an ACI sub-group (APN) that includes several airports and informs them regularly on data provision issues. While the NSA is in favour of a solution of this issue, currently and due to prioritisation, no extra activities are planned by the NSA itself.

