## **2.2.2.A. PI #1**

### **What initiatives were implemented or are planned that will improve this PI and how does the NSA intend on monitoring their effectiveness on performance?**

The NSAs are monitoring the performance by using the SES dashboards

https://www.sesperformance.eu/dataportal/vis/2025/

and the FABEC BI dashboards

https://app.powerbi.com/view?r=eyJrIjoiNzFjMGVhNmMtODAyZi00YzI3LWFjNmMtOTlhZWUyZmE3NjlkIiwidCI6ImZlMmE2ZDZmLTlhNDMtNGI5MC04ZDdlLTE3YTllOGY3ZGNmMSIsImMiOjh9.

Direct coordination between NSAs and ANSPs is done regularly and ad-hoc when required. The FABEC Performance Management Group also provides additional reports to the FABEC Financial and Performance Committee (FPC) where required.

\-\-- Germany \-\--

In 2025, ten out of thirteen AIRACs have been used for several route changes. The PYXIS/ZEBRA implementation in March 2025 was successful improving the overall capacity in Bremen ACC and Maastricht UAC with increased MME (military mission effectiveness). Throughout the year en-route and RAD updates were implemented to accompany the various PBN implementations for several airports in accordance with CP1.

Besides that, the major change has been made through flight plan adherence. In 2025, air traffic controllers were instructed not to issue non-standard flight level clearances or shortcuts in order to avoid undermining regulated airspace.

\-\-- Netherlands \-\--

LVNL: simultaneously with PYXIS a route in the western part of LVNL airspace was made more direct. This direct was already often given in the actual operation, but was formalised so that it can be planned.

Additionally, in RP4 LVNL plans to implement the use of LARA for advanced FUA, making temporary reserved areas available for civil traffic more efficiently, allowing airspace users to make use of more efficient routes.

\-\-- Switzerland \-\--

Compared with 2024 (6.35%), the flight efficiency of the planned route slightly declined in 2025 (6.41%). However, it remains above the 2023 level, when the deployment of Free Route Airspace (FRA) began to deliver benefits.

The FRA-CH, implemented at the end of 2022 and further developed, brought significant improvements at KEP level thanks to its cross-border design. Further cross-border developments are planned.

\-\-- France \-\--

2025 KEP achievement is quite similar to 2024 whih had improved with regards to previous years (better planning, less transition plans, less industrial actions and lower delays, better KEA results). See 2.2.1.A KPI #1 for major changes implemented by the DSNA. Measures that improve KEA generally also improve KEP.

Major impacts on KEP expected from FRA implementation : 100 % of the French airspace is now covered as complete FRA implementation is now effective since 19th March 2026 and will provide full effect in 2027, thus improving KEP.

For information on the monitoring of the effectivenesss on performance, see 2.2.2.A PI #1.

\-\-- Belgium \-\--

skeyes is monitoring the performance by using the SES dashboards, even though there is limited room for improvement within Belgian airspace; skeyes contributing to improvements of en-route flight efficiency by establishing a CIV-MIL AMC, co-located at skeyes premises, which aims at optimising the airspace management between CIV and MIL and contestant improvements of FUA on local level.

\-\-- MUAC contribution for D/B/NL\-\--

\[No contribution received\]

