## ERT1.3. Rate of using available airspace structures (PI#11) {#ert1.3.-rate-of-using-available-airspace-structures-pi11 .Heading-2-ER}

BELGIUM and LUXEMBOURG report that:

- The ratio of the use of the available airspace structures is **17%** (via available restricted and segregated airspaces)

- The ratio of the use of the available airspace structures is **86%** (via available conditional routes -- CDR)

FRANCE reports that:

- The ratio of the use of the available airspace structures is **54.30%** (via available restricted and segregated airspaces)

- The ratio of the use of the available airspace structures is **64.41%** (via available conditional routes -- CDR)

GERMANY reports that:

- The ratio of the use of the available airspace structures is **45.07%** (via available restricted and segregated airspaces)

- The ratio of the use of the available airspace structures is **70.35%** (via available conditional routes -- CDR)

LUXEMBOURG -- not applicable (see BELGIUM and LUXEMBOURG)

NETHERLANDS reports that:

- The ratio of the use of the available airspace structures is **27,43%** (via available restricted and segregated airspaces)

- The ratio of the use of the available airspace structures is **62.70%** (via available conditional routes -- CDR)

SWITZERLAND reports that:

- The ratio of the use of the available airspace structures is **65.58%** (via available restricted and segregated airspace)

MUAC -- not applicable
