## **2.3.2.A. PI #1**

### **Please provide background information on the actual performance: - If performance improved compared to previous years, please describe the measures that were implemented (if any), - If performance deteriorated compared to previous years, please explain the reasons which lead to the deterioration, and describe the improvement measures which are planned to improve performance. How does the NSA intend on monitoring their effectiveness on performance**

ATFCM cross-trainings for (Warsaw) Tower Supervisors have been performed in late 2024, which resulted in proper performance in 2025. Additionally, in 2025 dedicated ATFCM training sessions were conducted for TWR EPWR and EPKT, aimed at further improving performance parameters.

The results indicate that there were no airports in Poland where adherence to ATFM departure slots in year 2025 was less than 80%. The level of adherence to ATFM departure slots in 2025 was similar to that observed in 2024 with the highest percentage value of departures outside ATFM window noted at EPKT airport (6,2%), but still definitely not exceeding the 20% limit value.

