## PRB1.5. Capacity {#prb1.5.-capacity .Heading-2-ER}

- Poland registered 0.17 minutes of average en route ATFM delay per flight during 2025, which remained 0.17 after the post-ops adjustment process, thus achieving the local target value of 0.24. Delays in Poland decreased by -0.06 minutes per flight year-on-year.

- Delays were highest in July, driven by a combination of weather and other non-ATC causes as well as ATC capacity and staffing.

- The share of delayed flights with delays longer than 15 minutes in Poland decreased by -3 percentage points compared to 2024.

- The number of ATCOs in OPS was 179 being below the 2025 plan in Warsaw ACC by -5 FTE.

- The yearly total of sector opening hours in Warsaw ACC was 28,447, showing a -20% decrease compared to 2024.

- Warsaw ACC registered 23.47 IFR movements per sector opening hour in 2025. This is +29% above the ratio recorded in 2024.

- Poland registered an average airport arrival ATFM delay of 0.48 minutes per flight in 2025, thus not achieving the local target of 0.06 minutes. Compared to 2024, average arrival ATFM delays in Poland were -0.01 minutes per flight lower in 2025.

- The main drivers of delays were other non-ATC causes, accounting for 0.23 of the total delays, and weather, responsible for 0.22.

