## PRB1.6. Cost-efficiency {#prb1.6.-cost-efficiency .Heading-2-ER}

- The en route 2025 actual unit cost of Poland was 57.41€2022, +5.0% higher than the determined unit cost (54.69€2022). The terminal zone 1 2025 actual unit cost was 117.35€2022, -9.6% lower than the determined unit cost (129.78€2022), while the terminal zone 2 2025 actual unit cost was 226.69€2022, -6.9% lower than the determined unit cost (243.57€2022).

- The en route 2025 actual service units (4.0M) were -2.7% lower than the determined service units (4.1M).

- The en route 2025 actual total costs were +4.6M€2022 (+2.1%) higher than determined. This is mainly due to higher staff costs for PANSA (+8.2M€2022, or +6.5%), partially compensated by lower other operating costs than planned (-3.7M€2022, or -11.5%). The NSA explained that the increase in staff costs is mainly caused by higher provisions than forecasted, while the decrease in other operating costs is mainly due to lower energy and repair services costs.

- PANSA spent 49.6M€2022 in 2025 related to costs of investments for both en route and terminal charging zones, +0.8% more than determined (49.2M€2022). The NSA explained that this difference reflects the actual evolution of the useful life and value of assets.

- The en route actual unit cost incurred by users in 2025 was 67.51€ (-4.2% below the 2025 DUC). The terminal actual unit cost incurred by users was 153.02€ (-10.1% below the 2025 DUC) for the terminal zone 1, and 296.95€ (-6.4% below the 2025 DUC) for the terminal zone 2. The difference between the AUCU and the DUC for the en route charging zone is mainly driven by other revenues. The difference between the AUCU and the DUC for the terminal charging zone 1 is mainly driven by the adjustment for traffic risk sharing and by the adjustment for inflation for the terminal charging zone 2.

