## **2.2.2.G. PI #7**

### **What initiatives were implemented or are planned that will improve this PI and how does the NSA intend on monitoring their effectiveness on performance?**

Maintaining the work technologies and procedures of air traffic control services enabling the use of CDO landing techniques by aircraft crews.

RNAV procedures and airspace allowing continuous descent operations are available for all airports where PANSA provides ATS.

In 2025 TMA Kraków was redesigned in the lower part in order to optimise CDA profile for flights which arrive to EPKK on tactically shortened horizontal trajectories. Implementation of the project was completed in April 2026.

TMA Poznań reorganisation project was initiated in 2025. The project aims at optimising continued descent approach profile for EPPO arrival to RWY10.

TMA Zielona Góra reorganisation project was initiated in 2025 with the following goals:

1\. Implementation of separate arrival/departure point to/from east direction with linked separated SID/STAR procedures,

2\. Redesign of terminal airspace.

Implementation will enable simultaneous departures and arrivals to/from EPZG reducing the risk of holding patterns in such situation.

The NSA receives the list of planned changes to the ATM functional system on a regular basis. Once a change is notified the relevant monitoring activities are implemented.

