## **2.3.1.A. KPI #1**

### **Identification and analysis of the reasons and circumstances resulting in the achieved level of actual performance of the en-route ATFM delay per flight KPI**

The en-route delay target was achieved. The average en-route delay for flights operated by PANSA in 2025 was 0.17 min/flt, below the 2025 target of 0.24 min/flt established in RP4 PP. At the same time, en-route delays decreased compared to 2024.

Since 2022 the geopolitical situation has been the primary factor affecting operational performance in the Polish airspace. Warfare, increased military activity, and sanctions, resulting in significant changes to traffic flows in the European airspace, have had a significant impact on air traffic structure, sector capacity and airspace organisation, thereby affecting the level of delays generated. The target set for 2025, within the new, fourth reference period (RP4), based on reference value for Poland which partially reflected the operational situation in the Network observed in 2024, created also a realistic prospect of its achieving. The detailed brakdown of en-route ATFM delays per causes in 2025, based on Network Manager data for airspace users with post-ops, shows that the main delays were assigned to: code \"O\" - 34%, ATC capacity - 21% and weather - 17,3%. At the same time 16 335 minutes of delays in 2025 were coded as Special event, and it constitutes 12% of all ATFM en-route delays.

In 2025 the following actions were implemented on an ongoing basis to minimise en-route delays:

• Use of Free Route Airspace (FRA) in traffic planning and cross-border FRA,

• Use of dynamic capacity management, including tactical traffic scenarios at the network level,

• Flexible use of all available ATFCM (Air Traffic Flow and Capacity Management) tools, including STAM (Short Term ATFCM Measures) procedures, in managing air traffic capacity and flow,

• Operational use of a three-layer airspace division in the south-eastern sectors (sectors J and R),

• Post-operational analyses, including traffic volume, delays, and sector configurations used,

• Pre-tactical traffic analyses based on data sent by the Network Manager (NM) during the „Rolling NOP" (European Network Operations Plan) information exchange process,

• Planning ATC (Air Traffic Control) staffing based on forecasted traffic volumes in the strategic and pre-tactical phases,

• Dynamic management of ACC (Area Control Centre) sectorization and the layout of APP (Approach Control) and TWR (Aerodrome Control Tower) stations on the day of the operation,

• Effective civil-military cooperation, particularly taking into account tactical activities resulting from the war in Ukraine.

In 2025 PANSA participated in the Occupancy Regulation Trial, a project prepared and coordinated by the NM, which was designed and operationally tested to regulate air traffic flow while maintaining minimal delays.

It is also worth noting that 2025 was another year in which PANSA actively participated in European-level initiatives aimed at minimizing delays across the entire network. Due to the apparent limitations in airspace capacity in some countries and the growing impact of adverse weather events, for the Summer 2025 season, the NM, in cooperation with PANSA and other air navigation service providers in Europe, introduced additional measures to relieve the most congested parts of the European network\'s airspace and avoid dangerous areas. In particular, traffic scenarios were prepared that redirected some traffic flows to less congested areas, including Poland.

### **Description of the adjustments to the capacity plan included in adopted performance plan**

No adjustments were made to the capacity plan included in adopted RP4 PP.

PANSA continued implementing the initiatives listed in the RP4 PP, aimed at improving capacity in FIR Warszawa. These primarily included the following:

• Preparation for the operational use of the three-layer airspace division in all sectors of Polish airspace in 2026.

• Continuing the training of new air traffic controllers (with two new courses for new ATCOs launched in 2025, alongside the continuous training of trainees from the preceding years), as well as the process of acquiring and maintaining the competencies of ATC staff and other operational personnel to ensure the necessary staffing levels for the growing traffic volumes.

• Preparation to implement changes to the vertical boundaries of ACC sectors aimed at more effective distribution of changing air traffic flows.

• Developing, updating and preparing new solutions and functionalities within existing ATM-related systems (PEGASUS_21, Pandora), as well as deploying completely new platforms (iTEC, NMUI) in relation to RP5.

• Utilising tools to support ATCOs and flow management optimisation (including use of NMP Flow as well as Arrival Manager for EPWA airport).

• Continuing investments in infrastructure (CNS) and technology allowing for optimisation of airspace structures and enhance coverage across the Polish airspace, as well as supporting contingency.

• Works on implementation of Radar Control in EPRZ TMA (implemented in January 2025).

• Conducting traffic analyses under hypothetical scenarios assuming unblocking of Ukrainian and Belarussian airspace.

Additionally:

• CAPAN (capacity analysis) studies were carried out, allowing for flexible capacity determination depending on changing traffic flows. Taking into account the results, the current capacities of ACC sectors remained unchanged, and the data obtained in the study allowed PANSA to determine the capacities of new sectors created by the implementation of the third layer in the whole FIR Warszawa. When activating the analysed military zones, the possibility of reducing the declared capacities of the ACC sectors in which the military zones will be activated will be taken into account.

• Preparations were underway to further develop the cross-border FRA in cooperation with other ANSPs.

• Enhancing the civil-military cooperation taking into account the growing demand for airspace use by both sides.

Further improvements are planned for RP4 as listed in the RP4 PP for Poland.

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

n/a

### **Recommendations to the ANSP to rectify the situation**

n/a

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

n/a

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

1\. Improved sectorisation of ACC (until 2026) -- new sector configurations in JR part since 17.06.2022, implementation of the first stage of three-layer vertical airspace split in April 2023 (JR sectors) -- full FIR EPWW three layer vertical airspace split implemented in 2025 and operational from 2026.

2\. Traffic flow management and development of sectorisation (ongoing process) -- there are evaluations of traffic flows, carried out on a regular basis to modify flows and redirect traffic from congested areas to airspace volumes where spare capacity is available. Flexible use of ATFM regulations, including Dynamic RAD implemented (February 2025) and occupancy trials. Planned increase in the maximum number of sectors possible to be opened (number of sectors open will depend on traffic demand -- traffic level and structure/flows) and flexible use of available sectors (over 2000 sector configurations possible to use).

3\. Training of new ATCOs (ongoing process) -- new ATCOs training aimed at increasing the number of ATCOs in line with the plan included in the RP4 PP.

All the actions described in section 2.3.1.(a) to minimise en-route delays enabled the achievement of the en-route delay target for 2025. The results demonstrate that the actions taken were effective. However, a significant share of delays related to the war in Ukraine and weather factors is still visible, and PANSA\'s response and action capabilities remain limited.

