## **2.3.1.B. KPI #2**

### **Identification and analysis of the reasons and circumstances resulting in the achieved level of actual performance of the arrival ATFM delay per flight KPI**

The target for the terminal delay indicator was not achieved. The average terminal delay for airports where PANSA provided ATC services in 2025 was 0.48 minutes/arrival, compared to the annual target set under RP4 PP of 0.06 minutes/arrival. The value of ATC only terminal delays (CRSTMP) was however lower than forecasted when drafting the RP4 PP (0.04 vs. 0.05 minute/arrival) -- lower than the modulated pivot value based on ATC-related delays.

The recovery of inbound traffic to Polish airports after the pandemic and since the outbreak of the war in Ukraine was much more dynamic than in overflights. Inbound IFR traffic in 2025 was 16% higher than in 2019 and increased by 8% compared to 2024. Most Polish airports exceeded 2019 levels in terms of aircraft movements handled.

It should be noted that actual traffic (one way IFR MVS) at Polish airports (terminal zone I and II) in 2025 was almost 5% higher than the forecast underlying the adopted RP4 PP.

Terminal delays in 2025 were generated at 9 of the 15 controlled airports (EPKK, EPKT, EPLB, EPLL, EPMO, EPPO, EPRZ, EPWA, EPWR). Higher delays than the target terminal delay indicator were due to factors unrelated to ATC. These included weather conditions (45,4% of all terminal delays recorded in 2025) and airport capacity constraints, including those related to airport infrastructure renovations (43,8%). ATC (CMPRST) related delays accounted for only 8,6% of all delays, while other non-ATC factors accounted for around 2%, including delays related to the war in Ukraine.

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

The failure to achieve the 2025 target was due to factors beyond PANSA\'s control, including weather conditions and airport infrastructure renovation. The impact of those factors was much greater than anticipated at the stage of drafting the RP4 PP. Delays generated by ATC accounted for only 8,6% of all terminal delays, which translated into an indicator of 0.04 minutes/arrival, compared to the planned ATC reference value of 0.05 minutes/arrival in RP4 PP.

### **Recommendations to the ANSP to rectify the situation**

As the average terminal delay due to ATC related causes (CRSTMP) is only 8,6% of all terminal delays recorded in 2025 and lower than the pivot value for year 2025 no strict recommendations to the ANSP (PANSA) are issued. However, the NSA continues to monitor the number of ATCOs on a regular basis, as well as other ANSP\'s initiatives aimed at meeting the targets related to ATC causes. Non-ATC delays remain beyond PANSA\'s control.

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

As indicated above, terminal delays are significantly impacted by non-ATC elements that are beyond control of PANSA. However, PANSA is continuously implementing actions in line with RP4 PP which are aimed at reducing terminal delays and achieving the ATC terminal delay target.

In 2025 these mainly included the following:

• introduction of lower runway separation minima (EPWA), increasing operational efficiency,

• launch of DCL -- Digital Clearance -- sending flight permits electronically instead of traditional voice communication (EPWA, EPWR, EPKK, EPKT, EPMO),

• implementation (for testing at this stage) of D-ATIS -- it allows crews to read weather and operational conditions at the airport directly from the Flight Management System computer installed in the aircraft (EPWA, EPGD, EPKK),

• launch of the ground movement control service -- GND (EPWR, EPKT, EPMO),

• implementation of a full LVP procedure -- it allows crews to read weather and operational conditions at the airport directly from the Flight Management System computer installed in the aircraft (EPKK),

• introduction of Visual Departure -- visual departures allow for a significant improvement in aircraft departures, having a significant impact on the traffic flow and increasing the number of movements per hour (EPKK).

Planned measures to support achievement of the capacity targets in RP4 have been listed in the RP4 PP for Poland.

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

Remedial measures indicated in previous monitoring reports have been implemented.

The target takes into account all delay causes -- both ATC as well as non-ATC. As shown by the past years' data, terminal delays are significantly impacted by non-ATC elements that are beyond control of PANSA. This has been considered when defining the incentive scheme for RP4, however still due to this fact there is a significant risk that the actual delay indicator (based on all delay causes) might be different than the target -- which was confirmed in 2025. Another element that can influence the actual performance over the coming years is the level of traffic. The RP4 traffic forecast is, in principle, based on STATFOR predictions. Past years' experience has shown that actual traffic can develop more dynamically than forecasted, what could also impact the delay indicator.

Planned measures to support achievement of the capacity targets in RP4 have been listed in the RP4 PP for Poland.

