## **2.2.2.K. PI #11**

### **What initiatives were implemented or are planned that will improve this PI and how does the NSA intend on monitoring their effectiveness on performance?**

The lateral and vertical limits of the published airspace elements are defined considering the actual needs of users and nature of activities. All airspace elements shall be planned only for the period necessary to perform the intended task. The user is required to precisely specify the period of activity of the selected element, as well as any temporary suspensions of activity between these periods.

Segmentation, time and level restrictions are imposed when needed to mitigate the impact in high traffic periods of the day. If possible, class C TRA airspace is implemented to minimise the impact on civil routing.

Special procedures are developed including dynamic change of level or area segment.

Further measures include:

• implementation of closer cooperation between AMC Poland and FMP Warszawa in order to reduce the negative impact of segregated areas on civil traffic as far as possible,

• work on update of national aviation law to optimise the process for reserving segregated areas for military users.
