## **2.2.2.J. PI #10**

### **What initiatives were implemented or are planned that will improve this PI and how does the NSA intend on monitoring their effectiveness on performance?**

The available flight planning options are continuously updated to allow Aircraft Operators (AOs) to plan the most horizontally efficient trajectory -- even when the areas are active. Except for ATS network and DCTs, the AOs have the possibility to plan in the Free Route Airspace environment (FRA). Implementation of cross-border free route airspace operations within Lithuanian and Polish airspace (BALTIC FRA) and the cross-border operations between BALTIC FRA and South East Europe FRA were completed in 1Q 2022. This measures may further enhance the planning opportunities. Second step of cross-border FRA operation between Poland, Czechia and Sweden was implemented in November 2024, further enhancing benefits for AUs.

The lateral and vertical limits of the published airspace elements are defined taking into consideration the actual needs of users and nature of activities. All airspace elements shall be planned only for the period necessary to perform the intended task. The user is required to precisely specify the period of activity of the selected element, as well as any temporary suspensions of activity between these periods.

Segmentation, time and level restrictions are imposed when needed to mitigate the impact in high traffic periods of the day. If possible, class C TRA airspace is implemented to minimise the impact on civil routing.

Special procedures are developed including dynamic changes of level or segment and creation of new temporary routings to avoid military traffic.

Further measures include:

• implementation of closer cooperation between AMC Poland and FMP Warszawa in order to reduce the negative impact of segregated areas on civil traffic as far as possible,

• work on update of national aviation law to optimise segregated area booking process from military users.

Due to the war in Ukraine and significantly increased number of NATO flights in the Polish airspace special procedures were implemented in order to facilitate flight planning process for AUs. For some areas FUA restrictions are dynamically managed and, when possible, are not activated on given days.

