## SAF1.3. Rate of runway incursions (RIs) (PI#1)

Malta reported 7 runway incursions (RI) at Luqa airport during 2025. When comparing the rate of RIs at airport level to Union-wide level, Malta was significantly higher than Union-wide average (9.64 vs 2.53).

Malta reported 7 RIs with ATS/CNS contribution in 2025. When comparing the rate of RIs at airport level with ATS/CNS contribution, Malta was significantly higher than Union-wide average (9.64 vs 0.96).

The rate of runway incursions has decreased compared to 2024 at airport level (9.64 vs 16.97) but increased at ATS/CNS contribution-level (9.64 vs 5.66).

As described in the monitoring report, a significant number of infrastructure works are ongoing at LMML. The aerodrome now includes the new Apron 8 lightning system, new stop bars, and resurfacing works, which have impacted MATS TWR operations. MATS routinely briefs the ATCO community and discusses progress with MIA and the NCA with a view to identify and implement improvements. MATS also briefs occurrences in the spot training, consisting of tailor-made exercises replicating actual occurrences used for training purposes.

