## **TZ1.2. SECTION 2 -- ACTUAL UNIT COST INCURRED BY THE USERS**

### **TZ1.2.1. FOCUS ON TERMINAL AUCU MONITORING AT CHARGING ZONE LEVEL**

The actual terminal unit cost incurred by airspace users (AUCU) in respect of activities performed in 2025 (88.29 €) is -42.6% lower than the nominal DUC (153.77 €). The difference between these two figures (-65.48 €/SU) is due to:

- the negative inflation adjustment resulting from lower than planned inflation (-0.19 €/SU);

- the impact of adjustments resulting from the costs exempted from cost sharing mechanism (-55.40 €/SU);

- the deduction of the traffic risk sharing adjustments (-3.60 €/SU);

- the deduction of the traffic adjustment (-0.80 €/SU) for the costs not subject to traffic risk sharing; and,

- the deduction of other revenues (-5.49 €/SU).

The share of the regulatory result (see next sub-section) in the AUCU (before the deduction of other revenues) is -40.2%.

Costs exempt from cost sharing for 2025 presented here are based on preliminary figures and remain subject to revision pending the receipt of the NSA Reports on the verification of cost sharing due by 1 September 2026. Any changes may affect the analysis of Actual Costs for Users and the Regulatory Results.

### **TZ1.2.2. INITIATIVES IMPLEMENTED OR PLANNED THAT WILL IMPROVE THIS PI REPORTED BY THE NSA**

The NSA of Malta provides the following information regarding the initiatives:

*"The favourable 2025 terminal actual unit cost incurred by users is primarily explained by actual costs below the determined cost base combined with terminal service units above forecast. For the remaining RP4 years, the focus should remain on cost discipline, accurate cost allocation, investment delivery and operational resilience as traffic develops. The NSA will monitor the effectiveness of these measures through the annual review of actual costs, service units, traffic-related adjustments and any emerging terminal capacity pressures."*

### **TZ1.2.3. NOTES** 

#### **TZ1.2.3.1. NOTE 1**

#### **TZ1.2.3.1. NOTE 2**

