## **ER1.2. SECTION 2 - ACTUAL UNIT COSTS INCURRED BY THE USERS**

### **ER1.2.1. FOCUS ON EN ROUTE AUCU MONITORING AT CHARGING ZONE LEVEL**

The actual en route unit cost incurred by airspace users (AUCU) in respect of activities performed in 2025 (17.48 €) is -8.1% lower than the nominal DUC (19.02 €). The difference between these two figures (-1.54 €/SU) is due to:

- the negative inflation adjustment resulting from lower than planned inflation (-0.02 €/SU);

- the impact of adjustments resulting from the costs exempted from cost sharing mechanism (+0.28 €/SU);

- the deduction of the traffic risk sharing adjustments (-0.88 €/SU);

- the deduction of the traffic adjustment (-0.29 €/SU) for the costs not subject to traffic risk sharing; and,

- the deduction of other revenues (-0.62 €/SU).

The share of the regulatory result (see next sub-section) in the AUCU (before the deduction of other revenues) is 16.1%.

Costs exempt from cost sharing for 2025 presented here are based on preliminary figures and remain subject to revision pending the receipt of the NSA Reports on the verification of cost sharing due by 1 September 2026. Any changes may affect the analysis of Actual Costs for Users and the Regulatory Results.

### **ER1.2.2. INITIATIVES IMPLEMENTED OR PLANNED THAT WILL IMPROVE THIS PI REPORTED BY THE NSA**

The NSA of Malta provides the following information regarding the initiatives:

*"The favourable 2025 en-route actual unit cost incurred by users is supported by (i) actual costs below the determined cost base and (ii) actual service units above forecast. To support sustainable performance over RP4, the main initiatives remain the disciplined implementation of the RP4 investment programme, timely recruitment and training, and continued operational coordination with network partners. The NSA will monitor effectiveness through annual review of actual costs, service units, unit rates and the traffic- and inflation-related adjustments applied under the charging scheme."*

### **ER1.2.3. NOTES** 

#### **ER1.2.3.1. NOTE 1**

#### **ER1.2.3.1. NOTE 2**

