## PRB1.6. Cost-efficiency {#prb1.6.-cost-efficiency .Heading-2-ER}

- The en route 2025 actual unit cost of Malta was 14.96€2022, -15.0% lower than the determined unit cost (17.61€2022). The terminal 2025 actual unit cost was 126.68€2022,

-10.8% lower than the determined unit cost (142.05€2022).

- The en route 2025 actual service units (1.3M) were +10.5% higher than the determined service units (1.2M).

- The en route 2025 actual total costs were -1.2M€2022 (-6.1%) lower than determined. This is mainly due to lower staff costs (-0.9M€2022, or -7.5%) and other operating costs (-0.7M€2022, or -26.8%) for MATS. According to the NSA, staff costs decreased mainly due to retirements exceeding plan and a delay in recruitment, while the reduction in other operating costs was mainly due to lower insurance costs.

- MATS spent 3.0M€2022 in 2025 related to costs of investments for both en route and terminal charging zones, +4.6% more than determined (2.8M€2022). According to the NSA, this increase is due greater investments in assets subject to higher depreciation than planned.

- The en route actual unit cost incurred by users in 2025 was 17.48€ (-8.1% below the 2025 DUC), while the terminal actual unit cost incurred by users was 88.29€ (-42.6% below the 2025 DUC). The difference between the AUCU and the DUC for the en route charging zone is mainly driven by traffic risk sharing adjustments. The difference between the AUCU and the DUC for the terminal charging zone is mainly driven by new and existing investments in cost exempt from cost sharing.

- The en route regulatory result for MATS amounted to +3.7M€, or 18.5% of the 2025 revenue. This may indicate that the airspace users are charged for costs which have not materialised in 2025.

