## PRB1.6. Cost-efficiency {#prb1.6.-cost-efficiency .Heading-2-ER}

- The en route 2025 actual unit cost of Lithuania was 53.21€2022, -4.2% lower than the determined unit cost (55.57€2022). Lithuania does not have a terminal charging zone.

- The en route 2025 actual service units (0.50M) were +3.1% higher than the determined service units (0.48M).

- The en route 2025 actual total costs were -0.3M€2022 (-1.3%) lower than determined. This is mainly due to lower other operating costs (-0.3M€2022, or -7.6%) and cost of capital (-0.3M€2022, or -14.0%) for Oro Navigacija, partially compensated by unplanned exceptional items (+0.5M€2022). The NSA explained that the decrease in other operating costs is attributable among others to lower utilities, office-maintenance and consultancy costs, while for cost of capital, it is due to a lower return on equity. The unplanned exceptional items reflect the one-off adjustment related to the ATCO's early-retirement scheme.

- Oro Navigacija costs of investments were 4.1M€2022 in 2025, -11.5% less than determined (4.7M€2022). According to the NSA, this reduction was mainly due delays in smaller investments, caused by longer procurement procedures, unsuccessful tenders due to a lack of bids, and technical or supplier-related issues.

- The en route actual unit cost incurred by users in 2025 was 59.22€ (-2.1% below the 2025 DUC). The difference between the AUCU and the DUC is mainly driven by new and existing investments in cost exempt from cost sharing.

- The en route regulatory result for Oro Navigacija amounted to +2.6M€, or 10.1% of the 2025 revenue. This may indicate that the airspace users are charged for costs which have not materialised in 2025.

