## 2.3.1.A. KPI #1

### Identification and analysis of the reasons and circumstances resulting in the achieved level of actual performance of the en-route ATFM delay per flight KPI

Skyguide achieved its target in 2025. In spite of observing traffic levels well above 2019 level (+8%) and above 2024 level (+3.6%), Skyguide could reduce its en-route ATFM delay by 38% compared to 2024.

### Description of the adjustments to the capacity plan included in adopted performance plan

According to the latest Network Operations Plan (NOP 2026), no capacity bottleneck is expected, neither in LSAZACC nor in LSAGACC. The level of performance achieved in 2025 shows that, with the STATFOR traffic forecast baseline scenario, capacity should still be sufficient in 2026 and beyond.

### Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved

### 

### Recommendations to the ANSP to rectify the situation

### 

### Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why

skyguide: Target met --- no remedial measures required

### Follow up of the remedial measures indicated in the previous monitoring report(s)

## 

