## SAF1.1. Effectiveness of Safety Management (EoSM) (KPI#1)

In 2025, Skyguide achieved the planned maturity levels set out in its performance plan for all five components of the EoSM. In more detail, Skyguide exceeded the planned level in the area of Safety Culture.

In terms of main measures put in place to achieve the safety performance targets, the report defines the following elements:

- Skyguide reviewed and updated TOP8 reporting to the board of directors.

- Skyguide completed strategic initiative on how to Support effectively decision-makers with safety products.

- The new training specialist position in safety department was created and filled in order to review and improve safety training provided in Skyguide.

- There was a language course for all investigators to address neutral/non blaming language and cooperation with HF team was reinforced and utilized in several investigations.

- The response plans are not only coordinated, but also regularly exercised for example by inviting other organisations to participate in Skyguide\'s exercise and by Skyguide participating in airport EASA exercises.

- Skyguide reviewed and updated the Safety Manual.

- Skyguide did a yearly SMS audit by another ANSP, MUAC.

- New roles and responsibilities established for safety management.

