## 2.2.2.K. PI #11

### What initiatives were implemented or are planned that will improve this PI and how does the NSA intend on monitoring their effectiveness on performance?

FPL filed and flown on CDRs is not available in PRISMIL and would need to be added. However, all CDRs have be removed from our FUA restrictions since 14.05.2026, so for us, it makes no more sense to report on this.

Ongoing national civil-military initiatives

Enabled the technical capabilities for applying VPA, working on implementation of Dynamic RAD in Switzerland and in the frame of the CIV MIL ASM System we are implementing a fully integrated ASM data transfer from input by airspace user until output to airspace user as well as to ATCO radar.

Monitoring of effectiveness

Military mission planning remained stable at a high level over years implying more reliable flight planning by AUs across Swiss airspace. CH NSA measure and analyze the PIs in a regular basis in order to better assess (and improve, if necessary) the effectiveness of national FUA processes.

