## PRB1.6. Cost-efficiency {#prb1.6.-cost-efficiency .Heading-2-ER}

- The en route 2025 actual unit cost of Switzerland was 142.39€2022, +5.7% higher than the determined unit cost (134.75€2022). The terminal 2025 actual unit cost was 470.51€2022, +1.2% higher than the determined unit cost (464.93€2022).

- The en route 2025 actual service units (1.8M) were -6.8% lower than the determined service units (1.9M).

- The en route 2025 actual total costs were -3.8M€2022 (-1.5%) lower than determined. This is mainly due to lower other operating costs for Skyguide (-3.8M€2022, or -7.2%). The NSA explained that the decrease in other operating costs resulted from saving measures implemented in response to the drop of traffic.

- Skyguide spent 44.0M€2022 in 2025 related to costs of investments for both en route and terminal charging zones, +1.9% more than determined (43.2M€2022). This increase is mainly due to higher depreciation costs of terminal.

- The en route actual unit cost incurred by users in 2025 was 154.90€ (+4.0% above the 2025 DUC), while the terminal actual unit cost incurred by users was 513.20€ (-0.2% below the 2025 DUC). The difference between the AUCU and the DUC for the en route charging zone is mainly driven by the adjustment for traffic risk sharing.

