## 2.2.2.G. PI #7

### What initiatives were implemented or are planned that will improve this PI and how does the NSA intend on monitoring their effectiveness on performance?

Vertical flight efficiency from Top of Descent remained stable in 2025 despite traffic increase. CDOs can be flown only when traffic is reduced.

In 2025, the average duration of level-off segments during the descent phase was 3.2 minutes at Geneva Airport and 2.8 minutes at Zurich Airport, compared with an average of 2.8 minutes across the top 30 European airports.

Skyguide was audited in 2023, 2024 and 2025 by CANSO for CCO/CDO practices in ZRH and GVA as part of its GreenATM accreditation. Room for improvement is identified and corrective actions will be taken.

Skyguide continues to work with the airlines to improve the CCO/CDO rate. The OMASI trial with Swiss, aimed at implementing dynamic RAD on the border between France and Switzerland, OMASI waypoint, and thus enabling CDO from Top of Descent, was completed in March 2024. It shows impressive results and even if post-trial analysis determine that it can be continued because of its impact on capacity, improvement measured could be found.

Projects are planned to implement an AMAN in Geneva and optimize the Extended-AMAN (XMAN) in Zurich. The AMAN plays a critical role in ensuring that CDO can be executed effectively. By optimizing traffic flow, coordinating arrivals, and minimizing disruptions, AMAN enhances the ability of aircraft to maintain a smooth, uninterrupted descent.

Furthermore, in LSZH, LADY (Lean AMAN Development Yielder) will improve the inbound trajectory calculation, thus allowing the ATCOs to deliver a highly reliable \"miles to touchdown\" information to the pilots, which in turn will allow them to optimise their descents and contribute to our CDO objectives.

Projects are planned to implement an AMAN in Geneva and optimize the Extended-AMAN (XMAN) in Zurich. The AMAN plays a critical role in ensuring that CDO can be executed effectively. By optimizing traffic flow, coordinating arrivals, and minimizing disruptions, AMAN enhances the ability of aircraft to maintain a smooth, uninterrupted descent.

To further optimise CCO/CDO, a project based on new controller tools (including AMAN) and airspace design is planned.

