## SAF1.4. Rate of separation minima infringements (SMIs) (PI#2)

At State level, Switzerland reported 19 separation minima infringements (SMI) in their airspace during 2025. The rate of separation minima infringements was higher than Union-wide average (13.08 vs 7.10). At ANSP level, Switzerland reported 10 SMIs with ATS/CNS contribution. The rate of separation minima infringements at ANSP level was higher than the Union-wide average (6.89 vs 6.0).

When comparing to 2024, the rate of separation minima infringements has increased at both State level (13.08 vs 4.59) and at ANSP level (6.89 vs 3.82).

In terms of the initiatives implemented or planned to improve this performance indicator, the report defines the following elements:

-   NRH3 Geneva will remove the system interpretation of the route, allowing for a better conflict detection prediction (tools).

-   Improvement on CPDLC, which when used more, reduces the risk of Undetected Simultaneous Transmissions (USiT).

-   4D downlink trajectories will show the discrepancy between the FMS route and the filed FPL in system, better trajectory prediction.

-   ADST will allow to downlink.

-   LORD-CH (Leading Optimised Runway Delivery). The LORD project aims at delivering the following benefits:

    -   Reduced controller workload (via increased automation).

    -   Safety: reduced number of SMIs on final.

    -   Efficiency: systematic optimised spacing between pairs.

    -   Increased runway throughput (3% to 8%), leading to reduced delays.

