## ERT1.1. En route ATFM delay per flight (KPI#1)

-   Switzerland had 1 200k flights in 2025, up from 1 194k flights in 2024.

-   The Swiss ANSP, Skyguide, applied en route ATFM regulations resulting in 402k minutes of delay in 2025, a significant decrease from the 660k minutes in 2024.

-   As part of the strategic traffic re-orientation programme (S25/NTDM) operated by the Network Manager, 25k minutes of delay originating in Switzerland were re-attributed **to other ANSPs.**

-   Under the auspices of the Route Network (RN) Scenarios during Capacity & Weather Based Operations between June and September 2025, an additional 3k minutes of en route ATFM delay were re-attributed **to Skyguide** -- with 4k minutes of delay originating in Switzerland, being re-attributed **to other ANSPs**.

-   A further 41k minutes of en route AFTM delay were reattributed (post-operations) to Swiss airports, as airport ATFM arrival delay.

-   Following the NM post operations re-attributions process, Skyguide were responsible for 335k minutes of en route ATFM delay, compared to 402k minutes in 2024.

