## TRM1.1. Terminal and airport ANS ATFM arrival delay per flight (KPI#2) {#trm1.1.-terminal-and-airport-ans-atfm-arrival-delay-per-flight-kpi2 .Heading-2-TZ}

Average ATFM arrival delay in Italy was 0.29 min/arr in 2025, the first year of RP4. The **performance is almost equal to 2024**, last year of RP3, when there were 0.28 min/arr. It has to be noted that in RP3, Italy included only its five largest airports for the calculation of this indicator, whereas in the first year of RP4 there are 48 airports.

Within five of the six largest airports, the figures range from 0.04 min/arr in Rome Fiumicino to 0.36 min/arr in Milan Malpensa. However, the highest ATFM arrival delays in Italy took place in the sixth one, Naples, with 2.34 min/arr in 2025, increased from 1.55 min/arr in 2024. Delays in Naples are frequently driven by local operations procedures constrained by high temperatures in the summer.

The average for RP4 airports subject to monitoring of ATFM Arrival delay across Member States in 2025 was 0.97 min/arr.

