## **2.3.1.A. KPI #1**

### **Identification and analysis of the reasons and circumstances resulting in the achieved level of actual performance of the en-route ATFM delay per flight KPI**

The ENAV post-ops reconciliation process finally resulted in a figure of the Capacity KPI #1 being 0.075 min/flight (160,866 min./2,141,865 flights) against the 0.074 (158,322 min./ 2,139,035 flight) reported above. The reconciliation processes also affected the additional Capacity ENR PI#1 which solely includes the C, R, S, T, M, P reasons of the ATFM delay. It scored 0.010 min/flight.

### **Description of the adjustments to the capacity plan included in adopted performance plan**

N/A

### **Identification and analysis by the NSA of the underlying reasons or circumstances having led to the performance target not being achieved**

Not applicable

### **Recommendations to the ANSP to rectify the situation**

Not applicable

### **Description of the remedial measures that have been / will be taken by the ANSP to rectify the situation. If no measures will be taken by the ANSP, please explain why**

Not applicable

### **Follow up of the remedial measures indicated in the previous monitoring report(s)**

No remedial measures were indicated in the previous monitoring report.

