## SAF1.3. Rate of runway incursions (RIs) (PI#1)

Italy reported 62 runway incursions (RI) during 2025 for all airports listed in the performance plan (49). When comparing the rate of RIs at airport level to Union-wide level, Italy was higher than Union-wide average (3.34 vs 2.53).

In 2025, Italy reported 18 runway incursions with ATS/CNS contribution. When comparing the rate of RIs at airport level with ATS/CNS contribution, Italy was slightly above the Union-wide average (0.97 vs 0.96).

The rate of runway incursions has increased compared to 2024 at both airport level (3.34 vs 2.95) and at ATS/CNS contribution-level (0.97 vs 0.47).

The monitoring report does not list any initiatives implemented or planned to improve either the RI or SMI performance indicators. However, according to the report, the NSA has process in place to monitor RI and SMI reported events, day by day. NSA holds a regular meeting with ENAV to analyse events with focus on the trend. ITAF has an agreement for safety aspect with CAA also. Local CAA representative usually attend the LRST meetings.

Information for ITAF was not submitted in the monitoring report.

