## **2.2.2.I. PI #9**

### **What initiatives were implemented or are planned that will improve this PI and how does the NSA intend on monitoring their effectiveness on performance?**

The daily activity related to the reservation of military areas, as well as the ongoing coordination between the ENAV S.p.A. FUA Unit and the representatives of the Italian Air Force (IAF), is consistently managed with accuracy and with full consideration of all stakeholders. This ensures effective support to both institutional operational requirements and the needs of the ANSP and AUs in terms of planning and air traffic flow management.

This is clearly reflected in the quantitative results at both national and ACC level. Although these indicators represent only the difference (in absolute and percentage terms) between "Reservation" and "Real Activation" time for Italian AMC areas, they nonetheless demonstrate excellent performance. In fact, the "actual utilization" is approximately 50% of the "reserved time", thus maximizing the optimization of airspace restrictions while fully preserving the Air Force's institutional activities.

In relation to the data presented in the tables and acknowledging their indicative nature for the purposes of the Performance Indicator (PI), it should be noted that the reported values reflect only part of the coordination effort and preparatory activities supporting the FUA process. These actions are specifically aimed to "negotiate" the reservation of military areas as much as possible in alignment with actual military operational needs, thereby reducing constraints on the availability of national airspace for Airspace Users' planning and effective utilization.

Such results have been achieved through continuous and daily coordination among all stakeholders, including Italian Air Force representatives and ENAV S.p.A.'s FUA Unit personnel, both inside AMC Italy. Without this optimization of initial allocation requests, it is estimated that the outcome would have resulted in an increase of approximately 20% compared to the original timeframes requested by the Air Force, consequently leading to inefficient use of airspace.

Within this framework of ongoing coordination, the NSA encourages both Air Force representatives and the ENAV S.p.A. FUA Unit to continue strengthening their cooperation. The objective is to further optimize airspace reservation periods in line with actual military needs, thereby reducing airspace unavailability for Airspace Users. This approach is expected to increase airspace availability, improve flight efficiency, and positively impact the relevant performance indicator by enhancing both percentages and overall results.

