## SAF1.1. Effectiveness of Safety Management (EoSM) (KPI#1)

In 2025, ENAV achieved the planned maturity levels set out in its performance plan for all five components of the EoSM. In more detail, ENAV exceeded the planned maturity level in the area of Safety Culture.

In terms of measures put in place to achieve the planned levels, the monitoring report states that the ENAV SpA SMS is working on already adopted measures, and the level of performance is up to the expectations.

For the NSA, as described in the monitoring report, Specific Competent Authority branch monitors SMS performance very closely through audit and information gathered from various sources during the normal oversight actions, i.e. management of changes.

Italy has not submitted the EoSM questionnaire of ITAF.

The monitoring report states that according to internal procedure, ITAF has already in place an SMS process. Every year, ITAF sends the result of safety issues and the remedial actions put in place. Until now, ITAF doesn\'t follow the EoSM questionnaire to measure their performance because it isn\'t binding. The lack of historical values comparable to the requirements of the EoSM questionnaire does not allow Italy to provide information for years 2025-2028 supported by real and/or statistical data. For this reason, also if 2024 is still under RP3, Italy starts to use the EoSM in 2025, for 2024 reference, so Italy can start to understand how the system is working with reference to EoSM approach and how to set it to work better in that way.

