## **ER1.1. SECTION 1 -- UNIT COST**

### **ER1.1.1. AUC VS. DUC**

In 2025, the en route AUC was -2.6% (or -1.48 €2022) lower than the planned DUC. This results from the combination of lower than planned en route costs in real terms (-2.9%, or -20.2 M€2022) and slightly lower than planned TSUs (-0.2%).

### **ER1.1.2. EN ROUTE SERVICE UNITS**

The difference between actual and planned TSUs (-0.2%) falls inside the ±2% dead-band. Hence, the loss of en route revenues is borne by the ANSPs.

### **ER1.1.3. EN ROUTE COSTS BY ENTITY**

Actual real en route costs are -2.9% (-20.2 M€2022) lower than planned. This is the result of lower costs for the main ANSP, ENAV (-3.1%, or -18.8 M€2022), the NSA/EUROCONTROL (-1.9%, or -0.9 M€2022) and the other ANSP (ITAF, -0.9%, or -0.5 M€2022) and slightly higher costs for the MET service provider (+0.7%).

### **ER1.1.4. EN ROUTE COSTS FOR THE MAIN ANSP (ENAV) AT CHARGING ZONE LEVEL**

Based on the additional information to the en route reporting tables, the lower than planned en route costs in real terms for ENAV in 2025 (-3.1%, or -18.8 M€2022) result from:

- Lower than planned staff costs (-2.7%), mainly due to: lower than planned inflation recorded during the year; an agreement to postpone (predominantly) ATCO bonuses, as part of labour contract renewal; reductions in the fixed portion of staff costs due to different hiring dynamics; a lower cost for operational overtime; and higher rate of capitalisation of internal effort.

- Significantly lower than planned other operating costs (-10.3%), mainly due to: lower external support costs from cost-containment measures and greater use of internal expertise; reduced travel expenses following the postponement of some ATCO training sessions; lower utility and telecommunications costs driven by reduced electricity tariffs and partial deployment of the remote towers network; delayed data network infrastructure upgrades for security reasons; and lower infrastructure costs related to the Palermo offshore platforms and Pantelleria control tower.

- Lower than planned depreciation (-2.0%).

- Significantly higher than planned cost of capital (+9.7%), mainly due to higher average cost of debt and significantly higher net current assets.

### **ER1.1.5. ASSESSMENT OF THE ACTUAL PERFORMANCE IN THE CHARGING ZONE REPORTED BY THE NSA**

The NSA of Italy provides the following overall assessment of the actual performance in 2025 at charging zone level:

"*En-route 2025 Italy AUC has been € 55.03, -2.6% compared to the 2025 DUC of € 56.51.*

*Cost reductions have been registered for all Entities. All detailed information are provided in the Additional Information to Reporting Tables uploaded on ETNA.*"

### **ER1.1.6. EXPLANATION OF THE DIFFERENCES BETWEEN ACTUAL AND DETERMINED COSTS AT CHARGING ZONE LEVEL REPORTED BY THE NSA**

The NSA provides the following explanation for the differences between actual and determined costs in the charging zone:

"*Main ANSP reductions refer to: i) Staff costs at company level (lower inflation, 4 M€ postponement to 2026 in application of an agreement part of the renewal of Labour contract, lower operational overtime, higher reductions for internal works capitalized), ii) Operational costs at company level (lower external support, training postponement to 2026, lower utilities costs for lower tariffs), iii) Depreciation for investment postponement (-2 M€ that will be reimbursed to users).*

*Main ANSP increases refer to CoC at company level, as the actual average cost of debt in 2025 was 3.59% as in financial statement (vs 3.10% determined).*"

### **ER1.1.7. RECOMMENDATIONS FORMULATED BY THE NSA TO THE ANSP (ENAV) TO RECTIFY THE SITUATION AND ACTIONS TAKEN BY THE ANSP**

The NSA 2025 monitoring report indicates the following recommendations formulated by the NSA:

"*NSA recommended the ANSP a more precise cost planning for: specific investments and internal works capitalized.*

*NSA recommends as well more transparency in cost planning (specifically for what concerns revenue deductions).*"

ENAV reports the implementation of the following actions:

"*ENAV provided more detailed information regarding investments compared to the previous years. This allowed NSA to provide additional information to reconcile data.*"

### **ER1.1.8. NOTES**

#### **ER1.1.8.1. NOTE 1**

#### **ER1.1.8.2. NOTE 2**

