## PRB1.6. Cost-efficiency {#prb1.6.-cost-efficiency .Heading-2-ER}

- The en route 2025 actual unit cost of Italy was 55.03€2022, -2.6% lower than the determined unit cost (56.51€2022). The terminal zone 1 2025 actual unit cost was 130.11€2022, -1.9% lower than the determined unit cost (132.66€2022), while the terminal zone 2 2025 actual unit cost was 276.75€2022, -1.0% lower than the determined unit cost (279.46€2022).

- The en route 2025 actual service units (12.4M) were in line with the determined service units (12.5M).

- The en route 2025 actual total costs were -20.2M€2022 (-2.9%) lower than determined. This is mainly due to lower other operating costs (-11.2M€2022, or -10.3%), followed by staff costs (-10.2M€2022, or -2.7%) for ENAV. The NSA explained that it is mainly due to a decrease in operational support from external companies, lower travel, utility and telecommunications costs, and lower inflation and cost for overtime.

- ENAV spent 160.2M€2022 in 2025 related to costs of investments for both en route and terminal charging zones, -1.4% less than determined (162.4M€2022). According to the NSA, this reduction is due to delays in some investment programs caused by difficulties in the supply of materials, unstable market conditions, and bureaucratic delays.

- The en route actual unit cost incurred by users in 2025 was 60.89€ (+0.5% above the 2025 DUC). The terminal actual unit cost incurred by users was 142.28€ (in line with the 2025 DUC) for the terminal zone 1, and 304.06€ (+1.1% above the 2025 DUC) for the terminal zone 2. The difference between the AUCU and the DUC for the terminal charging zone 2 is mainly driven by the traffic adjustments.

- The en route regulatory result for ENAV amounted to +70.7M€, or 10.8% of the 2025 revenue. This may indicate that the airspace users are charged for costs which have not materialised in 2025.

