## CAP-ERT5.1. En route ATFM delay per flight (KPI#1)

**En route ATFM delay**

En route capacity is monitored by the average en route air traffic flow management (ATFM) delay generated by en route area control centres (ACCs). In 2025, the Union-wide target for en route capacity was 0.90 minutes of delay per flight.

The target was not achieved in 2025: the actual average en route ATFM delay was 1.64 minutes per flight (after post-ops adjustments), 0.74 minutes per flight above the Union-wide target. One factor in this performance was the inability of some ACCs to accommodate the local increase in IFR movements -- either the general increase or strong peaks in the traffic profile. Other contributing factors are remaining structural issues in a number of areas of the airspace, and delays due to weather, which were lower than in 2024 but still significant.

The traffic demand at network level in 2025 was +4.2% above 2024 traffic, and equalled 2019 traffic for the first time since the COVID-19 pandemic. Despite the traffic growth, en route ATFM delay per flight in 2025 was 25% lower than in 2024. This improvement is encouraging, but it should be acknowledged that a notable part of the reduction in delays was due to the reduced impact of weather and other non-ATC causes. On the other hand, the general improvement is underlined by the fact that the performance of 19 of the 29 ANSPs improved (including improvement in five of the seven ANSPs that did not meet their local target).

Compared to 2024, total delay minutes decreased by -22% to 16.3M. Average delay per flight decreased from 2.19 min/flight in 2024 to 1.64 min/flight in 2025. Main contributors to this -0.55 min/flight reduction in average delays are weather (-0.30 min/flight), ATC capacity (-0.10 min/flight) and other non-ATC (-0.10 min/flight). The main cause of delay in 2025 remains lack of ATC capacity (42% of all delay minutes), followed by weather (28%) and ATC Staffing (17%).

A large majority of the delays in 2025 were accumulated during the summer season, with a clear peak in July, when the average delay was 3.87 min/flight. The improvement in performance compared to 2024 was also visible here, as the peak in July 2024 was 5.85 min/flight. Similar reductions occurred in June (4.06 in 2024; 2.52 in 2025) and August (4.38 in 2024; 2.69 in 2025).

Although the reduction in delays due to weather played a large role in the performance improvement, this is not only due to a reduction in disruptive weather events. Improved handling of the impact of such events, for example at network level through the introduction of the Capacity and Weather Based Operations (CWBO) procedures introduced by the Network Manager for summer 2025, has had a positive effect.

Improvements in Union-wide performance are also visible in other indicators related to average en route ATFM delays: the average delay per delayed flight decreased from 18.40 min/flight to 16.90 min/flight, the share of flights experiencing any ATFM delay reduced from 11.9% to 9.7%, and the share of delayed flights experiencing an ATFM delay of more than 15 minutes reduced from 5.0% to 3.7%.

**En route incentive scheme**

Based on the parameters defined by the Member States in their performance plans and their respective 2025 performance in en route capacity, 15 ANSPs are eligible for a bonus -- however, for four of these ANSPs the maximum bonus has been set to 0%, meaning there is no financial effect. Six ANSPs are subject to a financial penalty. The total amount of bonuses equals 20.9M€, while total penalties amount to -23.3M€, giving a net effect of -2.4M€ to be returned to users.

