## CEF-ERT7.3. Regulatory Result

The Union-wide en route regulatory result for 2025 is 380.0M€, representing 5.0% of the total yearly revenues. After the actual value of the return on equity (+278.1M€), the largest net gain in 2025 came from the traffic risk sharing (+63.0M€).

Three of the main ANSPs recorded negative en route regulatory results in 2025: LPS SR (-6.4M€, or -8.5% of the yearly revenues), LVNL (-2.3M€, or -1.0% of the yearly revenues), and NAVIAIR (-0.5M€, or -0.5% of the yearly revenues). The main ANSPs with the highest regulatory result in terms of percentage of the yearly revenues are: MATS (+18.5%), Austro Control (+13.3%), and EANS (+10.9%).

When divided by the actual service units, the (unit) regulatory result is directly comparable with the AUCU. The regulatory result per actual en route service unit was equal to 2.74€ in 2025, which means that 4.7% of the true cost of the service was related to the "margin" generated by the ANSPs with respect to their 2025 activities.

# CEF-TRM8. Terminal Cost-efficiency performance -- SES RP4

